### ISSUE TITLE
Worldgen crash

### ISSUE THREAD

**Issue by the-creamster** [TechReborn/TechReborn#1010]
I'm getting the following crash during modpack loading:
https://gist.github.com/the-creamster/7fdd6dc5794403795c978445a716b0d4

My "ores.hjson" config has the identical settings as to that as reported in #983

Modpack information:
- MC 1.10.2
- Latest forge
- Latest RC/TR builds

**Comment by modmuss50** [comment]
Could you try deleting the ores.hjson file and allowing it to regen?

**Comment by the-creamster** [comment]
I've deleted the file but the pack doesn't load because of the following crash;
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177596_a(ModelBakery.java:441)
	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:320)
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:170)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:148)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
