### ISSUE TITLE
[1.12.1] Crush with Failed to get ore name:gemTitanium

### ISSUE THREAD

**Issue by Smartaros** [TechReborn/TechReborn#1275]
Forge 1.12.1-14.22.1.2478

`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tech Reborn (techreborn)
Caused by: java.lang.RuntimeException: Failed to get ore name:gemTitanium
	at reborncore.common.util.OreUtil.getStackFromName(OreUtil.java:56)
	at techreborn.init.ModRecipes.addCompressorRecipes(ModRecipes.java:146)
	at techreborn.init.ModRecipes.init(ModRecipes.java:88)
	at techreborn.Core.preinit(Core.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:609)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)`

**Comment by drcrazy** [comment]
Hi @Smartaros, what mod adds gemTitanium in your pack?

**Comment by Smartaros** [comment]
The reason is infinitic, but it does not add gemTitanium, it adds material from titanium for tinkersconstruct

**Comment by drcrazy** [comment]
What is in your json config?

**Comment by Smartaros** [comment]
`{
	"name": "Titanium",
	"textColor": "#FFE2F9FF",
	"whitelist": {
		"oredict": [],
		"ingots": ["techreborn:ingot:14"],
		"nuggets": [],
		"dusts": [],
		"gems": [],
		"blocks": ["techreborn:storage:2"],
		"ores": []
	},
	"blacklist": {
		"oredict": ["gemTitanium"],
		"ores": []
	},
	"fluidData": {
		"color": "#FFE2F9FF",
		"density": 2000,
		"viscosity": 10000,
		"temperature": 800,
		"luminosity": 10,
		"rarity": "COMMON"
	},
	"canCraftToolForge": true,
	"toolData": {
		"durability": 1250,
		"harvestLevel": 6,
		"extraDurability": 250,
		"miningSpeed": 12.0,
		"attack": 10.0,
		"handleModifier": 1.1,
		"color": "#FFE2F9FF",
		"temperature": 200,
		"projectiles": false,
		"drawSpeed": 1.0,
		"range": 1.0,
		"bonusDamage": 0.0,
		"stringModifier": 0.0,
		"shaftModifier": 1.0,
		"bonusAmmo": 0.0,
		"accuracy": 1.0,
		"fletchingModifier": 1.0,
	    "traits": ["lightweight", "dense"]
	},
	"localizations": [{
		"locale": "en_US",
		"solid": "Titanium",
		"liquid": "Molten Titanium",
		"bucket": "Titanium Bucket"
	}]
}`

**Comment by Smartaros** [comment]
"name": "Titanium",
	"textColor": "#FFE2F9FF",
	"whitelist": {
		"oredict": [],
		"ingots": ["techreborn:ingot:14"],
		"nuggets": [],
		"dusts": [],
		"gems": [],
		"blocks": ["techreborn:storage:2"],
		"ores": []
	},
	"blacklist": {
		"oredict": [],
		"ores": []
	},
	"fluidData": {
		"color": "#FFE2F9FF",
		"density": 2000,
		"viscosity": 10000,
		"temperature": 800,
		"luminosity": 10,
		"rarity": "COMMON"
	},
	"canCraftToolForge": true,
	"toolData": {
		"durability": 1250,
		"harvestLevel": 6,
		"extraDurability": 250,
		"miningSpeed": 12.0,
		"attack": 10.0,
		"handleModifier": 1.1,
		"color": "#FFE2F9FF",
		"temperature": 200,
		"projectiles": false,
		"drawSpeed": 1.0,
		"range": 1.0,
		"bonusDamage": 0.0,
		"stringModifier": 0.0,
		"shaftModifier": 1.0,
		"bonusAmmo": 0.0,
		"accuracy": 1.0,
		"fletchingModifier": 1.0,
	    "traits": ["lightweight", "dense"]
	},
	"localizations": [{
		"locale": "en_US",
		"solid": "Titanium",
		"liquid": "Molten Titanium",
		"bucket": "Titanium Bucket"
	}]

**Comment by Smartaros** [comment]
"name": "Titanium",
	"textColor": "#FFE2F9FF",
	"whitelist": {
		"oredict": [],
		"ingots": ["techreborn:ingot:14"],
		"nuggets": [],
		"dusts": [],
		"gems": [],
		"blocks": ["techreborn:storage:2"],
		"ores": []
	},
	"blacklist": {
		"oredict": [],
		"ores": []
	},
	"fluidData": {
		"color": "#FFE2F9FF",
		"density": 2000,
		"viscosity": 10000,
		"temperature": 800,
		"luminosity": 10,
		"rarity": "COMMON"
	},
	"canCraftToolForge": true,
	"toolData": {
		"durability": 1250,
		"harvestLevel": 6,
		"extraDurability": 250,
		"miningSpeed": 12.0,
		"attack": 10.0,
		"handleModifier": 1.1,
		"color": "#FFE2F9FF",
		"temperature": 200,
		"projectiles": false,
		"drawSpeed": 1.0,
		"range": 1.0,
		"bonusDamage": 0.0,
		"stringModifier": 0.0,
		"shaftModifier": 1.0,
		"bonusAmmo": 0.0,
		"accuracy": 1.0,
		"fletchingModifier": 1.0,
	    "traits": ["lightweight", "dense"]
	},
	"localizations": [{
		"locale": "en_US",
		"solid": "Titanium",
		"liquid": "Molten Titanium",
		"bucket": "Titanium Bucket"
	}]

**Comment by drcrazy** [comment]
is it still crashing with gem removed from blacklist?

**Comment by Smartaros** [comment]
"blacklist": {
		"oredict": ["gem"],
		"ores": []
	}

...same crush

**Comment by drcrazy** [comment]
can you not mention gem at all?
