### ISSUE TITLE
LESU - Server console error

### ISSUE THREAD

**Issue by FilipK-CZ** [TechReborn/TechReborn#1369]
LESU give error in console after connected to power source

```
[23:17:51] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: techreborn/client/IconSupplier
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_151]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-2555-7.0.0-BETA-2774]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zif000(MinecraftServer.java:4008) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: techreborn/client/IconSupplier
        at techreborn.client.container.builder.ContainerPlayerInventoryBuilder$ContainerPlayerArmorInventoryBuilder.helmet(ContainerPlayerInventoryBuilder.java:105) ~[ContainerPlayerInventoryBuilder$ContainerPlayerArmorInventoryBuilder.class:?]
        at techreborn.client.container.builder.ContainerPlayerInventoryBuilder$ContainerPlayerArmorInventoryBuilder.complete(ContainerPlayerInventoryBuilder.java:121) ~[ContainerPlayerInventoryBuilder$ContainerPlayerArmorInventoryBuilder.class:?]
        at techreborn.tiles.lesu.TileLapotronicSU.createContainer(TileLapotronicSU.java:134) ~[TileLapotronicSU.class:?]
        at techreborn.client.GuiHandler.getServerGuiElement(GuiHandler.java:58) ~[GuiHandler.class:?]
        at net.minecraftforge.fml.common.network.NetworkRegistry.redirect$setRemoteContainerPlugin$bac000(NetworkRegistry.java:547) ~[NetworkRegistry.class:?]
        at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:254) ~[NetworkRegistry.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:87) ~[FMLNetworkHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
        at techreborn.blocks.storage.BlockEnergyStorage.func_180639_a(BlockEnergyStorage.java:109) ~[BlockEnergyStorage.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1746) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zhk000(NetHandlerPlayServer.java:2376) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151) ~[PacketUtil.class:1.12.2-2555-7.0.0-BETA-2774]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjp000(SourceFile:539) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more

```

**Comment by modmuss50** [comment]
This should have been fixed in the latest version.
