### ISSUE TITLE
[1.10.2] Compatibility issue with Minecolony

### ISSUE THREAD

**Issue by yotthani** [TechReborn/TechReborn#1419]
in combination with latest minecolony server crashing at startup with this exception:

Time: 12/22/17 9:05 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
at exterminatorjeff.undergroundbiomes.common.block.UBOreSedimentary.func_180642_a(UBOreSedimentary.java:42)
at com.minecolonies.api.compatibility.CompatabilityManager.discoverOres(CompatabilityManager.java:162)
at com.minecolonies.api.compatibility.CompatabilityManager.discover(CompatabilityManager.java:63)
at com.minecolonies.coremod.colony.ColonyManager.readFromNBT(ColonyManager.java:818)
at com.minecolonies.coremod.colony.ColonyManager.onWorldLoad(ColonyManager.java:716)
at com.minecolonies.coremod.event.EventHandler.onWorldLoad(EventHandler.java:397)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_814_EventHandler_onWorldLoad_Load.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:263)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
at java.lang.Thread.run(Unknown Source)

**Comment by modmuss50** [comment]
can you post a log? or explain what is wrong? I assume its the same as this issue: https://github.com/TechReborn/TechReborn/issues/1414

**Comment by yotthani** [comment]
sorry just hit return in the false momen was still typing, issue is now explained

**Comment by modmuss50** [comment]
That looks like an issue with undergroundbiomes, I would contact the minecolonies guys and see what is up
