### ISSUE TITLE
Viewing possible uses for Centrifuge block crashes client.

### ISSUE THREAD

**Issue by Darkfiend009** [TechReborn/TechReborn#1578]
I have TechReborn in a modpack i am creating for my streaming community. We test all the mods that we add to the pack as extensively as possible and ran into this issue today. We were looking at ways to make pulverized coal and clicked on the Centrifuge tab:

[crash-2018-08-16_15.06.34-client.txt](https://github.com/TechReborn/TechReborn/files/2294966/crash-2018-08-16_15.06.34-client.txt)

`8/16/18 3:06 PM
Description: Rendering screenjava.lang.NullPointerException: Rendering screen
	at reborncore.common.powerSystem.PowerSystem.getRoundedString(PowerSystem.java:133)
	at reborncore.common.powerSystem.PowerSystem.getLocaliszedPowerFormatted(PowerSystem.java:85)
	at techreborn.compat.jei.centrifuge.CentrifugeRecipeWrapper.drawInfo(CentrifugeRecipeWrapper.java:64)
	at mezz.jei.gui.recipes.RecipeLayout.drawRecipe(RecipeLayout.java:158)
	at mezz.jei.gui.recipes.RecipesGui.func_73863_a(RecipesGui.java:215)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

**Comment by modmuss50** [comment]
Please can you try on the latest forge version as this might be related to 

https://github.com/MinecraftForge/MinecraftForge/pull/5105
and
https://github.com/bdew/gendustry/issues/277

Has this issue just started today? Have you updated your mods and then this issue starts. This code has not been touched since May 4th.

**Comment by shadoxxhd** [comment]
I just created a pull request for the issue. Nothing too sophisticated, but should do the job until microsoft fixes their end of the problem.

**Comment by Darkfiend009** [comment]
I had recently just updated Forge. I also just added the mod to the pack, so it's the newest version of the mod. It's new to the pack altogether. So i can't say if the issue has been happening or not as i only have today as a snapshot. 

I also do not have gendustry installed in the modpack.

**Comment by modmuss50** [comment]
This issue has been fixed by forge and mojang, its not our responsibility to fix forge/mojang issues.

See https://github.com/TechReborn/RebornCore/issues/90 for more detail.
