### ISSUE TITLE
TR - Game crash when looking certains Items in Creative Inventory

### ISSUE THREAD

**Issue by starkimax** [TechReborn/TechReborn#1591]
```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 8/26/18 11:50 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at reborncore.common.powerSystem.PowerSystem.getRoundedString(PowerSystem.java:133)
	at reborncore.common.powerSystem.PowerSystem.getLocaliszedPowerFormattedNoSuffix(PowerSystem.java:93)
	at techreborn.events.StackToolTipEvent.handleItemTooltipEvent(StackToolTipEvent.java:61)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_33_StackToolTipEvent_handleItemTooltipEvent_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:334)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.gui.GuiScreen.func_191927_a(GuiScreen.java:143)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146285_a(GuiContainerCreative.java:737)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:684)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at reborncore.common.powerSystem.PowerSystem.getRoundedString(PowerSystem.java:133)
	at reborncore.common.powerSystem.PowerSystem.getLocaliszedPowerFormattedNoSuffix(PowerSystem.java:93)
	at techreborn.events.StackToolTipEvent.handleItemTooltipEvent(StackToolTipEvent.java:61)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_33_StackToolTipEvent_handleItemTooltipEvent_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:334)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.gui.GuiScreen.func_191927_a(GuiScreen.java:143)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146285_a(GuiContainerCreative.java:737)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:684)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (285, 152). Absolute: (570, 188)
	Screen size: Scaled: (427, 247). Absolute: (854, 494). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['starkmax'/909, l='MpServer', x=-288.50, y=76.00, z=-32.50]]
	Chunk stats: MultiplayerChunkCache: 529, 529
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-286,64,-31), Chunk: (at 2,4,1 in -18,-2; contains blocks -288,0,-32 to -273,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 179 game time, 179 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 64 total; [EntitySheep['Sheep'/99, l='MpServer', x=-345.26, y=64.00, z=-100.49], EntitySheep['Sheep'/100, l='MpServer', x=-343.22, y=64.00, z=-88.64], EntitySheep['Sheep'/101, l='MpServer', x=-340.23, y=64.00, z=-93.38], EntitySheep['Sheep'/102, l='MpServer', x=-334.50, y=64.00, z=-93.50], EntitySheep['Sheep'/106, l='MpServer', x=-316.50, y=54.00, z=-82.50], EntitySheep['Sheep'/107, l='MpServer', x=-318.50, y=61.00, z=-83.50], EntitySheep['Sheep'/108, l='MpServer', x=-322.19, y=64.00, z=-82.53], EntitySheep['Sheep'/109, l='MpServer', x=-321.90, y=64.00, z=-83.75], EntityRabbit['Rabbit'/112, l='MpServer', x=-309.50, y=77.00, z=-58.50], EntityRabbit['Rabbit'/113, l='MpServer', x=-307.50, y=77.00, z=-57.50], EntityRabbit['Rabbit'/114, l='MpServer', x=-310.50, y=76.00, z=-60.50], EntityRabbit['Rabbit'/115, l='MpServer', x=-286.50, y=71.00, z=-17.50], EntitySpider['Spider'/4211, l='MpServer', x=-219.99, y=15.00, z=-46.99], EntityRabbit['Rabbit'/116, l='MpServer', x=-285.50, y=71.00, z=-16.50], EntityCreeper['Creeper'/4212, l='MpServer', x=-229.50, y=15.00, z=-47.50], EntityRabbit['Rabbit'/117, l='MpServer', x=-307.50, y=67.00, z=20.50], EntityRabbit['Rabbit'/118, l='MpServer', x=-309.50, y=69.00, z=16.50], EntityRabbit['Rabbit'/119, l='MpServer', x=-307.50, y=68.00, z=15.50], EntityRabbit['Rabbit'/120, l='MpServer', x=-308.50, y=68.00, z=17.50], EntityRabbit['Rabbit'/121, l='MpServer', x=-306.50, y=67.00, z=14.50], EntityRabbit['Rabbit'/122, l='MpServer', x=-311.44, y=70.28, z=14.50], EntityRabbit['Rabbit'/123, l='MpServer', x=-297.50, y=66.00, z=26.50], EntityRabbit['Rabbit'/124, l='MpServer', x=-301.50, y=67.00, z=26.50], EntityRabbit['Rabbit'/125, l='MpServer', x=-294.50, y=75.00, z=-69.50], EntityRabbit['Rabbit'/126, l='MpServer', x=-289.24, y=77.23, z=-68.68], EntitySkeleton['Skeleton'/4226, l='MpServer', x=-368.50, y=17.00, z=29.23], EntityCreeper['Creeper'/4229, l='MpServer', x=-321.50, y=18.00, z=42.50], EntityCreeper['Creeper'/4237, l='MpServer', x=-237.50, y=49.00, z=28.50], EntitySkeleton['Skeleton'/4267, l='MpServer', x=-315.50, y=53.00, z=-55.50], EntitySkeleton['Skeleton'/4302, l='MpServer', x=-358.79, y=28.00, z=-40.51], EntitySpider['Spider'/4332, l='MpServer', x=-348.50, y=35.00, z=21.50], EntitySpider['Spider'/4333, l='MpServer', x=-344.02, y=31.87, z=25.70], EntitySkeleton['Skeleton'/4334, l='MpServer', x=-345.80, y=34.18, z=22.50], EntitySkeleton['Skeleton'/4335, l='MpServer', x=-341.50, y=35.00, z=22.89], EntitySkeleton['Skeleton'/4411, l='MpServer', x=-352.50, y=64.00, z=23.50], EntitySkeleton['Skeleton'/4412, l='MpServer', x=-353.50, y=64.00, z=23.50], EntityZombie['Zombie'/4414, l='MpServer', x=-352.50, y=64.00, z=24.50], EntityZombie['Zombie'/4600, l='MpServer', x=-225.50, y=13.00, z=-12.50], EntityZombie['Zombie'/4689, l='MpServer', x=-341.01, y=36.00, z=24.53], EntityZombie['Zombie'/4690, l='MpServer', x=-340.44, y=36.00, z=24.85], EntityZombie['Zombie'/4709, l='MpServer', x=-354.50, y=16.00, z=43.50], EntityCreeper['Creeper'/4710, l='MpServer', x=-354.50, y=16.00, z=44.50], EntitySkeleton['Skeleton'/4720, l='MpServer', x=-343.50, y=26.00, z=-72.50], EntityCreeper['Creeper'/4779, l='MpServer', x=-348.50, y=72.00, z=8.50], EntitySpider['Spider'/4819, l='MpServer', x=-282.00, y=28.00, z=13.72], EntityCreeper['Creeper'/4987, l='MpServer', x=-213.16, y=48.00, z=-69.42], EntitySkeleton['Skeleton'/5100, l='MpServer', x=-323.50, y=12.00, z=-57.50], EntitySkeleton['Skeleton'/5160, l='MpServer', x=-362.50, y=74.00, z=10.50], EntityZombie['Zombie'/5175, l='MpServer', x=-338.50, y=32.00, z=22.50], EntityZombie['Zombie'/5176, l='MpServer', x=-337.87, y=32.00, z=23.55], EntityZombie['Zombie'/5177, l='MpServer', x=-340.50, y=32.00, z=25.50], EntityZombie['Zombie'/5178, l='MpServer', x=-347.50, y=32.00, z=25.50], EntityBat['Bat'/1800, l='MpServer', x=-224.50, y=29.84, z=21.25], EntityBat['Bat'/1907, l='MpServer', x=-218.25, y=52.97, z=-64.62], EntityBat['Bat'/1998, l='MpServer', x=-352.51, y=39.23, z=-9.23], EntityPlayerSP['starkmax'/909, l='MpServer', x=-288.50, y=76.00, z=-32.50], EntitySpider['Spider'/3741, l='MpServer', x=-356.67, y=63.00, z=30.30], EntityCreeper['Creeper'/3778, l='MpServer', x=-339.50, y=24.00, z=9.50], EntityCreeper['Creeper'/3802, l='MpServer', x=-264.50, y=47.00, z=-25.50], EntityBat['Bat'/3880, l='MpServer', x=-282.56, y=21.05, z=-47.21], EntityBat['Bat'/3921, l='MpServer', x=-236.22, y=51.28, z=-51.31], EntityCreeper['Creeper'/3975, l='MpServer', x=-344.50, y=37.00, z=-19.50], EntityBat['Bat'/3994, l='MpServer', x=-240.25, y=51.64, z=-45.39], EntityBat['Bat'/4021, l='MpServer', x=-222.02, y=39.66, z=11.58]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4390805544 bytes (4187 MB) / 5281480704 bytes (5036 MB) up to 6355222528 bytes (6060 MB)
	JVM Flags: 4 total; -XX:-UseAdaptiveSizePolicy -XX:+UseConcMarkSweepGC -Xms5G -Xmx6G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2758 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
```

	| State     | ID         | Version      | Source                                     | Signature                                |
	|:--------- |:---------- |:------------ |:------------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft  | 1.12.2       | minecraft.jar                              | None                                     |
	| UCHIJAAAA | mcp        | 9.42         | minecraft.jar                              | None                                     |
	| UCHIJAAAA | FML        | 8.0.99.99    | forge-1.12.2-14.23.4.2758.jar              | None                                     |
	| UCHIJAAAA | forge      | 14.23.4.2758 | forge-1.12.2-14.23.4.2758.jar              | None                                     |
	| UCHIJAAAA | reborncore | 3.10.0.332   | RebornCore-1.12.2-3.10.0.332-universal.jar | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAA | techreborn | 2.17.1.786   | TechReborn-1.12.2-2.17.1.786-universal.jar | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.01' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.10.0.332
		Runtime Debofucsation 1
		RenderEngine: 0
	Launched Version: 1.10.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>`

**Comment by drcrazy** [comment]
Why do you have "Current Language: ~~ERROR~~ NullPointerException: null"

There was an issue with MC and Forge week ago. Have you updated your MC since then?

**Comment by modmuss50** [comment]
not us, reinstall forge + mc if the issue continues
