### ISSUE TITLE
Crash when trying to use the rolling machine.

### ISSUE THREAD

**Issue by pupnewfster** [TechReborn/TechReborn#1666]
Tech Reborn version: 2.20.7.915 
Reborn Core version: 3.13.3.416
Forge: 14.23.5.2808

```
java.lang.ArithmeticException: / by zero
    at techreborn.tiles.tier1.TileRollingMachine.balanceRecipe(TileRollingMachine.java:220)
    at techreborn.tiles.tier1.TileRollingMachine.update(TileRollingMachine.java:123)
    at net.minecraft.world.World.redirect$tileEntityUpdate$zzn000(World.java:4131)
    at net.minecraft.world.World.updateEntities(World.java:1835)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by pupnewfster** [comment]
This was happening when attempting to make nichrome heating coils. It doesn't happen every time but once a crash is caused by a rolling machine the world will not load again. (It also happened when I was messing around with locking mid recipe making not sure if that has to do with it. I recommend just adding a safety check that if slots is zero then it does not try to balance.
