### ISSUE TITLE
Crash upon opening Rolling Machine GUI

### ISSUE THREAD

**Issue by LordEpos** [TechReborn/TechReborn#1676]
Not 100% sure what the cause is, but there was a game freeze and then crash when I opened the rolling machine. This is using the five day old version, which isn't quite up to date, but none of the changelogs mention a fix for this, so I think it's reasonable to assume it's still an issue.

My best guess is that there's some old code in there for copying recipes from Railcraft's rolling machine in 1.10, that don't know what to do with the 1.12 version of that mod, but honestly, I have no idea if that's even a feature.

Crash report below:
[19:23:43] [Client thread/FATAL] [minecraft/Minecraft]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1151) ~[buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoSuchFieldError: builder
	at techreborn.client.gui.GuiRollingMachine.func_146976_a(GuiRollingMachine.java:64) ~[GuiRollingMachine.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75) ~[bmg.class:?]
	at reborncore.client.gui.builder.GuiBase.func_73863_a(GuiBase.java:195) ~[GuiBase.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) ~[buq.class:?]
	... 17 more
[19:23:43] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.1.jar)
  RandomPatches (randompatches-1.12.2-1.8.0.0.jar)
  BiggerPacketsPlzCoreMod (biggerpacketsplz-1.0.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.44.jar)
  ToolProgressionPlugin (toolprogression-core-1.12.2-1.6.5.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.4.jar)
  AstralCore (astralsorcery-1.12.2-1.10.11 (1).jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  HCASM (HammerCore-1.12.2-2.0.4.1.jar)
  FastLangLoadingPlugin (fastlang-1.1.jar)
  llibrary (llibrary-core-1.0.10-1.12.2.jar)
  LoadingPlugin (Quark-r1.5-133.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.15 (2).jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 3/2/19 7:23 PM
Description: Rendering screen

java.lang.NoSuchFieldError: builder
	at techreborn.client.gui.GuiRollingMachine.func_146976_a(GuiRollingMachine.java:64)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at reborncore.client.gui.builder.GuiBase.func_73863_a(GuiBase.java:195)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at techreborn.client.gui.GuiRollingMachine.func_146976_a(GuiRollingMachine.java:64)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at reborncore.client.gui.builder.GuiBase.func_73863_a(GuiBase.java:195)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: techreborn.client.gui.GuiRollingMachine
	Mouse location: Scaled: (420, 262). Absolute: (840, 525)
	Screen size: Scaled: (840, 525). Absolute: (1680, 1050). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['ArloTheEpic'/404, l='MpServer', x=1247.34, y=65.74, z=-92.90]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 07 - buffet, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (1258,64,-107), Chunk: (at 10,4,5 in 78,-7; contains blocks 1248,0,-112 to 1263,255,-97), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
	Level time: 41243 game time, 41243 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 40 total; [EntityLocomotiveCreative['Perpetuum Locomotive'/144003, l='MpServer', x=1251.66, y=64.06, z=-92.84], EntityBabySkeleton['Baby Skeleton'/140295, l='MpServer', x=1263.50, y=32.00, z=-123.50], EntityCreeper['Creeper'/145160, l='MpServer', x=1260.05, y=32.00, z=-128.30], EntitySkeleton['Skeleton'/145166, l='MpServer', x=1202.50, y=47.00, z=-56.50], EntityCartChest['Chest Cart'/144524, l='MpServer', x=1251.51, y=64.06, z=-94.77], EntitySkeleton['Skeleton'/145165, l='MpServer', x=1201.50, y=47.00, z=-57.50], EntityColoredItemFrame['Colored Item Frame'/26258, l='MpServer', x=1269.97, y=103.50, z=-96.50], EntityCreeper['Creeper'/145174, l='MpServer', x=1255.46, y=65.00, z=-64.16], EntityColoredItemFrame['Colored Item Frame'/42261, l='MpServer', x=1269.97, y=101.50, z=-94.50], EntityColoredItemFrame['Colored Item Frame'/43158, l='MpServer', x=1269.97, y=101.50, z=-93.50], EntityColoredItemFrame['Colored Item Frame'/26912, l='MpServer', x=1269.97, y=101.50, z=-99.50], EntityCartChest['Chest Cart'/144417, l='MpServer', x=1251.55, y=64.06, z=-93.69], EntityRabbit['Rabbit'/164, l='MpServer', x=1230.63, y=71.00, z=-130.52], EntityRabbit['Rabbit'/166, l='MpServer', x=1230.14, y=71.00, z=-131.44], EntityColoredItemFrame['Colored Item Frame'/26534, l='MpServer', x=1269.97, y=102.50, z=-98.50], EntityColoredItemFrame['Colored Item Frame'/46248, l='MpServer', x=1269.97, y=100.50, z=-95.50], EntityPlayerSP['ArloTheEpic'/404, l='MpServer', x=1247.34, y=65.74, z=-92.90], EntityItem['item.item.string'/141357, l='MpServer', x=1231.13, y=67.00, z=-92.99], EntityMummy['Mummy'/141498, l='MpServer', x=1267.57, y=65.00, z=-61.50], EntityPlayerSP['ArloTheEpic'/404, l='MpServer', x=1239.38, y=67.00, z=-154.28], EntityScorpion['Scorpion'/145086, l='MpServer', x=1274.92, y=65.00, z=-75.91], EntityScorpion['Scorpion'/145214, l='MpServer', x=1209.50, y=68.00, z=-78.50], EntityCreeper['Creeper'/141500, l='MpServer', x=1212.17, y=70.00, z=-106.83], EntityScorpion['Scorpion'/145213, l='MpServer', x=1216.94, y=68.00, z=-73.13], EntityScorpion['Scorpion'/145089, l='MpServer', x=1277.50, y=65.00, z=-71.50], EntityScorpion['Scorpion'/145217, l='MpServer', x=1208.50, y=68.00, z=-82.50], EntityFester['Fester'/144968, l='MpServer', x=1229.50, y=30.00, z=-129.50], EntityItem['item.item.leather'/143309, l='MpServer', x=1277.54, y=11.00, z=-103.46], EntityCreeper['Creeper'/144973, l='MpServer', x=1243.83, y=67.00, z=-57.17], EntitySilverfish['Silverfish'/145229, l='MpServer', x=1296.50, y=71.00, z=-84.94], EntityColoredItemFrame['Colored Item Frame'/26452, l='MpServer', x=1269.97, y=103.50, z=-97.50], EntityScorpion['Scorpion'/141151, l='MpServer', x=1221.13, y=70.00, z=-120.01], EntityFester['Fester'/144611, l='MpServer', x=1246.50, y=67.00, z=-133.50], EntityCreeper['Creeper'/144864, l='MpServer', x=1206.50, y=69.00, z=-92.50], EntityColoredItemFrame['Colored Item Frame'/36073, l='MpServer', x=1269.97, y=102.50, z=-95.50], EntityColoredItemFrame['Colored Item Frame'/35696, l='MpServer', x=1269.97, y=103.50, z=-95.50], EntityCreeper['Creeper'/145266, l='MpServer', x=1206.50, y=70.00, z=-135.50], EntityFester['Fester'/145019, l='MpServer', x=1280.50, y=16.00, z=-137.50], EntityFester['Fester'/145151, l='MpServer', x=1209.50, y=69.00, z=-45.50], EntityFester['Fester'/145020, l='MpServer', x=1284.50, y=16.00, z=-140.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 851482704 bytes (812 MB) / 5712117760 bytes (5447 MB) up to 5726797824 bytes (5461 MB)

**Comment by modmuss50** [comment]
Make sure you are using the latest version of TechReborn AND RebornCore, there seems to be some version mis match between the two.

**Comment by modmuss50** [comment]
no response so closing.

**Comment by LordEpos** [comment]
Yep, sorry for lack of response, my reborn core was out of date and updating fixed the issue.
