### ISSUE TITLE
crash when updating to V0.5.2.896

### ISSUE THREAD

**Issue by bear989** [TechReborn/TechReborn#168]
running forestry 4 and IC2 Exp @780 from V0.5.1.891

---- Minecraft Crash Report ----
// You're mean.

Time: 10/6/15 3:04 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.AbstractMethodError
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.AbstractMethodError
	at forestry.apiculture.genetics.BeeHelper.registerMutation(BeeHelper.java:248)
	at Reika.DragonAPI.ModInteract.Bees.BeeSpecies.addBreeding(BeeSpecies.java:313)
	at Reika.DragonAPI.ModInteract.Bees.BeeSpecies.addBreeding(BeeSpecies.java:294)
	at Reika.RotaryCraft.RotaryCraft.postload(RotaryCraft.java:512)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 824674624 bytes (786 MB) / 1331691520 bytes (1270 MB) up to 1789919232 bytes (1707 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx1920m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1517 22 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1517-1.7.10-universal.jar) 
	UCHIJ	Forge{10.13.4.1517} [Minecraft Forge] (forge-1.7.10-10.13.4.1517-1.7.10-universal.jar) 
	UCHIJ	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJ	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHIJ	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJ	BuildCraft|Core{7.1.5} [BuildCraft] (buildcraft-7.1.5.jar) 
	UCHIJ	BuildCraft|Builders{7.1.5} [BC Builders] (buildcraft-7.1.5.jar) 
	UCHIJ	BuildCraft|Transport{7.1.5} [BC Transport] (buildcraft-7.1.5.jar) 
	UCHIJ	BuildCraft|Energy{7.1.5} [BC Energy] (buildcraft-7.1.5.jar) 
	UCHIJ	BuildCraft|Silicon{7.1.5} [BC Silicon] (buildcraft-7.1.5.jar) 
	UCHIJ	BuildCraft|Robotics{7.1.5} [BC Robotics] (buildcraft-7.1.5.jar) 
	UCHIJ	BuildCraft|Factory{7.1.5} [BC Factory] (buildcraft-7.1.5.jar) 
	UCHIJ	Forestry{4.0.6.34} [Forestry for Minecraft] (forestry_1.7.10-4.0.6.34.jar) 
	UCHIJ	BuildCraft|Compat{7.1.0} [BuildCraft Compat] (buildcraft-compat-7.1.0.jar) 
	UCHIJ	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V9b.jar) 
	UCHIE	RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V9b.jar) 
	UCHIE	ElectriCraft{1.0} [ElectriCraft] (ElectriCraft 1.7.10 V9b.jar) 
	UCHIJ	ImmersiveEngineering{0.5.4} [Immersive Engineering] (ImmersiveEngineering-0.5.4.jar) 
	UCHIE	ReactorCraft{1.0} [ReactorCraft] (ReactorCraft 1.7.10 V9b.jar) 
	UCHIJ	techreborn{0.5.1.891} [TechReborn] (TechReborn-0.5.1.891-universal.jar) 
	UD	techrebornasm{000} [Techreborn-ASM] (minecraft.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.06' Renderer: 'GeForce GT 720/PCIe/SSE2'

**Comment by modmuss50** [comment]
And this didn't happen before, because the crash looks like its from DragonAPI

**Comment by bear989** [comment]
dragon API isn't loaded in this pack and no it ran fine before

**Comment by Rongmario** [comment]
Why does it list you have DragonAPI and it's mods enabled then? -.-

**Comment by bear989** [comment]
I went in and looked though the .mincraft fold and 1 dragonAPI file, not
even in the mods or config folder. Everything working fine now. thanks for
the help and sorry for the issue

**Comment by Rongmario** [comment]
No worries, please check thoroughly through your file next time :D
