### ISSUE TITLE
net.minecraft.block.BlockAir cannot be cast to techreborn.blocks.BlockMachineCasing

### ISSUE THREAD

**Issue by bluelightning32** [TechReborn/TechReborn#1740]
I'm running a DD&SS server. It crashed with the following stack trace. So far none of the players have explained what they did to cause it.

This is the stack trace:
```
Time: 2019-07-28 16:48:50 PDT
Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to techreborn.blocks.BlockMachineCasing
    at techreborn.tiles.multiblock.TileIndustrialBlastFurnace.getHeat(TileIndustrialBlastFurnace.java:94)
    at reborncore.client.containerBuilder.builder.BuiltContainer.detectAndSendChanges(BuiltContainer.java:167)
    at net.minecraft.entity.player.InventoryPlayer.cleanupDirty(InventoryPlayer.java:1778)
    at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:195)
    at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:418)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_768_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:756)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:706)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:657)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```

Full crash report:
https://gist.github.com/bluelightning32/86bf28496190f350bf205f297b8e27b9

I didn't see any more helpful information in the server log.

Modpack: DD&SS 5.5a
Relevant mods:
* forge-1.12.2-14.23.5.2836-universal.jar
* spongeforge-1.12.2-2838-7.1.7-RC3785.jar
* TechReborn-1.12.2-2.22.1.979-universal.jar

**Comment by drcrazy** [comment]
Can you try without Sponge, please?

**Comment by bluelightning32** [comment]
Sorry, no, I can't try without Sponge at this point. None of the players admitted to what they did, and this crash has only happened once.

I run 4 servers linked together with InvSync, which requires Sponge. So if I removed Sponge, everyone would leave my server.

Can you catch the exception, log the location of the blast furnace, and rethrow the exception? That way I would at least know which player did it next time.

**Comment by drcrazy** [comment]
Only with your world save
