### ISSUE TITLE
Crash when remove cable

### ISSUE THREAD

**Issue by BlayzerQ** [TechReborn/TechReborn#1773]
TechReborn-1.12.2-2.24.1.1017-universal

java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at techreborn.tiles.cable.TileCableEU.removeConductor(TileCableEU.java:294)
	at ic2.core.energy.leg.EnergyCalculatorLeg.applyCableEffects(EnergyCalculatorLeg.java:663)
	at ic2.core.energy.leg.EnergyCalculatorLeg.runCalculation(EnergyCalculatorLeg.java:452)
	at ic2.core.energy.leg.EnergyCalculatorLeg.runSyncStep(EnergyCalculatorLeg.java:116)
	at ic2.core.energy.grid.GridUpdater.startTransferCalc(GridUpdater.java:75)
	at ic2.core.energy.grid.EnergyNetLocal.onTickStart(EnergyNetLocal.java:196)
	at ic2.core.energy.grid.EventHandler.onWorldTick(EventHandler.java:61)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_541_EventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:288)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:444)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:774)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@6b519c from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 18 more
Caused by: java.lang.RuntimeException: Attempted to load class bib for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 20 more

**Comment by coderbot16** [comment]
Appears to be caused by https://github.com/TechReborn/TechReborn/blob/1.12/src/main/java/techreborn/tiles/cable/TileCableEU.java#L290

The fix should just be replacing the `Minecraft.getMinecraft().world` with `this.world`.
