### ISSUE TITLE
Put lava bucket into Thermal Generator made my game clashes.

### ISSUE THREAD

**Issue by Chuwar** [TechReborn/TechReborn#1776]
- fabric-loader-0.4.8+build.159-1.14.4
- fabric-api-0.3.1+build.208
- RebornCore-1.14.4-4.0.7.122
- TechReborn-1.14.4-3.0.5.123

Description: Ticking block entity
java.lang.NullPointerException: Ticking block entity
	at techreborn.blockentity.generator.BaseFluidGeneratorBlockEntity.method_16896(BaseFluidGeneratorBlockEntity.java:93)
	at net.minecraft.class_1937.method_18471(class_1937.java:624)
	at net.minecraft.class_3218.method_18765(class_3218.java:405)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:835)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774)
	at net.minecraft.class_1132.method_3748(class_1132.java:161)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642)
	at java.lang.Thread.run(Unknown Source)

**Comment by modmuss50** [comment]
Fixed, https://github.com/TechReborn/TechReborn/commit/ff8b497c54eb55f9561f55911d6681d8629c4370

Thanks for reporting.
