### ISSUE TITLE
When with Tech Reborn GAme wont open and I didnt understand whats what. using 1.14.4. Fabric. and Latest Tech Reborn 

### ISSUE THREAD

**Issue by Ceyes00** [TechReborn/TechReborn#1798]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 19.08.2019 16:09
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: java.lang.ExceptionInInitializerError
		at techreborn.events.ModRegistry.registerBlocks(ModRegistry.java:91)
		at techreborn.events.ModRegistry.setupShit(ModRegistry.java:83)
		at techreborn.TechReborn.onInitialize(TechReborn.java:71)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointClient$$Lambda$1408/2073764942.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils$$Lambda$1409/1330702708.accept(Unknown Source)
		at java.util.ArrayList.forEach(ArrayList.java:1249)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 11 more
	Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: techreborn:bauxıte_ore
		at net.minecraft.class_2960.<init>(class_2960.java:38)
		at net.minecraft.class_2960.<init>(class_2960.java:47)
		at techreborn.utils.InitUtils.setup(InitUtils.java:45)
		at techreborn.init.TRContent$Ores.<init>(TRContent.java:330)
		at techreborn.init.TRContent$Ores.<clinit>(TRContent.java:299)
		... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1035213400 bytes (987 MB) / 1509949440 bytes (1440 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		blue_endless_jankson: jankson 1.1.0
		cloth: Cloth Events 0.4.0
		cloth-config2: Cloth Config v2 0.5.2
		com_typesafe_config: config 1.3.1
		fabric: Fabric API 0.3.1+build.208
		fabric-api-base: fabric-api-base 0.1.0+b494ebeb42
		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
		fabric-commands-v0: fabric-commands-v0 0.1.1+b494ebeb42
		fabric-containers-v0: fabric-containers-v0 0.1.2+b494ebeb42
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+b494ebeb42
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.1+9f55aa7042
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.1+9f55aa7042
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.1+eff46b3d42
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
		fabric-language-kotlin: Fabric Language Kotlin 1.3.40+build.1
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+b494ebeb42
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+ab421b9c42
		fabric-models-v0: fabric-models-v0 0.1.0+5914746342
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+b494ebeb42
		fabric-networking-v0: fabric-networking-v0 0.1.3+9f55aa7042
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9b03381f42
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+9b03381f42
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9b03381f42
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.10+f0fe03ff42
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+b494ebeb42
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.1+39442fc242
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.2+232e294c42
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+b494ebeb42
		fabric-textures-v0: fabric-textures-v0 0.1.4+b494ebeb42
		fabricloader: Fabric Loader 0.4.8+build.159
		itemscroller: Item Scroller 0.15.0-dev.20190720.190250
		malilib: MaLiLib 0.10.0-dev.20
		modmenu: Mod Menu 1.7.9+build.118
		org_jetbrains_annotations: annotations 16.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.40
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.40
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.40
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.2.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.2.2
		org_spongepowered_configurate-core: configurate-core 3.6
		org_spongepowered_configurate-hocon: configurate-hocon 3.6
		reborncore: Reborn Core 4.0.10.138
		roughlyenoughitems: Roughly Enough Items 2.9.8+build.150
		silk: Silk API 1.2.4-43
		techreborn: Tech Reborn 3.0.8.151
	Launched Version: fabric-loader-0.4.8+build.159-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

**Comment by modmuss50** [comment]
Humm, this is a very strage one.

**Comment by modmuss50** [comment]
Can you try with the latest released RC and TR?

**Comment by Ceyes00** [comment]
its still crashes even before opening (sorry for the incovenience)
heres the crash report:

Time: 20.08.2019 17:47
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: java.lang.ExceptionInInitializerError
		at techreborn.events.ModRegistry.registerBlocks(ModRegistry.java:91)
		at techreborn.events.ModRegistry.setupShit(ModRegistry.java:83)
		at techreborn.TechReborn.onInitialize(TechReborn.java:71)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointClient$$Lambda$1372/1910163007.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils$$Lambda$1373/300117596.accept(Unknown Source)
		at java.util.ArrayList.forEach(ArrayList.java:1249)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 11 more
	Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: techreborn:bauxıte_ore
		at net.minecraft.class_2960.<init>(class_2960.java:38)
		at net.minecraft.class_2960.<init>(class_2960.java:47)
		at techreborn.utils.InitUtils.setup(InitUtils.java:45)
		at techreborn.init.TRContent$Ores.<init>(TRContent.java:317)
		at techreborn.init.TRContent$Ores.<clinit>(TRContent.java:286)
		... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 976287360 bytes (931 MB) / 1644167168 bytes (1568 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		com_typesafe_config: config 1.3.1
		fabric: Fabric API 0.3.1+build.208
		fabric-api-base: fabric-api-base 0.1.0+b494ebeb42
		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
		fabric-commands-v0: fabric-commands-v0 0.1.1+b494ebeb42
		fabric-containers-v0: fabric-containers-v0 0.1.2+b494ebeb42
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+b494ebeb42
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.1+9f55aa7042
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.1+9f55aa7042
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.1+eff46b3d42
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+b494ebeb42
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+ab421b9c42
		fabric-models-v0: fabric-models-v0 0.1.0+5914746342
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+b494ebeb42
		fabric-networking-v0: fabric-networking-v0 0.1.3+9f55aa7042
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9b03381f42
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+9b03381f42
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9b03381f42
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.10+f0fe03ff42
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+b494ebeb42
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.1+39442fc242
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.2+232e294c42
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+b494ebeb42
		fabric-textures-v0: fabric-textures-v0 0.1.4+b494ebeb42
		fabricloader: Fabric Loader 0.4.8+build.159
		modmenu: Mod Menu 1.7.9+build.118
		org_spongepowered_configurate-core: configurate-core 3.6
		org_spongepowered_configurate-hocon: configurate-hocon 3.6
		reborncore: Reborn Core 4.0.11.140
		silk: Silk API 1.2.4-43
		techreborn: Tech Reborn 3.0.9.165
	Launched Version: fabric-loader-0.4.8+build.159-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

**Comment by Ceyes00** [comment]
Im really sorry for the inconvenience. And I must add this reborn core works fine but when tech reborn is installed it crashes

**Comment by modmuss50** [comment]
I think I have an idea of what the issue might be, I will look into it shortly

**Comment by modmuss50** [comment]
Ok, I have made a change that will hopefully fix the issue, can you please try the following builds:

[RebornCore-1.14.4-4.0.11.143.jar](https://jenkins.modmuss50.me/job/Team%20Reborn/job/RebornCore/job/1.14/143/artifact/build/libs/RebornCore-1.14.4-4.0.11.143.jar)

[TechReborn-1.14.4-3.0.9.174.jar](https://jenkins.modmuss50.me/job/Team%20Reborn/job/TechReborn/job/1.14/174/artifact/build/libs/TechReborn-1.14.4-3.0.9.174.jar)

Let me know how these 2 versions work for you, thanks.

**Comment by Ceyes00** [comment]
thank you very very much it works at last.

**Comment by modmuss50** [comment]
Great!, thanks for testing. This fix will be released with the next versions.
