### ISSUE TITLE
Game Crashes On start *fabric*

### ISSUE THREAD

**Issue by Aftathott** [TechReborn/TechReborn#1809]
Try to start the game with all my mods installed, including tech reborn and reborn core, game crashes with the below crash report, i also tried removing all my mods except tech reborn and reborn core and i get another crash on start, except this one says its an unexpected crash and doesnt give a report, i have this problem with the last version as well.

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 8/21/19 10:45 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors!
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:35)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/event/client/ItemTooltipCallback
		at java.lang.ClassLoader.defineClass1(Native Method)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
		at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at techreborn.TechRebornClient.onInitializeClient(TechRebornClient.java:113)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointClient$$Lambda$1786/1489152144.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils$$Lambda$1490/107733226.accept(Unknown Source)
		at java.util.ArrayList.forEach(ArrayList.java:1249)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 11 more
	Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.event.client.ItemTooltipCallback
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:160)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:35)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3417657120 bytes (3259 MB) / 4328521728 bytes (4128 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 1.0.7
		artifice: Artifice 0.3.3
		autoconfig1: Auto Config v1 1.2.0+mc1.14.4
		autofish: Autofish 0.8.4
		beachslimes: Beach Slimes 1.3.0+mc1.14.4
		blue_endless_jankson: jankson 1.1.2
		bluepower: BluePower 1.0.3
		cloth: Cloth Events 0.3.1+build.23
		cloth-config: Cloth Config 0.2.1+build.14
		cloth-config2: Cloth Config v2 0.2.0
		com_typesafe_config: config 1.3.1
		cursedchests: CursedChests 2.3.22
		disenchanting: Disenchanting 0.8.1
		durabilityviewer: Giselbaers Durability Viewer 1.14-fabric0.2.7-1.5
		easyexcavate: Easy Excavate 1.5.1
		fabric: Fabric API 0.3.0+build.200
		fabric-api-base: fabric-api-base 0.1.0+59147463
		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
		fabric-commands-v0: fabric-commands-v0 0.1.1+25fd0c5242
		fabric-containers-v0: fabric-containers-v0 0.1.2+25fd0c5242
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+05f11b7542
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+5914746342
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+ea100f6142
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+5914746342
		fabric-furnaces: Fabric Furnaces 1.1.7
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
		fabric-language-kotlin: Fabric Language Kotlin 1.3.40+build.1
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+43028fa642
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+ab421b9c42
		fabric-models-v0: fabric-models-v0 0.1.0+5914746342
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+25fd0c5242
		fabric-networking-v0: fabric-networking-v0 0.1.2+200eb5c2
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+592d1d2242
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+ea100f6142
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9486cfbf42
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.9+9486cfbf42
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+02a46d5b42
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c242
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+59147463
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+c189dc5c42
		fabric-textures-v0: fabric-textures-v0 0.1.4+792c1c3542
		fabricloader: Fabric Loader 0.4.8+build.159
		gbfabrictools: GBfabrictools 1.0.0
		glassdoor: Glass Doors 1.2.1
		harvest: Harvest 1.0.4
		instantlava: InstantLava 1.0.1
		jankson: Jankson 1.0.0+j1.1.2
		leaf-decay: Leaf Decay 1.0.3
		libblockattributes_core: LibBlockAttributes (Core) 0.4.9
		libblockattributes_items: LibBlockAttributes (Items) 0.4.9
		libcd: LibCapableData 1.2.1+1.14.3
		libgui: LibGui 1.2.5-b
		malilib: MaLiLib 0.10.0-dev.20
		mbackpacks: Mpcs' Backpacks 1.1.4
		mm: Manningham Mills 1.6
		modmenu: Mod Menu 1.6.3+build.101
		moreberries: More Berries 1.2.1
		net_fabricmc_stitch: stitch 0.2.1.61
		netherthings: Nether Things 1.1.2.1
		optifabric: Optifabric 0.4.3
		org_jetbrains_annotations: annotations 16.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.40
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.40
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.40
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.2.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.2.2
		org_slf4j_slf4j-api: slf4j-api 1.7.26
		org_slf4j_slf4j-simple: slf4j-simple 1.7.26
		org_spongepowered_configurate-core: configurate-core 3.6
		org_spongepowered_configurate-hocon: configurate-hocon 3.6
		org_zeroturnaround_zt-zip: zt-zip 1.13
		reborncore: Reborn Core 4.0.12.146
		roughlyenoughitems: Roughly Enough Items 2.9.7+build.142
		silk: Silk API 1.2.4-43
		simpleteleporters: Simple Teleporters 2.1.0
		sonyikaarftl: Advanced Rotten Flesh to Leather 1.4.4
		stockpile: Stockpile 1.0.9+1.14.4
		superores: Super Ores 2.0.1
		techreborn: Tech Reborn 3.0.10.184
		vanilla-hammers: Vanilla Hammers 1.4.2
		vanilladeathchest: VanillaDeathChest ${version}
		voxelmap: VoxelMap 1.9.13
		waila: Hwyla 1.9.17
	Launched Version: fabric-loader-0.4.8+build.159-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

**Comment by modmuss50** [comment]
Update fabric api.
