### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by thatguyontv** [TechReborn/TechReborn#1813]
Hi,

I get a crash whenever I start MC/Fabric 1.14.4 with TechReborn installed. RebornCore works fine. 

Crash message: The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors!

Crash Report:
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 24.08.19 15:02
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:187)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/event/client/ItemTooltipCallback
		at java.lang.ClassLoader.defineClass1(Native Method)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
		at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at techreborn.TechRebornClient.onInitializeClient(TechRebornClient.java:113)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$1898/2076240234.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils$$Lambda$1496/1495879465.accept(Unknown Source)
		at java.util.ArrayList.forEach(ArrayList.java:1249)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 11 more
	Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.event.client.ItemTooltipCallback
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:187)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7972998808 bytes (7603 MB) / 8522825728 bytes (8128 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		abusedlib: AbusedLib 1.3.0
		allthecreepers: All The Creepers v5.0.0+mc1.14.1
		amethystmod: Amethyst Mod 1.2.0
		appleskin: AppleSkin 1.0.7
		artifice: Artifice 0.3.4
		autoconfig1: Auto Config v1 1.2.0+mc1.14.4
		battle-towers: Battle Towers 1.1.2
		betterutilities: Better Utilities 1.4.2
		blockus: Blockus 1.2.0
		blue_endless_jankson: jankson 1.1.2
		cakechomps: Cake Chomps FABRIC-1.14.2-3.0
		cardinal-components-base: Cardinal Components API 2.0.1-SNAPSHOT
		cardinal-components-block: Cardinal Components API 2.0.1-SNAPSHOT
		cardinal-components-item: Cardinal Components API 2.0.1-SNAPSHOT
		cardinalenergy: Cardinal Energy 1.3.0
		chunkactivator: Chunk Activator 1.2.0+mc1.14.4
		cloth: Cloth Events 0.4.0
		cloth-config: Cloth Config 0.2.1+build.14
		cloth-config2: Cloth Config v2 1.0.0
		com_typesafe_config: config 1.3.1
		cotton-client-commands: Cotton Client Commands 0.4.2+1.14.3-SNAPSHOT
		couplings: Couplings 1.1.0
		crochet: Crochet 1.0.2
		crowmap: Crowmap 1.0.1
		cursedchests: CursedChests 2.3.24
		cutsceneapi: Cutscene API 1.0.0-beta5
		de_javagl_obj: obj 0.3.0
		ding: Ding 2.0.3
		durabilityviewer: Giselbaers Durability Viewer 1.14-fabric0.2.7-1.5
		dynagear: DynaGear 1.3.1+1.14.4
		enchantedtooltips: Enchanted ToolTips 1.1.0
		energies: Energies 1.14.4-1.0.14
		fabric: Fabric API 0.3.0+build.207
		fabric-api-base: fabric-api-base 0.1.0+59147463
		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
		fabric-commands-v0: fabric-commands-v0 0.1.1+b494ebeb42
		fabric-containers-v0: fabric-containers-v0 0.1.2+b494ebeb42
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+b494ebeb42
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+5914746342
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+ea100f6142
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+5914746342
		fabric-furnaces: Fabric Furnaces 1.1.7
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
		fabric-language-kotlin: Fabric Language Kotlin 1.3.40+build.1
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+b494ebeb42
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+ab421b9c42
		fabric-models-v0: fabric-models-v0 0.1.0+5914746342
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+b494ebeb42
		fabric-networking-v0: fabric-networking-v0 0.1.2+9b03381f42
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9b03381f42
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+9b03381f42
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9b03381f42
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.9+9b03381f42
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+b494ebeb42
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c242
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+59147463
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+b494ebeb42
		fabric-textures-v0: fabric-textures-v0 0.1.4+b494ebeb42
		fabricloader: Fabric Loader 0.4.9+build.160
		fiber2cloth: Fiber To Cloth 1.1.0
		firstperson: FirstpersonModel 1.0.1
		gbfabrictools: GBfabrictools 1.0.0
		glassential: Glassential 1.14.4-1.1.0
		harvest: Harvest 1.0.4
		informedload: Informed Load 2.1.0-1.14.4
		inventorysorter: Inventory Sorter 1.5.5
		jankson: Jankson 1.0.0+j1.1.2
		libblockattributes: LibBlockAttributes 0.4.9
		libblockattributes_core: LibBlockAttributes (Core) 0.4.9
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.4.9
		libblockattributes_items: LibBlockAttributes (Items) 0.4.9
		libcd: LibCapableData 1.3.2+1.14.4
		lightoverlay: Light Overlay 3.4
		mbackpacks: Mpcs' Backpacks 1.1.4
		me_zeroeightsix_fiber: fiber 0.6.0-7
		modmenu: Mod Menu 1.7.9+build.118
		moreberries: More Berries 1.2.1
		netherthings: Nether Things 1.1.3.1
		org_jetbrains_annotations: annotations 16.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.40
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.40
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.40
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.2.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.2.2
		org_spongepowered_configurate-core: configurate-core 3.6
		org_spongepowered_configurate-hocon: configurate-hocon 3.6
		protos: Protos 1.14.4-1.0.3
		reborncore: Reborn Core 4.0.12.146
		refinedmachinery: Refined Machinery 1.2.1
		roughlyenoughitems: Roughly Enough Items 3.0-pre+build.3
		silk: Silk API 1.2.4-43
		simple_pipes: SimplePipeTest 0.1.8
		stockpile: Stockpile 1.0.9+1.14.4
		superores: Super Ores 2.0.1
		techreborn: Tech Reborn 3.0.10.184
		terraform: Terraform 1.1.4+build.9
		traverse: Traverse 2.0.7+build.22
		trees-do-not-float: Trees Do Not Float 1.5.57+1.14.4
		vanilla-hammers: Vanilla Hammers 1.6.1
		vanilladeathchest: VanillaDeathChest ${version}
		variablepaxels: VariablePaxels 1.14.4-1.0.1
		voxelmap: VoxelMap 1.9.13
		waila: Hwyla 1.9.17
		wildworld: Wild World 1.1.2
	Launched Version: fabric-loader-0.4.9+build.160-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

**Comment by drcrazy** [comment]
Please, update Fabric API to recent version. You've got pretty ancient one )
