### ISSUE TITLE
Could not resolve valid mod collection (at: techreborn requires {fabric @ [*]})

### ISSUE THREAD

**Issue by raspopov** [TechReborn/TechReborn#1862]
Fabric Loader 0.6.3+build.167

```
Mods:

RebornCore-1.14.4-4.0.19+build.187
TechReborn-1.14.4-3.0.17+build.250

Using onesix launcher.

[10:56:32] [main/INFO]: Loading for game Minecraft 1.14.4`
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:159)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:122)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: techreborn requires {fabric @ [*]})
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:170)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:603)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:157)
	... 10 more
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:168)
	... 12 more
```

**Comment by ghost** [comment]
You need to install Fabric API: https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by raspopov** [comment]
Thank you! Please add notes about Fabric API to CurseForge's project page. And to dependencies.
