### ISSUE TITLE
TechReborn-1.15-3.3.0+build.158 will crash when play awhile online

### ISSUE THREAD

**Issue by jimahy7687** [TechReborn/TechReborn#2019]
**Describe the bug**
TechReborn-1.15-3.3.0+build.158 & 167 have the same problem
**Steps to Reproduce**
- First Step
- Second Step

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.1
 - Mod Loader: fabric , fabric-api-0.4.27+build.286-1.15

**Logs**
Time: 2020/1/29 上午 4:42
Description: Exception ticking world

java.lang.AbstractMethodError
	at net.minecraft.class_2647.method_11431(class_2647.java:20)
	at net.minecraft.class_2473.method_10507(class_2473.java:51)
	at net.minecraft.class_2473.method_9588(class_2473.java:42)
	at net.minecraft.class_2248.method_9514(class_2248.java:560)
	at net.minecraft.class_2680.method_11624(class_2680.java:267)
	at net.minecraft.class_3218.method_18203(class_3218.java:485)
	at net.minecraft.class_3215.method_20801(class_3215.java:406)
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1661)
	at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:105)
	at net.minecraft.class_3215.method_14161(class_3215.java:367)
	at net.minecraft.class_3215.a(class_3215.java:336)
	at net.minecraft.class_3218.method_18765(class_3218.java:324)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:847)
	at net.minecraft.class_3176.method_3813(class_3176.java:343)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:786)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:654)
	at java.lang.Thread.run(Unknown Source)

**Additional context**

**Comment by modmuss50** [comment]
Update to 1.15.2 please
