### ISSUE TITLE
When I into the auto crafting table will crash

### ISSUE THREAD

**Issue by jimahy7687** [TechReborn/TechReborn#2020]
**Describe the bug**
When I into the auto crafting table will crash some times, not always
It's have item in it.
It's happened in build 131,158,179
only 167 not crash when I open the ACT GUI

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.1
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
java.lang.NullPointerException: Rendering screen
	at de.siphalor.nbtcrafting.Core.hasClientMod(Core.java:79)
	at net.minecraft.class_1856.lambda$createStackArray$0(class_1856.java:562)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at net.minecraft.class_1856.handler$zia000$createStackArray(class_1856.java:562)
	at net.minecraft.class_1856.method_8096(class_1856.java)
	at net.minecraft.class_1856.method_8100(class_1856.java:77)
	at net.minecraft.class_1662$class_1663.<init>(class_1662.java:113)
	at net.minecraft.class_1662.method_7406(class_1662.java:70)
	at net.minecraft.class_1662.method_7402(class_1662.java:66)
	at net.minecraft.class_1867.method_17730(class_1867.java:66)
	at net.minecraft.class_1867.method_8115(class_1867.java:15)
	at net.minecraft.class_3956.method_17725(class_3956.java:29)
	at net.minecraft.class_1863.method_17718(class_1863.java:69)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.HashMap$ValueSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at net.minecraft.class_1863.method_8132(class_1863.java:69)
	at techreborn.blockentity.machine.tier1.AutoCraftingTableBlockEntity.getCurrentRecipe(AutoCraftingTableBlockEntity.java:93)
	at techreborn.client.gui.GuiAutoCrafting.method_2388(GuiAutoCrafting.java:60)
	at net.minecraft.class_465.render(class_465.java:123)
	at reborncore.client.gui.builder.GuiBase.render(GuiBase.java:258)
	at net.minecraft.class_757.method_3192(class_757.java:604)
	at net.minecraft.class_310.method_1523(class_310.java:947)
	at net.minecraft.class_310.method_1514(class_310.java:585)
	at net.minecraft.client.main.Main.main(Main.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

**Additional context**

**Comment by drcrazy** [comment]
I blame @Siphalor and NBT Crafting due to "de.siphalor.nbtcrafting.Core.hasClientMod(Core.java:79)"

Can you try without it, please?

**Comment by drcrazy** [comment]
Also, it looks like similar issue was fixed some time ago in NBT Crafting: https://github.com/Siphalor/nbt-crafting/issues/33
Fix might be release in this version: https://www.curseforge.com/minecraft/mc-mods/nbt-crafting/files/2863809

**Comment by CrossVas** [comment]
Update to the latest version of NBT Crafting

**Comment by Siphalor** [comment]
Thanks for the ping :/
@drcrazy

**Comment by drcrazy** [comment]
It looks like it is fixed by NBT Crafting
