### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by vancologne** [TechReborn/TechReborn#2032]
**Describe the bug**
downloaded mod, seemed to work fine untill i scrolled through all of the new items

**Steps to Reproduce**
-open minecraft
-run it
-start world
-scroll through creative inventory
-game crashes

**Environment (please complete the following information with the version):**
 - Minecraft :1.14.4
 - Mod Loader: fabric

-- Head --
Thread: Client thread
Stacktrace:
	at techreborn.client.render.BaseDynamicFluidBakedModel.lambda$emitItemQuads$0(BaseDynamicFluidBakedModel.java:83)
	at techreborn.client.render.BaseDynamicFluidBakedModel$$Lambda$4229/1354653840.transform(Unknown Source)
	at net.fabricmc.indigo.renderer.render.AbstractRenderContext.transform(AbstractRenderContext.java:40)
	at net.fabricmc.indigo.renderer.render.ItemRenderContext.renderQuad(ItemRenderContext.java:196)
	at net.fabricmc.indigo.renderer.render.ItemRenderContext.access$100(ItemRenderContext.java:55)
	at net.fabricmc.indigo.renderer.render.ItemRenderContext$Maker.emit(ItemRenderContext.java:136)
	at net.fabricmc.indigo.renderer.render.ItemRenderContext$Maker.emit(ItemRenderContext.java:126)
	at techreborn.client.render.BaseDynamicFluidBakedModel.lambda$emitItemQuads$1(BaseDynamicFluidBakedModel.java:91)
	at techreborn.client.render.BaseDynamicFluidBakedModel$$Lambda$4230/1592368889.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at techreborn.client.render.BaseDynamicFluidBakedModel.emitItemQuads(BaseDynamicFluidBakedModel.java:89)
	at techreborn.client.render.DynamicCellBakedModel.emitItemQuads(DynamicCellBakedModel.java:48)
	at net.fabricmc.indigo.renderer.render.ItemRenderContext.renderModel(ItemRenderContext.java:111)
	at net.minecraft.class_918.handler$zbi000$hookRenderModel(class_918.java:1057)
	at net.minecraft.class_918.method_4027(class_918.java)
	at net.minecraft.class_918.method_4018(class_918.java:104)
	at net.minecraft.class_918.method_4006(class_918.java:194)
	at net.minecraft.class_918.method_4021(class_918.java:519)

-- Item being rendered --
Details:
	Item Type: cell
	Registry Name: null
	Item Damage: 0
	Item NBT: {fluid:"minecraft:water"}
	Item Foil: false

LOVE the mod so far though! takes me back to when i used to play the technic modpacks as a little one :) thanks!!

**Comment by modmuss50** [comment]
Sadly 1.14.4 is no longer supported, I urge you to update to 1.15.2. Sorry about that
