### ISSUE TITLE
Crashed sometimes using a dispenser to fill empty cell with water

### ISSUE THREAD

**Issue by Gardelll** [TechReborn/TechReborn#2097]
Crashed when using a dispenser to fill empty cell with water

Place a dispenser near the water source like this, then fill the dispenser with empty cell, power the dispenser, the game will crash.
![crash](https://user-images.githubusercontent.com/19503016/80171581-5a935500-861d-11ea-9764-b355a0ca6e21.png)

but this will work properly.
![not crash](https://user-images.githubusercontent.com/19503016/80171697-9f1ef080-861d-11ea-878a-451c59cf3efc.png)

(sorry for my English)

Here is the crash report
```
---- Minecraft Crash Report ----
// Sorry :(

Time: 4/24/20, 10:13 AM
Description: Exception while ticking

java.lang.StackOverflowError: Exception while ticking
	at java.base/java.util.Spliterator.getExactSizeIfKnown(Spliterator.java:408)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:501)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.IntPipeline.allMatch(IntPipeline.java:518)
	at net.minecraft.class_2960.method_20209(class_2960.java:158)
	at net.minecraft.class_2960.<init>(class_2960.java:34)
	at net.minecraft.class_2960.<init>(class_2960.java:43)
	at techreborn.items.DynamicCellItem.getFluid(DynamicCellItem.java:237)
	at techreborn.items.DynamicCellItem.placeFluid(DynamicCellItem.java:107)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:78)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	..........very long
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.base/java.util.Spliterator.getExactSizeIfKnown(Spliterator.java:408)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:501)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.IntPipeline.allMatch(IntPipeline.java:518)
	at net.minecraft.class_2960.method_20209(class_2960.java:158)
	at net.minecraft.class_2960.<init>(class_2960.java:34)
	at net.minecraft.class_2960.<init>(class_2960.java:43)
	at techreborn.items.DynamicCellItem.getFluid(DynamicCellItem.java:237)
	at techreborn.items.DynamicCellItem.placeFluid(DynamicCellItem.java:107)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:78)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	.
	.
	.
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at techreborn.init.TRDispenserBehavior$2.method_10135(TRDispenserBehavior.java:90)
	at net.minecraft.class_2347.dispense(class_2347.java:15)

-- Block being ticked --
Details:
	Block location: World: (55,74,62), Chunk: (at 7,4,14 in 3,3; contains blocks 48,0,48 to 63,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.class_1949.method_8670(class_1949.java:87)
	at net.minecraft.class_3218.method_18765(class_3218.java:337)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:852)
	at net.minecraft.class_3176.method_3813(class_3176.java:350)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:791)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:650)
	at java.base/java.lang.Thread.run(Thread.java:834)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 2025
	Level dimension: minecraft:overworld
	Level name: world
	Level seed: 6763092692731856838
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: NBT[{}]
	Level spawn location: World: (48,70,48), Chunk: (at 0,4,0 in 3,3; contains blocks 48,0,48 to 63,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 17778930 game time, 19518943 day time
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 113537 (now: false), thunder time: 95069 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- System Details --
Details:
	Minecraft Version: 20w16a
	Minecraft Version ID: 20w16a
	Operating System: Linux (amd64) version 4.15.0-91-generic
	Java Version: 11.0.6, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 746586112 bytes (712 MB) / 1213202432 bytes (1157 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 2
	JVM Flags: 1 total; -Xmx3G
	Fabric Mods: 
		autoconfig1: Auto Config v1 1.2.0+mc1.14.4
		fabric: Fabric API 0.5.11+build.322-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cad
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.1+b7d52fa5ad
		fabric-commands-v0: Fabric Commands (v0) 0.1.4+a2a96bf9ad
		fabric-containers-v0: Fabric Containers (v0) 0.1.7+d249f7b6ad
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.5+88afe607ad
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825dad
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.3+a2a96bf9ad
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+04b99794ad
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+1a47cd78ad
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.10+d249f7b6ad
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.6+2f56dff2ad
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+5b8a535aad
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7bad
		fabric-networking-v0: Fabric Networking (v0) 0.1.9+1a47cd78ad
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.2.4+eb276f9cad
		fabric-particles-v1: fabric-particles-v1 0.1.2+12a8474cad
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.10+eb276f9cad
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825dad
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.13+94c7834aad
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.3+9cd8d660ad
		fabricloader: Fabric Loader 0.8.2+build.194
		fabricproxy: FabricProxy 1.3.2
		minecraft: Minecraft 1.16-alpha.20.16.a
		reborncore: Reborn Core 4.2.7+build.13
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.3.9+build.17
		terraform: Terraform 1.6.1+build.8
		traverse: Traverse 2.2.2+build.5
	Player Count: 0 / 5; []
	Data Packs: vanilla, fabric/fabric-mining-levels-v0, fabric/techreborn (incompatible), fabric/traverse
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by modmuss50** [comment]
Nice find :D should be fixed in the next version
