### ISSUE TITLE
Crash when configuring sides on latest snapshot

### ISSUE THREAD

**Issue by Mizhok** [TechReborn/TechReborn#2108]
```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 5/10/20 10:37 AM
Description: Rendering screen

java.lang.IllegalAccessError: tried to access method net.minecraft.class_918.method_4026(Lnet/minecraft/class_1309;Lnet/minecraft/class_1799;II)V from class reborncore.client.gui.builder.slot.elements.ConfigSlotElement
	at reborncore.client.gui.builder.slot.elements.ConfigSlotElement.draw(ConfigSlotElement.java:118)
	at reborncore.client.gui.builder.slot.SlotConfigGui.draw(SlotConfigGui.java:91)
	at reborncore.client.gui.builder.slot.GuiTab.draw(GuiTab.java:67)
	at reborncore.client.gui.builder.GuiBase.lambda$drawForeground$11(GuiBase.java:255)
	at java.util.Optional.ifPresent(Unknown Source)
	at reborncore.client.gui.builder.GuiBase.method_2388(GuiBase.java:255)
	at techreborn.blockentity.data.DataDrivenGui.method_2388(DataDrivenGui.java:55)
	at net.minecraft.class_465.method_25394(class_465.java:124)
	at reborncore.client.gui.builder.GuiBase.method_25394(GuiBase.java:260)
	at net.minecraft.class_757.method_3192(class_757.java:604)
	at net.minecraft.class_310.method_1523(class_310.java:1007)
	at net.minecraft.class_310.method_1514(class_310.java:630)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at reborncore.client.gui.builder.slot.elements.ConfigSlotElement.draw(ConfigSlotElement.java:118)
	at reborncore.client.gui.builder.slot.SlotConfigGui.draw(SlotConfigGui.java:91)
	at reborncore.client.gui.builder.slot.GuiTab.draw(GuiTab.java:67)
	at reborncore.client.gui.builder.GuiBase.lambda$drawForeground$11(GuiBase.java:255)
	at java.util.Optional.ifPresent(Unknown Source)
	at reborncore.client.gui.builder.GuiBase.method_2388(GuiBase.java:255)
	at techreborn.blockentity.data.DataDrivenGui.method_2388(DataDrivenGui.java:55)
	at net.minecraft.class_465.method_25394(class_465.java:124)
	at reborncore.client.gui.builder.GuiBase.method_25394(GuiBase.java:260)

-- Screen render details --
Details:
	Screen name: techreborn.blockentity.data.DataDrivenGui
	Mouse location: Scaled: (347, 146). Absolute: (1041.000000, 439.000000)
	Screen size: Scaled: (640, 353). Absolute: (1920, 1057). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['Mizhok'/75, l='ClientLevel', x=-116.41, y=88.00, z=-282.89]]
	Chunk stats: Client Chunks (ImmPtl) 169
	Level dimension: minecraft:overworld
	Level seed: 9040927431377053917
	Level generator options: NBT[{}]
	Level spawn location: World: (32,83,-144), Chunk: (at 0,5,0 in 2,-9; contains blocks 32,0,-144 to 47,255,-129), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 90102 game time, 90102 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:435)
	at net.minecraft.class_310.method_1587(class_310.java:1980)
	at net.minecraft.class_310.method_1514(class_310.java:648)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 20w19a
	Minecraft Version ID: 20w19a
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 183913440 bytes (175 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.0.1-unstable
		autoharvest: autoharvest 1.0.4
		biow0rks: biow0rk5 0.4.4-1.16
		cavebiomes: Cave Biomes 0.2.1
		cloth: Cloth Events 2.2.0-unstable
		cloth-basic-math: Cloth Basic Math 0.5.0
		cloth-config2: Cloth Config v2 4.1.0-unstable
		conveyance: Conveyance 0.4.1+20w19a
		fabric: Fabric API 0.10.7+build.344-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cd2
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.2+2fd224cad2
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea89d2
		fabric-command-api-v1: Fabric Command API (v1) 1.0.2+fbdec548d2
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d30836d2
		fabric-containers-v0: Fabric Containers (v0) 0.1.7+d249f7b6d2
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.5+88afe607d2
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825dd2
		fabric-dimensions-v1: fabric-dimensions-v1 0.4.1+686e6e57d2
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+04b99794d2
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+1a47cd78d2
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.12+63435d4bd2
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d6d2
		fabric-language-kotlin: Fabric Language Kotlin 1.3.61+build.1
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.6+2f56dff2d2
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce99d2
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d6d2
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7bd2
		fabric-networking-v0: Fabric Networking (v0) 0.1.9+1a47cd78d2
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.2.0+57dbcc4cd2
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.5.1+57dbcc4cd2
		fabric-particles-v1: fabric-particles-v1 0.1.2+12a8474cd2
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.2+d1e1b46cd2
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb8d2
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.29+6c0e72dfd2
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a60d2
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825dd2
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.7+12a8474cd2
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+53410490d2
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.0+304e48ebd2
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.14+2fd224cad2
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.4+2fd224cad2
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb8d2
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.0.4+fa840743d2
		fabricloader: Fabric Loader 0.8.2+build.194
		fabricshieldlib: Fabric Shield Lib 1.0.3
		fermion: Fermion 1.14.165
		fermion-modkeys: Fermion Modifier Keys 1.5.157
		immersive_portals: Immersive Portals 0.10
		jankson: Jankson 2.0.0+j1.2.0
		lavafishing: Lava Fishing 1.0.3
		llamasteeds: Llama Steeds 2020.2.8
		minecraft: Minecraft 1.16-alpha.20.19.a
		mixedslab: Mixed Slab 20w17a-fabric-0.3.0.0
		modmenu: Mod Menu 1.11.4+build.9
		moenchantments: Mo'Enchantments 1.11.0
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.61
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.61
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.61
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.61
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.3
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.3
		pleasant_rotation: Pleasant Rotation 1.0.0-1.16
		reborncore: Reborn Core 4.2.9+build.20
		resourceful_tools: Resourceful Tools 1.0.4
		roughlyenoughitems: Roughly Enough Items 4.3.1-unstable
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.3.11+build.25
		tinyconfig: TinyConfig 1.1.2
		wrenchable: Wrenchable 0.3.1+20w19a
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) Vega 8 Graphics GL version 4.6.13572 Compatibility Profile Context 19.11.3 26.20.13031.18002, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx 
#@!@# Game crashed! Crash report saved to: #@!@# C:\Bullshit Programs\MultiMC\instances\Mizhoks Cool Snappack\.minecraft\crash-reports\crash-2020-05-10_10.37.30-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.

```

**Comment by modmuss50** [comment]
For now TR is for 18a, I dont have the time to keep it updated each week. I will get around to fixing this sometime in the next week or two tbh.

**Comment by LukeNotDuke** [comment]
I got a crash too , but when pick blocking an ore block from the mod 
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 6/15/20 2:12 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.class_327.method_27528(Lnet/minecraft/class_4587;Lnet/minecraft/class_2561;FFI)I
	at reborncore.client.hud.StackInfoHUD.addInfo(StackInfoHUD.java:147)
	at reborncore.client.hud.StackInfoHUD.drawStackInfoHud(StackInfoHUD.java:88)
	at reborncore.client.hud.StackInfoHUD.onHudRender(StackInfoHUD.java:184)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$null$0(HudRenderCallback.java:27)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback$$Lambda$2580/955901595.onHudRender(Unknown Source)
	at net.minecraft.class_329.handler$zed000$render(class_329.java:1321)
	at net.minecraft.class_329.method_1753(class_329.java:374)
	at net.minecraft.class_757.method_3192(class_757.java:584)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at reborncore.client.hud.StackInfoHUD.addInfo(StackInfoHUD.java:147)
	at reborncore.client.hud.StackInfoHUD.drawStackInfoHud(StackInfoHUD.java:88)
	at reborncore.client.hud.StackInfoHUD.onHudRender(StackInfoHUD.java:184)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$null$0(HudRenderCallback.java:27)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback$$Lambda$2580/955901595.onHudRender(Unknown Source)
	at net.minecraft.class_329.handler$zed000$render(class_329.java:1321)
	at net.minecraft.class_329.method_1753(class_329.java:374)

-- Affected level --
Details:
	All players: 1 total; [class_746['JilterSmelter'/243, l='ClientLevel', x=10009.53, y=59.00, z=10006.33]]
	Chunk stats: Client Chunk Cache: 441, 393
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,63,32), Chunk: (at 0,3,0 in 1,2; contains blocks 16,0,32 to 31,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2368 game time, 2368 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2176)
	at net.minecraft.class_310.method_1514(class_310.java:677)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16 Pre-release 5
	Minecraft Version ID: 1.16-pre5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 945804328 bytes (901 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 1.0.10
		fabric: Fabric API 0.12.1+build.361-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c2f
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea8662f
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea892f
		fabric-command-api-v1: Fabric Command API (v1) 1.0.6+4e84b64f2f
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308362f
		fabric-containers-v0: Fabric Containers (v0) 0.1.7+d249f7b62f
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8662f
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d2f
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b30532f
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f2f
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.3+0d474ec42f
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96362f
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a97742f
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c52f
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea8662f
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce992f
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d62f
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b2f
		fabric-networking-v0: Fabric Networking (v0) 0.1.9+1a47cd782f
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.4+059ea8662f
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad62f
		fabric-particles-v1: fabric-particles-v1 0.1.3+4a08d6b22f
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c2f
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb82f
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.1+059ea8662f
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a602f
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d2f
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.7+12a8474c2f
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104902f
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d72f
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.5+059ea8662f
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.5+5a6e8f4c2f
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb82f
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.3+059ea8662f
		fabricloader: Fabric Loader 0.8.7+build.201
		minecraft: Minecraft 1.16-rc.5
		reborncore: Reborn Core 4.2.10+build.22
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.3.12+build.30
	Launched Version: fabric-loader-0.8.7+build.201-1.16-pre5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon (TM) R5 M330 GL version 4.6.13596 Compatibility Profile Context 20.5.1 27.20.1017.1011, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz

**Comment by jusvit** [comment]
Closing due to inactivity, if issue still persists, reopen.
