### ISSUE TITLE
[Suggestion]Use inputstack instead of output stack in MT machine recipe removal

### ISSUE THREAD

**Issue by wormzjl** [TechReborn/TechReborn#219]
centrifuge, electrolyzer...etc
This allows better control of recipes and can prevent accidental removal of other recipes.
And this is pretty much a standard for MT integrations in other mods.

**Comment by wormzjl** [comment]
While testing with the latest version I still find it impossible to remove recipes with inputstack
However output stack still works?

**Comment by modmuss50** [comment]
ok, thanks for that, I will take a look into it

**Comment by modmuss50** [comment]
That should do it

**Comment by wormzjl** [comment]
Umm it seems that it's still broken
I was testing with this
mods.techreborn.blastFurnace.removeRecipe(<techreborn:dust:81>);
mods.techreborn.blastFurnace.removeRecipe(<techreborn:smallDust:82>);

**Comment by modmuss50** [comment]
ok thanks for the script, I will have a look into it

**Comment by modmuss50** [comment]
What was the main issue with the old way?? it worked fine right??

**Comment by modmuss50** [comment]
Im thinking of reverting it because I dont want to break existing scripts

**Comment by wormzjl** [comment]
Using output stack will sometimes remove a bunch of recipes while unintended, and it's difficult to find stuff that are not present in all other recipes, it's just easier to control via inputstack

**Comment by wormzjl** [comment]
Sometime I just don't know what I could remove accidentally

**Comment by modmuss50** [comment]
Oh you want to check the input slots, not the output ones??

**Comment by wormzjl** [comment]
Ummm yeah

**Comment by modmuss50** [comment]
ahh, I was confused

**Comment by wormzjl** [comment]
Sry for that :3

**Comment by modmuss50** [comment]
I think Im going to rewrite the MT support to be easier to maintain.

**Comment by wormzjl** [comment]
I guess that this is not completed yet?
While using my old script I got this:
ERROR: tic.zs:22 > a method available but none matches the parameters (minetweaker.item.IItemStack)
This is for removing the aluminium brass ingot recipe from the alloy furnance

**Comment by modmuss50** [comment]
Every machine now has removeInputRecipe as well as removeRecipe

**Comment by wormzjl** [comment]
ok thx

**Comment by wormzjl** [comment]
Seems to be bugged still
Using the following expression
mods.techreborn.alloySmelter.removeInputRecipe(<techreborn:ingot:0>);
I got this in the MT log
ERROR: Error executing tic.zs: null
java.lang.NullPointerException
	at techreborn.compat.minetweaker.MTGeneric.removeInputRecipe(MTGeneric.java:36)
	at Tic.__script__(tic.zs:22)
	at __ZenMain__.run(tic.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:163)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:656)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:83)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:642)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by modmuss50** [comment]
That should fix it ^^^
