### ISSUE TITLE
"ClassCastException: BlockItem cannot be cast to ItemFluidInfo" ticking Industrial Grinder after mod update

### ISSUE THREAD

**Issue by copygirl** [TechReborn/TechReborn#2261]
After updating from Tech Reborn `3.5.4` to `3.6.0`, I crashed the server as soon I got close to my friend's base, and it keeps crashing when I attempt to log in.

```
java.lang.ClassCastException: net.minecraft.class_1747 cannot be cast to reborncore.common.fluid.container.ItemFluidInfo
    at techreborn.utils.FluidUtils.drainContainers(FluidUtils.java:71)
    at techreborn.utils.FluidUtils.drainContainers(FluidUtils.java:59)
    at techreborn.blockentity.machine.multiblock.IndustrialGrinderBlockEntity.method_16896(IndustrialGrinderBlockEntity.java:86)
    at net.minecraft.class_1937.method_18471(class_1937.java:510)
    at net.minecraft.class_3218.method_18765(class_3218.java:424)
    at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:868)
    at net.minecraft.class_3176.method_3813(class_3176.java:303)
    at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:808)
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by copygirl** [comment]
I presume this is due to [this check being removed](https://github.com/TechReborn/TechReborn/commit/75e7e626f9831073aebce9df6efb117e1dd4b691#diff-5db38411fe6cddc719d1d7315cad5763abfb4a96e50e02bbbbde19bfccb78ba4L66) in 75e7e626f9831073aebce9df6efb117e1dd4b691.

**Comment by modmuss50** [comment]
Looks like it yes, ill try and get a hot fix out soon.

**Comment by drcrazy** [comment]
Sorry, I haven't tested case when you put not a fluid container into input slot.
