### ISSUE TITLE
ArithmeticException when open Compressor GUI

### ISSUE THREAD

**Issue by L2jLiga** [TechReborn/TechReborn#2330]
**Describe the bug**

**Steps to Reproduce**
- ??? floating
- Open compressor GUI

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.4
 - Mod Loader: [e.g. forge, fabric]

**Logs**

<details> <summary>Stacktrace</summary>

```
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:625) ~[intermediary-fabric-loader-0.11.1-1.16.4.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1048) ~[intermediary-fabric-loader-0.11.1-1.16.4.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-fabric-loader-0.11.1-1.16.4.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.11.1-1.16.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
Caused by: java.lang.ArithmeticException: / by zero
	at techreborn.blockentity.machine.GenericMachineBlockEntity.getProgressScaled(GenericMachineBlockEntity.java:78) ~[TechReborn-1.16-3.7.3+build.192.jar:?]
	at techreborn.client.gui.GuiCompressor.method_2388(GuiCompressor.java:61) ~[TechReborn-1.16-3.7.3+build.192.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java:142) ~[intermediary-fabric-loader-0.11.1-1.16.4.jar:?]
	at reborncore.client.gui.builder.GuiBase.method_25394(GuiBase.java:260) ~[RebornCore-1.16-4.6.3+build.110.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:616) ~[intermediary-fabric-loader-0.11.1-1.16.4.jar:?]
	... 10 more
---- Minecraft Crash Report ----
// There are four lights!

Time: 26.01.21 16:17
Description: Rendering screen

java.lang.ArithmeticException: / by zero
	at techreborn.blockentity.machine.GenericMachineBlockEntity.getProgressScaled(GenericMachineBlockEntity.java:78)
	at techreborn.client.gui.GuiCompressor.method_2388(GuiCompressor.java:61)
	at net.minecraft.class_465.method_25394(class_465.java:142)
	at reborncore.client.gui.builder.GuiBase.method_25394(GuiBase.java:260)
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at techreborn.blockentity.machine.GenericMachineBlockEntity.getProgressScaled(GenericMachineBlockEntity.java:78)
	at techreborn.client.gui.GuiCompressor.method_2388(GuiCompressor.java:61)
	at net.minecraft.class_465.method_25394(class_465.java:142)
	at reborncore.client.gui.builder.GuiBase.method_25394(GuiBase.java:260)

-- Screen render details --
Details:
	Screen name: techreborn.client.gui.GuiCompressor
	Mouse location: Scaled: (292, 202). Absolute: (877.000000, 606.000000)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 2 total; [class_746['Pray'/4399, l='ClientLevel', x=-250.98, y=68.00, z=-1653.30], class_745['Dila'/18308, l='ClientLevel', x=-250.37, y=68.00, z=-1653.37]]
	Chunk stats: SodiumChunkCache: 361
	Level dimension: minecraft:overworld
	Level spawn location: World: (-261,73,-1641), Chunk: (at 11,4,7 in -17,-103; contains blocks -272,0,-1648 to -257,255,-1633), Region: (-1,-4; contains chunks -32,-128 to -1,-97, blocks -512,0,-2048 to -1,255,-1537)
	Level time: 276154 game time, 267961 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
```

</details>

**Comment by L2jLiga** [comment]
I guess it fixed in https://github.com/TechReborn/TechReborn/commit/ea0db38b6aaa5a537f65d4d6cd6219228b178580
