### ISSUE TITLE
Using Drill on some blocks result in crash

### ISSUE THREAD

**Issue by Ramzyu** [TechReborn/TechReborn#2348]
Using the drill on dirt causes a the game to crash.

Thought it was conflicting with my mods from Orgins classes with the mining class has slightly faster mining (but changing class didn't do anything)
but while in LAN my friend could use it fine. But when I touch dirt, sand and gravel with it causes a crash.
everything is up to date as far as i'm aware

 - Minecraft: 1.16.5
 - Mod Loader: Fabric

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 16/02/21 10:19 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.class_1766.redirect$zkc000$applyMiningSpeedMultiplierMultiplier(class_1766.java:519)
	at net.minecraft.class_1766.method_7865(class_1766.java:38)
	at techreborn.items.tool.DrillItem.method_7856(DrillItem.java:92)
	at techreborn.items.tool.DrillItem.method_7865(DrillItem.java:72)
	at net.minecraft.class_1799.method_7924(class_1799.java:235)
	at net.minecraft.class_1661.method_7370(class_1661.java:421)
	at net.minecraft.class_1657.method_7351(class_1657.java:756)
	at net.minecraft.class_4970.method_9594(class_4970.java:352)
	at net.minecraft.class_4970$class_4971.method_26165(class_4970.java:751)
	at net.minecraft.class_636.method_2910(class_636.java:164)
	at net.optifine.override.PlayerControllerOF.method_2910(PlayerControllerOF.java:50)
	at net.minecraft.class_310.method_1536(class_310.java:1396)
	at net.minecraft.class_310.method_1508(class_310.java:1706)
	at net.minecraft.class_310.method_1574(class_310.java:1534)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1766.redirect$zkc000$applyMiningSpeedMultiplierMultiplier(class_1766.java:519)
	at net.minecraft.class_1766.method_7865(class_1766.java:38)
	at techreborn.items.tool.DrillItem.method_7856(DrillItem.java:92)
	at techreborn.items.tool.DrillItem.method_7865(DrillItem.java:72)
	at net.minecraft.class_1799.method_7924(class_1799.java:235)
	at net.minecraft.class_1661.method_7370(class_1661.java:421)
	at net.minecraft.class_1657.method_7351(class_1657.java:756)
	at net.minecraft.class_4970.method_9594(class_4970.java:352)
	at net.minecraft.class_4970$class_4971.method_26165(class_4970.java:751)
	at net.minecraft.class_636.method_2910(class_636.java:164)
	at net.optifine.override.PlayerControllerOF.method_2910(PlayerControllerOF.java:50)
	at net.minecraft.class_310.method_1536(class_310.java:1396)
	at net.minecraft.class_310.method_1508(class_310.java:1706)

-- Affected level --
Details:
	All players: 1 total; [class_746['Ramzokillzo'/169, l='ClientLevel', x=-1239.59, y=12.00, z=193.14]]
	Chunk stats: Client Chunk Cache: 441, 240
	Level dimension: minecraft:overworld
	Level spawn location: World: (-256,85,80), Chunk: (at 0,5,0 in -16,5; contains blocks -256,0,80 to -241,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2109078 game time, 2550371 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:617)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 888342112 bytes (847 MB) / 2080374784 bytes (1984 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.3.1
		blue_endless_jankson: jankson 1.2.0
		cardinal-components-base: Cardinal Components API (base) 2.7.1
		cardinal-components-entity: Cardinal Components API (entities) 2.7.1
		chainmail: Chainmail 0.5.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.10.9
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		croptopia: Croptopia 1.2.0
		expandedstorage: ExpandedStorage 5.6.32
		fabric: Fabric API 0.30.0+1.16
		fabric-api-base: Fabric API Base 0.2.0+daa38b3d7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+ca58154a7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		fallflyinglib: FallFlyingLib 1.1.0
		fallingtree: FallingTree 2.10.1
		go-fish: Go Fish 1.2.1-beta-1.16.4
		inmis: Inmis 2.1.1-1.16.4
		inventorysorter: Inventory Sorter 1.7.6-1.16
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kyrptconfig: Kytpt Config 1.1.6-1.16
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 1.16.7
		optifabric: OptiFabric 1.9.2
		origins: Origins 0.4.6
		origins-classes: Origins: Classes 1.1.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.6.4+build.117
		roughlyenoughitems: Roughly Enough Items 5.10.178
		roughlyenoughitems-api: REI (API) 5.10.178
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.10.178
		roughlyenoughitems-runtime: REI (Runtime) 5.10.178
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.7.3+build.192
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		voxelmap: VoxelMap 1.10.15
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
	Launched Version: fabric-loader-0.11.1-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.40, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	OptiFine Version: OptiFine_1.16.5_HD_U_G6
	OptiFine Build: 20210117-013236
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.2.01pre2.zip
	OpenGlVersion: 4.6.0 NVIDIA 461.40
	OpenGlRenderer: GeForce RTX 2070 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.5
	OptiFine jar version: OptiFine_1.16.5_HD_U_G6
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:\Users\L0LKa\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G6\Optifine-mapped.jar
	OptiFabric error: <None>

Its probably cause of Orgins but its too fun to get rid off, but want the drills too.

**Comment by jusvit** [comment]
I think this is fixed, can you update to 3.8.0 (https://www.curseforge.com/minecraft/mc-mods/techreborn/files/3204155) and report if the issue persists.

**Comment by Ramzyu** [comment]
I updated the tech and the core mod, it loaded fine but same thing happens, crashed as I touch dirt or the like with the drill.

Added a text file, not sure if its attached as this is my first time using github. 

[crash-2021-02-17_05.12.11-client.txt](https://github.com/TechReborn/TechReborn/files/5995856/crash-2021-02-17_05.12.11-client.txt)

**Comment by scarekraken** [comment]
Having the exact same problem, after click on dirt, sand or gravel with the Basic Drill. I have not tested the same bug with other drills.

[peepopog.txt](https://github.com/TechReborn/TechReborn/files/6002325/peepopog.txt)
