### ISSUE TITLE
Crash - When looking into inventory containing Energy Crystal

### ISSUE THREAD

**Issue by DestroyFX** [TechReborn/TechReborn#2591]
When I look in the assembler to grab my freshly made energy crystals, The client crash.

This is not related to the other bug with Megane. (I did add Megane mod **after** to see if it would change something)

[01/11/2021 17:54:31 PM] [17:54:31] [Render thread/INFO]: [STDOUT]: Minimap session finalized.
[01/11/2021 17:54:31 PM] [17:54:31] [Render thread/INFO]: [STDOUT]: Finalizing world map session...
[01/11/2021 17:54:31 PM] [17:54:31] [Netty Epoll Client IO #0/INFO]: Left dedicated server, restoring config.
[01/11/2021 17:54:32 PM] [17:54:32] [Thread-4/INFO]: [STDOUT]: World map force-cleaned!
[01/11/2021 17:54:32 PM] [17:54:32] [Render thread/INFO]: [STDOUT]: World map session finalized.
[01/11/2021 17:54:32 PM] [17:54:32] [Render thread/INFO]: Stopping worker threads
[01/11/2021 17:54:32 PM] [17:54:32] [Render thread/INFO]: Destroying pipeline OVERWORLD
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/FATAL]: Reported exception thrown!
[01/11/2021 17:54:33 PM] net.minecraft.class_148: Rendering screen
[01/11/2021 17:54:33 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.62) ~[?:?]
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.render.GameRenderer.render(GameRenderer:883) ~[?:?]
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112) ~[?:?]
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.main.Main.main(Main:217) [intermediary-client-1.17.1.jar:?]
[01/11/2021 17:54:33 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[01/11/2021 17:54:33 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
[01/11/2021 17:54:33 PM] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[01/11/2021 17:54:33 PM] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
[01/11/2021 17:54:33 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-loader-0.12.2.jar:?]
[01/11/2021 17:54:33 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.12.2.jar:?]
[01/11/2021 17:54:33 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.2.jar:?]
[01/11/2021 17:54:33 PM] Caused by: java.lang.IllegalArgumentException: Invalid count: 4
[01/11/2021 17:54:33 PM] 	at team.reborn.energy.api.base.SimpleBatteryItem.getStoredEnergy(SimpleBatteryItem.java:55) ~[team_reborn_energy-2.0.0-beta1-a90c99d8af2f3ca2.jar:?]
[01/11/2021 17:54:33 PM] 	at reborncore.common.util.ItemUtils.getPowerForDurabilityBar(ItemUtils.java:116) ~[RebornCore-5.0.9-beta+build.131.jar:?]
[01/11/2021 17:54:33 PM] 	at techreborn.items.BatteryItem.getDurability(BatteryItem.java:117) ~[TechReborn-5.0.9-beta+build.131.jar:?]
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.render.item.ItemRenderer.handler$fam000$renderGuiItemOverlay(ItemRenderer:5062) ~[?:?]
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.render.item.ItemRenderer.renderGuiItemOverlay(ItemRenderer) ~[?:?]
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.gui.screen.ingame.HandledScreen.drawSlot(HandledScreen:266) ~[?:?]
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen:123) ~[?:?]
[01/11/2021 17:54:33 PM] 	at reborncore.client.gui.builder.GuiBase.render(GuiBase.java:261) ~[RebornCore-5.0.9-beta+build.131.jar:?]
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.render.GameRenderer.render(GameRenderer:874) ~[?:?]
[01/11/2021 17:54:33 PM] 	... 10 more
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: OpenGL debug message: id=2, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM in glPolygonMode(face)'
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: java.lang.Throwable
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1008.handler$ckc000$onLogging(class_1008.java:521)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1008.method_4224(class_1008.java:104)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.GL11C.glPolygonMode(Native Method)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.GL11.glPolygonMode(GL11.java:5040)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.platform.GlStateManager._polygonMode(GlStateManager.java:468)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.polygonMode(RenderSystem.java:359)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at fudge.notenoughcrashes.utils.GlUtil.resetState(GlUtil.java:52)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.resetStates(InGameCatcher.java:41)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:32)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.modify$eeb000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:15593)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:750)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:217)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: OpenGL debug message: id=2, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM in glPolygonMode(face)'
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: java.lang.Throwable
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1008.handler$ckc000$onLogging(class_1008.java:521)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1008.method_4224(class_1008.java:104)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.GL11C.glPolygonMode(Native Method)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.GL11.glPolygonMode(GL11.java:5040)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.platform.GlStateManager._polygonMode(GlStateManager.java:468)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.polygonMode(RenderSystem.java:359)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at fudge.notenoughcrashes.utils.GlUtil.resetState(GlUtil.java:53)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.resetStates(InGameCatcher.java:41)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:32)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.modify$eeb000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:15593)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:750)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:217)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/FATAL]: Unreported exception thrown!
[01/11/2021 17:54:33 PM] java.lang.IllegalArgumentException: Invalid count: 4
[01/11/2021 17:54:33 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.62) ~[?:?]
[01/11/2021 17:54:33 PM] 	at team.reborn.energy.api.base.SimpleBatteryItem.getStoredEnergy(SimpleBatteryItem.java:55) ~[team_reborn_energy-2.0.0-beta1-a90c99d8af2f3ca2.jar:?]
[01/11/2021 17:54:33 PM] 	at reborncore.common.util.ItemUtils.getPowerForDurabilityBar(ItemUtils.java:116) ~[RebornCore-5.0.9-beta+build.131.jar:?]
[01/11/2021 17:54:33 PM] 	at techreborn.items.BatteryItem.getDurability(BatteryItem.java:117) ~[TechReborn-5.0.9-beta+build.131.jar:?]
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.render.item.ItemRenderer.handler$fam000$renderGuiItemOverlay(ItemRenderer:5062) ~[?:?]
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.render.item.ItemRenderer.renderGuiItemOverlay(ItemRenderer) ~[?:?]
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.gui.screen.ingame.HandledScreen.drawSlot(HandledScreen:266) ~[?:?]
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen:123) ~[?:?]
[01/11/2021 17:54:33 PM] 	at reborncore.client.gui.builder.GuiBase.render(GuiBase.java:261) ~[RebornCore-5.0.9-beta+build.131.jar:?]
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.render.GameRenderer.render(GameRenderer:874) ~[?:?]
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112) ~[?:?]
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.main.Main.main(Main:217) [intermediary-client-1.17.1.jar:?]
[01/11/2021 17:54:33 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[01/11/2021 17:54:33 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
[01/11/2021 17:54:33 PM] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[01/11/2021 17:54:33 PM] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
[01/11/2021 17:54:33 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-loader-0.12.2.jar:?]
[01/11/2021 17:54:33 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.12.2.jar:?]
[01/11/2021 17:54:33 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.2.jar:?]
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/FATAL]: Minecraft ran into a problem! Report saved to: **USERSDIR**/instances/MathAndMarty/crash-reports/crash-2021-11-01_17.54.33-client.txt
[01/11/2021 17:54:33 PM] ---- Minecraft Crash Report ----
[01/11/2021 17:54:33 PM] // Why did you do that?
[01/11/2021 17:54:33 PM] 
[01/11/2021 17:54:33 PM] Time: 11/1/21, 5:54 PM
[01/11/2021 17:54:33 PM] Description: Rendering screen
[01/11/2021 17:54:33 PM] 
[01/11/2021 17:54:33 PM] java.lang.IllegalArgumentException: Invalid count: 4
[01/11/2021 17:54:33 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.62)
[01/11/2021 17:54:33 PM] 	at team.reborn.energy.api.base.SimpleBatteryItem.getStoredEnergy(SimpleBatteryItem.java:55)
[01/11/2021 17:54:33 PM] 	at reborncore.common.util.ItemUtils.getPowerForDurabilityBar(ItemUtils.java:116)
[01/11/2021 17:54:33 PM] 	at techreborn.items.BatteryItem.getDurability(BatteryItem.java:117)
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.render.item.ItemRenderer.handler$fam000$renderGuiItemOverlay(ItemRenderer:5062)
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.render.item.ItemRenderer.renderGuiItemOverlay(ItemRenderer)
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.gui.screen.ingame.HandledScreen.drawSlot(HandledScreen:266)
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen:123)
[01/11/2021 17:54:33 PM] 	at reborncore.client.gui.builder.GuiBase.render(GuiBase.java:261)
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.render.GameRenderer.render(GameRenderer:874)
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112)
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
[01/11/2021 17:54:33 PM] 	at net.minecraft.client.main.Main.main(Main:217)
[01/11/2021 17:54:33 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01/11/2021 17:54:33 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01/11/2021 17:54:33 PM] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01/11/2021 17:54:33 PM] 	at java.lang.reflect.Method.invoke(Method.java:568)
[01/11/2021 17:54:33 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
[01/11/2021 17:54:33 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[01/11/2021 17:54:33 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[01/11/2021 17:54:33 PM] 
[01/11/2021 17:54:33 PM] 
[01/11/2021 17:54:33 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[01/11/2021 17:54:33 PM] ---------------------------------------------------------------------------------------
[01/11/2021 17:54:33 PM] 
[01/11/2021 17:54:33 PM] -- Head --
[01/11/2021 17:54:33 PM] Thread: Render thread
[01/11/2021 17:54:33 PM] Stacktrace:
[01/11/2021 17:54:33 PM] 	at team.reborn.energy.api.base.SimpleBatteryItem.getStoredEnergy(SimpleBatteryItem.java:55)
[01/11/2021 17:54:33 PM] 	at reborncore.common.util.ItemUtils.getPowerForDurabilityBar(ItemUtils.java:116)
[01/11/2021 17:54:33 PM] 	at techreborn.items.BatteryItem.getDurability(BatteryItem.java:117)
[01/11/2021 17:54:33 PM] 	at net.minecraft.class_918.handler$fam000$renderGuiItemOverlay(class_918.java:5062)
[01/11/2021 17:54:33 PM] 	at net.minecraft.class_918.method_4022(class_918.java)
[01/11/2021 17:54:33 PM] 	at net.minecraft.class_465.method_2385(class_465.java:266)
[01/11/2021 17:54:33 PM] 	at net.minecraft.class_465.method_25394(class_465.java:123)
[01/11/2021 17:54:33 PM] 	at reborncore.client.gui.builder.GuiBase.method_25394(GuiBase.java:261)
[01/11/2021 17:54:33 PM] 
[01/11/2021 17:54:33 PM] 		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
[01/11/2021 17:54:33 PM] [17:54:33] [Render thread/ERROR]: Unhandled game exception

[01/11/2021 17:53:24 PM] Mods:
[01/11/2021 17:53:24 PM]  - /oxidized-1.4.0.jar
[01/11/2021 17:53:24 PM]  - /indium-1.0.0+mc1.17.1.jar
[01/11/2021 17:53:24 PM]  - /RoughlyEnoughItems-6.0.306-alpha.jar
[01/11/2021 17:53:24 PM]  - /indrev-1.11.0-alpha.3.jar
[01/11/2021 17:53:24 PM]  - /lithium-fabric-mc1.17.1-0.7.4.jar
[01/11/2021 17:53:24 PM]  - /fabric-api-0.41.0+1.17.jar
[01/11/2021 17:53:24 PM]  - /dataattributes-1.0.6-1.17.1.jar
[01/11/2021 17:53:24 PM]  - /DimensionalDoors-4.0.0+beta.4-10.10.2021.jar
[01/11/2021 17:53:24 PM]  - /durability-speed-1.4.0.jar
[01/11/2021 17:53:24 PM]  - /EmeraldTools-Fabric-1.17.1-1.2.27.jar
[01/11/2021 17:53:24 PM]  - /EntityCulling-Fabric-1.3.3.jar
[01/11/2021 17:53:24 PM]  - /fabric-language-kotlin-1.6.5+kotlin.1.5.31.jar
[01/11/2021 17:53:24 PM]  - /forgottenrecipes-fabric-1.17.1-1.0.3.jar
[01/11/2021 17:53:24 PM]  - /glassential-fabric-1.17-1.2.0.jar
[01/11/2021 17:53:24 PM]  - /goldenhoppers-1.1.0.jar
[01/11/2021 17:53:24 PM]  - /ninjaphenix-container-library-1.2.4+1.17.1.jar
[01/11/2021 17:53:24 PM]  - /Pehkui-2.5.2+1.14.4-1.18.jar
[01/11/2021 17:53:24 PM]  - /riverredux-0.2.0.jar
[01/11/2021 17:53:24 PM]  - /trinkets-3.0.4.jar
[01/11/2021 17:53:24 PM]  - /expandedstorage-7.2.7+1.17.1.jar
[01/11/2021 17:53:24 PM]  - /atlantis-2021.7.18-1.17-2.0.2-fabric.jar
[01/11/2021 17:53:24 PM]  - /packages-1.17.1-1.2.1.jar
[01/11/2021 17:53:24 PM]  - /InventorySorter-1.8.0-1.17.jar
[01/11/2021 17:53:24 PM]  - /impaled-1.0.1.jar
[01/11/2021 17:53:24 PM]  - /immersive-portals-0.29-mc1.17.1-fabric.jar
[01/11/2021 17:53:24 PM]  - /playerex-3.0.6-1.17.1.jar
[01/11/2021 17:53:24 PM]  - /iron-jetpacks-0.4.0.jar
[01/11/2021 17:53:24 PM]  - /DisableCustomWorldsAdvice-1.3.jar
[01/11/2021 17:53:24 PM]  - /architectury-2.5.32.jar
[01/11/2021 17:53:24 PM]  - /cloth-config-5.0.38-fabric.jar
[01/11/2021 17:53:24 PM]  - /1.17.1-additionalbars-2.1.1.jar
[01/11/2021 17:53:24 PM]  - /AdditionalEnchantedMiner-1.17-fabric-17.0.390.jar
[01/11/2021 17:53:24 PM]  - /adventurez-1.3.0.jar
[01/11/2021 17:53:24 PM]  - /antighost-1.17.1-fabric0.36.1-1.1.4.jar
[01/11/2021 17:53:24 PM]  - /appliedenergistics2-9.0.0-alpha.6.jar
[01/11/2021 17:53:24 PM]  - /AE2WTLib-9.0.0-beta.3.jar
[01/11/2021 17:53:24 PM]  - /artifality-mc1.17.1-0.4.2.jar
[01/11/2021 17:53:24 PM]  - /autoconfig1u-3.3.1.jar
[01/11/2021 17:53:24 PM]  - /autotorch-mc1.17.1-1.2.2+build.2.jar
[01/11/2021 17:53:24 PM]  - /bclib-0.3.1.jar
[01/11/2021 17:53:24 PM]  - /blast-1.8.jar
[01/11/2021 17:53:24 PM]  - /backslot-1.2.1.jar
[01/11/2021 17:53:24 PM]  - /betterf3-1.1.5+1.17.jar
[01/11/2021 17:53:24 PM]  - /better-nether-5.1.3.jar
[01/11/2021 17:53:24 PM]  - /bewitchment-1.17-12.jar
[01/11/2021 17:53:24 PM]  - /bitsandchisels-2.5.3.jar
[01/11/2021 17:53:24 PM]  - /blockus-2.2.10+1.17.1.jar
[01/11/2021 17:53:24 PM]  - /BOMD-1.3.2-1.17.1.jar
[01/11/2021 17:53:24 PM]  - /cc-restiched-1.97.1-beta-1.jar
[01/11/2021 17:53:24 PM]  - /caelus-fabric-0.0.18-1.17.1.jar
[01/11/2021 17:53:24 PM]  - /Cardinal-Components-API-3.1.1.jar
[01/11/2021 17:53:24 PM]  - /carrier-1.8.0.jar
[01/11/2021 17:53:24 PM]  - /cavebiomes-0.6.3.jar
[01/11/2021 17:53:24 PM]  - /Chunky-1.2.124.jar
[01/11/2021 17:53:24 PM]  - /cloth-api-2.0.54.jar
[01/11/2021 17:53:24 PM]  - /columns-1.2.0.jar
[01/11/2021 17:53:24 PM]  - /dawn-2.0.6.jar
[01/11/2021 17:53:24 PM]  - /diggusmaximus-1.5.1-1.17.jar
[01/11/2021 17:53:24 PM]  - /drinkbeer-v2.2 for 1.17.x.jar
[01/11/2021 17:53:24 PM]  - /dyeablenetherite-1.3.0.jar
[01/11/2021 17:53:24 PM]  - /EditSign-1.17.1-2.2.3.jar
[01/11/2021 17:53:24 PM]  - /extra-generators-1.1-BETA+1.17.jar
[01/11/2021 17:53:24 PM]  - /fabric-seasons-1.3.1-BETA+1.17.jar
[01/11/2021 17:53:24 PM]  - /FallingTree-1.17.1-2.14.1.jar
[01/11/2021 17:53:24 PM]  - /geckolib-fabric-1.17-3.0.18.jar
[01/11/2021 17:53:24 PM]  - /Gobber2-Fabric-1.17.1-2.4.53.jar
[01/11/2021 17:53:24 PM]  - /impersonate-2.3.5.jar
[01/11/2021 17:53:24 PM]  - /Patchouli-1.17.1-56-FABRIC.jar
[01/11/2021 17:53:24 PM]  - /pal-1.3.0.jar
[01/11/2021 17:53:24 PM]  - /somnus-fabric-0.0.14-1.17.1.jar
[01/11/2021 17:53:24 PM]  - /wthit-fabric-3.10.0.jar
[01/11/2021 17:53:24 PM]  - /can-i-mine-this-block-1.1.0.jar
[01/11/2021 17:53:24 PM]  - /icarus-1.8.jar
[01/11/2021 17:53:24 PM]  - /illegal-substances-that-you-should-not-do-in-real-life-craft-1.0.0.jar
[01/11/2021 17:53:24 PM]  - /IndustrialChronicle-1.17.01.jar
[01/11/2021 17:53:24 PM]  - /interactic-0.1.6-1.17.jar
[01/11/2021 17:53:24 PM]  - /konkrete_fabric_1.3.0_MC_1.17-1.17.1.jar
[01/11/2021 17:53:24 PM]  - /krypton-0.1.4.jar
[01/11/2021 17:53:24 PM]  - /letitgrow-1.0.0.jar
[01/11/2021 17:53:24 PM]  - /lifts-1.3-BETA+1.17.jar
[01/11/2021 17:53:24 PM]  - /linkedstorage-1.3.13.17.jar
[01/11/2021 17:53:24 PM]  - /mcdw-3.5.5.jar
[01/11/2021 17:53:24 PM]  - /mostructures-1.3.0-pre1-1.17.1-fabric.jar
[01/11/2021 17:53:24 PM]  - /OreRevolution-1.17.1-1.0.4-[FABRIC].jar
[01/11/2021 17:53:24 PM]  - /moreblockbricks-1.3.1-mc-1.17.x.jar
[01/11/2021 17:53:24 PM]  - /morevillagers-FABRIC-1.17-2.1.1.jar
[01/11/2021 17:53:24 PM]  - /mousewheelie-1.7.3-newconfig+mc1.17.1-pre1.jar
[01/11/2021 17:53:24 PM]  - /noenchantcap-4.1.0.jar
[01/11/2021 17:53:24 PM]  - /notenoughcrashes-3.7.0+1.17.1-fabric.jar
[01/11/2021 17:53:24 PM]  - /polymorph-fabric-0.0.14-1.17.1.jar
[01/11/2021 17:53:24 PM]  - /quartz-elevator-1.2.5-1.17.1.jar
[01/11/2021 17:53:24 PM]  - /realisticfirespread-1.17-3.jar
[01/11/2021 17:53:24 PM]  - /smootherbedrock-1.0.2.jar
[01/11/2021 17:53:24 PM]  - /snow-under-trees-fabric-mc1.17.0-1.0.0.jar
[01/11/2021 17:53:24 PM]  - /agape_space_17-0.3.3.jar
[01/11/2021 17:53:24 PM]  - /stacker-2.0.0.jar
[01/11/2021 17:53:24 PM]  - /stoneholm-1.3.jar
[01/11/2021 17:53:24 PM]  - /stonevaults-1.1.0.jar
[01/11/2021 17:53:24 PM]  - /branders-sulfurpotassiummod-1.17-1.1.1.jar
[01/11/2021 17:53:24 PM]  - /TacoCraft-1.6.5-1.17.1.jar
[01/11/2021 17:53:24 PM]  - /talking-villagers-1.1.3.jar
[01/11/2021 17:53:24 PM]  - /The_Graveyard_(FABRIC)_1.4_for_1.17-1.17.1.jar
[01/11/2021 17:53:24 PM]  - /darkness-mc117-1.6.74.jar
[01/11/2021 17:53:24 PM]  - /graves-1.1.3b+1.17.1.jar
[01/11/2021 17:53:24 PM]  - /universal_ores-1.0.jar
[01/11/2021 17:53:24 PM]  - /upgradedechests-1.0.3-1.17.jar
[01/11/2021 17:53:24 PM]  - /vampirehunters-1.1.jar
[01/11/2021 17:53:24 PM]  - /vanillaplusbiomes-0.3.2.jar
[01/11/2021 17:53:25 PM]  - /DungeonsArise-1.17.1-2.1.48-fabric-beta.jar
[01/11/2021 17:53:25 PM]  - /winged-1.17.1-3.0.0.jar
[01/11/2021 17:53:25 PM]  - /wirelessnetworks-1.3.0.jar
[01/11/2021 17:53:25 PM]  - /world_blender_fabric-3.0.7+1.17.0.jar
[01/11/2021 17:53:25 PM]  - /xp_storage-1.4.2+1.17.1.jar
[01/11/2021 17:53:25 PM]  - /Xaeros_Minimap_21.19.0_Fabric_1.17.1.jar
[01/11/2021 17:53:25 PM]  - /XaerosWorldMap_1.17.3_Fabric_1.17.1.jar
[01/11/2021 17:53:25 PM]  - /YungsApi-1.17-Fabric-19.jar
[01/11/2021 17:53:25 PM]  - /BetterDungeons-Fabric-1.17-1.0.2.jar
[01/11/2021 17:53:25 PM]  - /BetterMineshafts-Fabric-1.17-1.0.1.jar
[01/11/2021 17:53:25 PM]  - /zombified-1.2.0.jar
[01/11/2021 17:53:25 PM]  - /modmenu-2.0.14.jar
[01/11/2021 17:53:25 PM]  - /mcda-1.7.15.jar
[01/11/2021 17:53:25 PM]  - /voidz-1.0.5.jar
[01/11/2021 17:53:25 PM]  - /TechReborn-5.0.9-beta+build.131.jar
[01/11/2021 17:53:25 PM]  - /iris-and-sodium-mc1.17-1.1.2+build.9.jar
[01/11/2021 17:53:25 PM]  - /Modern-Industrialization-0.6.0-alpha.02.jar
[01/11/2021 17:53:25 PM]  - /mythic-mounts-1.17.1-2.0.jar
[01/11/2021 17:53:25 PM]  - /denseores-1.1+1.17.jar

**Comment by Technici4n** [comment]
Fixed in Fabric API 0.42.0.
