### ISSUE TITLE
Conflict with CC-Restiched ?

### ISSUE THREAD

**Issue by OnkelDrako** [TechReborn/TechReborn#2616]
Minecraft crashed on startup

Works witout CC-Restiched

I possted it on CC-Restiched aswell.

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 11/23/21, 5:26 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'techreborn'!
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
at net.minecraft.class_310.(class_310.java:457)
at net.minecraft.client.main.Main.main(Main.java:179)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Suppressed: java.lang.NoClassDefFoundError: Could not initialize class dan200.computercraft.shared.ComputerCraftRegistry$ModTiles
at dan200.computercraft.shared.ComputerCraftRegistry.init(ComputerCraftRegistry.java:79)
at dan200.computercraft.ComputerCraft.onInitialize(ComputerCraft.java:134)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
... 11 more
Caused by: java.lang.ExceptionInInitializerError
at dan200.computercraft.shared.ComputerCraftRegistry$ModBlocks.(ComputerCraftRegistry.java:94)
at dan200.computercraft.shared.ComputerCraftRegistry$ModItems.(ComputerCraftRegistry.java:206)
at ml.pkom.advancedreborn.addons.computercraft.ComputerCraftAddon.addRightUpgradeForNormalAsStack(ComputerCraftAddon.java:109)
at ml.pkom.advancedreborn.addons.computercraft.ComputerCraftAddon.init(ComputerCraftAddon.java:65)
at ml.pkom.advancedreborn.ModManager.initAfterLoadedTR(ModManager.java:18)
at techreborn.TechReborn.handler$fdk000$onInitialize(TechReborn.java:514)
at techreborn.TechReborn.onInitialize(TechReborn.java:121)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
... 11 more
Caused by: java.lang.NullPointerException
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
at com.google.common.collect.SingletonImmutableSet.(SingletonImmutableSet.java:47)
at com.google.common.collect.ImmutableSet.of(ImmutableSet.java:82)
at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:319)
at net.minecraft.class_2591$class_2592.method_20528(class_2591.java:109)
at net.fabricmc.fabric.api.object.builder.v1.block.entity.FabricBlockEntityTypeBuilder.build(FabricBlockEntityTypeBuilder.java:50)
at net.fabricmc.fabric.api.object.builder.v1.block.entity.FabricBlockEntityTypeBuilder.build(FabricBlockEntityTypeBuilder.java:46)
at dan200.computercraft.shared.ComputerCraftRegistry$ModTiles.ofBlock(ComputerCraftRegistry.java:195)
at dan200.computercraft.shared.ComputerCraftRegistry$ModTiles.(ComputerCraftRegistry.java:154)
... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Render thread
Stacktrace:
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
at net.minecraft.class_310.(class_310.java:457)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.main.Main.main(Main.java:179)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
Minecraft Version: 1.17.1
Minecraft Version ID: 1.17.1
Operating System: Windows 10 (amd64) version 10.0
Java Version: 16.0.1, Microsoft
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
Memory: 1764879048 bytes (1683 MiB) / 2810183680 bytes (2680 MiB) up to 12884901888 bytes (12288 MiB)
CPUs: 4
Processor Vendor: GenuineIntel
Processor Name: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
Identifier: Intel64 Family 6 Model 58 Stepping 9
Microarchitecture: Ivy Bridge (Client)
Frequency (GHz): 3.19
Number of physical packages: 1
Number of physical CPUs: 4
Number of logical CPUs: 4
Graphics card #0 name: Radeon RX 560 Series
Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
Graphics card #0 VRAM (MB): 4095.00
Graphics card #0 deviceId: 0x67ff
Graphics card #0 versionInfo: DriverVersion=30.0.13033.1000
Memory slot #0 capacity (MB): 8192.00
Memory slot #0 clockSpeed (GHz): 1.33
Memory slot #0 type: DDR3
Memory slot #1 capacity (MB): 8192.00
Memory slot #1 clockSpeed (GHz): 1.33
Memory slot #1 type: DDR3
Virtual memory max (MB): 32210.45
Virtual memory used (MB): 11666.27
Swap memory total (MB): 15872.00
Swap memory used (MB): 117.38
JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
Fabric Mods:
additionaladditions: Additional Additions 2.2.0
additionalbars: Additional Bars 2.1.1
adorn: Adorn 2.3.1+1.17.1
advanced_reborn: Advanced Reborn 1.0.0
advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
advancements-enlarger: Advancements Enlarger 0.2.4
advdebug: Advancements Debug 2.3.0
adventurez: AdventureZ 1.4.2
allarrowsinfinityfix: All Arrows Infinity Fix 1.0.0
alloy_forgery: Alloy Forgery 2.0.6
ambientenvironment: Ambient Environment 6.0.22
amecsapi: Amecs API 1.1.5+mc21w16a
animal_feeding_trough: Animal Feeding Trough 1.0.2
appleskin: AppleSkin mc1.17-2.1.3
appliedenergistics2: Applied Energistics 2 9.0.0-beta.2
aqupdcaracal: Caracal mob 1.17-1.3.2
aqupdgrizzly: Grizzly Bear mob 1.17-1.2.0
architects_palette: Architect's Palette Fabric 1.2
architectury: Architectury 2.6.35
artifality: Artifality 0.4.2
assembly: Assembly 21w06a-1.0.0
attributefix: Attribute Fix {FABRIC} 1.0.3
autoconfig1u: Auto Config v1 Updated 3.3.1
autofish: Autofish 0.9.3
autotorch: Autotorch 1.2.2+build.2
axolotlitemfix: Axolotl Item Fix 1.1.3
backslot: BackSlot 1.2.2
backslotaddon: BackSlot Addon 1.0.7
basicshields: Basic Shields [Fabric] 1.1.1-1.17.1
bclib: BCLib 0.5.1
beaconoverhaul: Beacon Overhaul 1.4.2+1.17
beehivetooltips: Beehive Tooltips 1.3.1
betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
betterend: Better End 0.12.2
betterf3: BetterF3 1.1.5
bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
betternether: Better Nether 5.1.3
betterstrongholds: YUNG's Better Strongholds 1.17-1.1.2
bfapi: BFAPI 1.1.11
blockus: Blockus 2.2.10+1.17.1
blue_endless_jankson: jankson 1.2.1
blur: Blur (Fabric) 2.4.0
boatcontainer: BoatContainer 1.0.3
bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.2-1.17.1
bountiful: Bountiful 1.0.0
breakprogress: Break Progress 1.0.1
caelus: Caelus API 0.0.16-1.17
campanion: Campanion 2.0.1
cardinal-components: Cardinal Components API 3.1.1
cardinal-components-base: Cardinal Components API (base) 3.1.1
cardinal-components-block: Cardinal Components API (blocks) 3.1.1
cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
cardinal-components-entity: Cardinal Components API (entities) 3.1.1
cardinal-components-item: Cardinal Components API (items) 3.1.1
cardinal-components-level: Cardinal Components API (world saves) 3.1.1
cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
cardinal-components-util: Cardinal Components API (utilities) 3.1.1
cardinal-components-world: Cardinal Components API (worlds) 3.1.1
carrier: Carrier 1.8.1
caves-and-cliffs-add-on-for-william-wythers-overhauled-overworld: Caves and Cliffs add-on for William Wythers Overhauled Overworld 1.4
charm: Charm 3.3.2
charmonium: Charmonium 3.3.0
cherishedworlds: Cherished Worlds 2.0.1-1.17.1
chord: Chord 1.8.0+1.17-rc1-fabric
cleancut: CleanCut 1.17-4.0-fabric
cloth-api: Cloth API 2.0.54
cloth-basic-math: cloth-basic-math 0.6.0
cloth-client-events-v0: Cloth Client Events v0 2.0.54
cloth-common-events-v1: Cloth Common Events v1 2.0.54
cloth-config2: Cloth Config v5 5.1.40
cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
cloth-utils-v1: Cloth Utils v1 2.0.54
clumps: Clumps 7.0.10
collective-fabric: Collective (Fabric) 1.62
colorfulsubtitles: Colorful Subtitles 1.0.0
colytra: Colytra 2.0.0-1.17
com_electronwill_night-config_core: core 3.6.4
com_electronwill_night-config_toml: toml 3.6.4
com_eliotlash_mclib_mclib: mclib 18
com_eliotlash_molang_molang: molang 18
com_github_shevek_parallelgzip: parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
com_moandjiezana_toml_toml4j: toml4j 0.7.2
com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
comforts: Comforts 0.0.7-1.17.1
compostable-rottenflesh: Compostable Rotten Flesh 1.0.0
computercraft: CC:Restitched 1.97.2
connected-doors: Connected Doors 1.1+1.17
consistency_plus: Consistency Plus 0.4.1+1.17
controlling: Controlling For Fabric 1.1.2
convenient-mobgriefing: Convenient mobGriefing 2.0.2
cosmetica: Cosmetica 0.2.1
couplings: Couplings 1.5.0+1.17
cpas: cpas 2.0.1
cpas-api: cpas-api 2.0.1
cpas-runtime: cpas-runtime 2.0.1
cpas-trinkets: cpas-trinkets 2.0.1
craftpresence: CraftPresence 1.8.8
crawl: Crawl 0.9.3
croptopia: Croptopia 1.6.3
crowdin-translate: CrowdinTranslate 1.3+1.17
customportalapi: Custom Portal Api 0.0.1-beta46-1.17
dankstorage: Dank Storage 2.2.1-1.17.1
dark-enchanting: Dark Enchanting 0.4.1-1.17.1
darkpaintings: Dark Paintings 4.0.2
dashloader: DashLoader 2.0.1
dawn: Dawn API 2.0.6
deepslatecutting: Deepslate Cutting 1.2.2
denseores: Dense Ores: Refabricated 1.1+1.17
desolation: Desolation 1.1.5
diggusmaximus: Diggus Maximus 1.5.1-1.17
disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
disenchanter_block: Disenchanter Block 1.0.3
dragonloot: DragonLoot 1.0.9
drippyloadingscreen: Drippy Loading Screen 1.3.0
dual_riders: DualRiders 1.0.5
dungeons_arise: When Dungeons Arise 2.1.47-fabric
dynamicfps: Dynamic FPS 2.0.6
earthtojavamobs: Earth2Java 1.7.3+1.17
eatinganimationid: Eating Animation 1.2
ecotones: Ecotones 0.8.1
elytratrinket: Elytra Trinket 2.0.1-1.17
enchantment_lore: EnchantmentLore 1.2.1+MC1.17.1
enchantmentdescriptions: Enchantment Descriptions 4.0.1
endgoblintraders: End Goblin Traders 1.3.0
enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.17
enhancedcelestials: Enhanced Celestials 2.0.5
entityculling: EntityCulling-Fabric 1.3.3
equipmentcompare: Equipment Compare 1.2.7
exdel: Explorer's Delight 1.0.0-beta.1
extended_armor_bars: Extended Armor Bars 1.1.0
fabric: Fabric API 0.42.1+1.17
fabric-api-base: Fabric API Base 0.4.0+5847535018
fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+6d0fac4218
fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+6d0fac4218
fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+6d0fac4218
fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
fabric-tree-chopper: Fabric Tree Chopper 0.7.10
fabricenchantments: Fabric Enchantments 0.5.0
fabricloader: Fabric Loader 0.11.7
fabricshieldlib: Fabric Shield Lib 1.4.5+1.17
fabricsit: FabricSit 1.6.4
fake-player-api: Fake Player API 0.2.0
fallingleaves: Falling Leaves 1.7.4+1.17.1
fancymenu: FancyMenu 2.3.6
farmersdelight: Farmer's Delight 1.17.1-0.1.2
ferritecore: FerriteCore 3.0.3
fiber: fiber 0.23.0-2
fiber2cloth: Fiber To Cloth 3.2.0
flesh2leather: Flesh2Leather 1.0.2
flintytools: Flinty Tools 1.0.0
fluidtank: Fluid Tank 17.1.3-fabric
flytre-lib-base: Flytre Lib - Base Module 1.3.0
flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
flytre-lib-config: Flytre Lib - Config Module 1.1.0
flytre-lib-event: Flytre Lib - Event Module 1.0.1
flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
flytre-lib-storage: Flytre Lib - Storage Module 2.3.2
flytre_lib: Flytre Lib 1.4.2
forgeconfigapiport: Forge Config API Port 2.0.0
forgottenrecipes: Forgotten Recipes 1.0.3
fpsdisplay: FPS-Display 1.4.1+1.17
gateofbabylon: Gate Of Babylon 1.5.1-1.17.1
geckolib3: Geckolib 3.0.26
geodes: More Geodes 1.0.5
go-fish: Go Fish 1.3.0-beta-1.17.1
goblintraders: Goblin Traders 1.3.0
goldenhoppers: Golden Hoppers 1.1.0
goml: Get Off My Lawn 1.4.0-beta
gottaclimbfast: Gotta Climb Fast! 1.17-3.0-fabric
grass_pass: Grass Bypass 1.0.0
graveyard: The Graveyard 2.0
grindenchantments: Grind Enchantments 1.4.0+1.17.1
guiclock-fabric: GUI Clock (Fabric) 2.6
guild: Guild 0.3.4
helpwanted: Help Wanted 1.1.2
highlighter: Highlighter 1.1.1
hologram-api: Hologram API 0.2.1+1.17.1
hplus: Better Hoppers (Hopper+) 3.0.1
iceberg: Iceberg 1.0.23
illuminations: Illuminations 1.10
improved-stations: Improved Stations 2.0.7
indium: Indium 1.0.0+mc1.17.1
infusion_table: Infusion Table 1.0.2
inmis: Inmis 2.3.2-1.17.1
inventorio: Inventorio 1.6.2
inventoryhud: Inventory HUD + 3.4.1
io_activej_activej-codegen: activej-codegen 4.3
io_activej_activej-serializer: activej-serializer 4.3
iris: Iris 1.1.2+build.9
ironchest: Iron Chests 1.2.0+fabric-1.17.1
ironfurnaces: Iron Furnaces 1.17.1-2.6.1-fabric
jankson: Jankson 3.0.1+j1.2.0
java: OpenJDK 64-Bit Server VM 16
just_end_anchor: Just An End Anchor 1.0.1
kambrik: Kambrik 1.1.0
konkrete: Konkrete 1.3.0
krypton: Krypton 0.1.4
kubejs: KubeJS 1701.3.10-build.9999
kyrptconfig: Kytpt Config 1.1.10-1.17
lazydfu: LazyDFU 0.1.2
legendarytooltips: Legendary Tooltips 1.1.2
libblockattributes: LibBlockAttributes 0.9.2
libblockattributes_core: LibBlockAttributes (Core) 0.9.2
libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.2
libblockattributes_items: LibBlockAttributes (Items) 0.9.2
libcd: LibCapableData 3.0.3+1.16.3
libgui: LibGui 4.2.1+1.17.1
libmultipart: LibMultiPart 0.6.0
libnetworkstack: Lib Network Stack 0.5.0
libninepatch: LibNinePatch 1.1.0
libzoomer: LibZoomer 0.2.1+1.17
lightestlamp: Lightest Lamps 0.9.6
lightoverlay: Light Overlay 6.0.1
litematica: Litematica 0.0.0-dev.20210906.183617
litematicatool: Litematia Tool 1.2.1
lithium: Lithium 0.7.5
lovely_snails: Lovely Snails 1.0.3+1.17
maelstrom_library: Maelstrom Library 1.2.2-1.17.1
malilib: MaLiLib 0.10.0-dev.26
mavm: More Axolotl Variants Mod 1.0.5
maybe-data: Maybe data 1.0.1-1.17
maybe-more-data: Maybe More Data 1.0.0-1.17.1
megane: megane 5.5.2
megane-applied-energistics-2: megane-applied-energistics-2 5.5.2+9.0.0-beta.1
megane-base: megane-base 5.5.2
megane-fabric-transfer: megane-fabric-transfer 5.5.2+1.5.1-6d0fac4218
megane-lib-block-attributes: megane-lib-block-attributes 5.5.2+0.9.0
megane-reborn-core: megane-reborn-core 5.5.2+5.0.11-beta
megane-runtime: megane-runtime 5.5.2
megane-team-reborn-energy: megane-team-reborn-energy 5.5.2+2.0.0-beta1
megane-tech-reborn: megane-tech-reborn 5.5.2+5.0.11-beta
megane-vanilla: megane-vanilla 5.5.2+1.17.1
midnightlib: MidnightLib 0.3.0
minecraft: Minecraft 1.17.1
minershorizon: Miner's Horizon 1.7.2-1.17.1
mining_dims: Mining Dimensions 1.1.14
mm: Manningham Mills 2.3
modmenu: Mod Menu 2.0.14
morebannerfeatures: More Banner Features 1.0.9
morerespawnanchors: More Respawn Anchors 1.0.2
moretotems: More Totems 2.8.0
morevillagers-fabric: MoreVillagersFabric 2.1.1-SNAPSHOT
mostructures: Mo' Structures 1.3.0-pre1-1.17.1
mousewheelie: Mouse Wheelie 1.7.3+mc1.17.1-pre1
multipart_entities: MultipartEntities 1.1.3-1.17.1
naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
nears: Nears 1.1.2
nearsightedly: Near-Sightedly 1.2.1
notenoughcreativity: Not Enough Creativity 1.3.2
npcvariety: NPC Variety 2.2.0
observable: Observable 0.1.2-1.17
okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
omega-config: OmegaConfig 1.0.8
onsoulfire: On Soul Fire 1.17-3
org_apache_commons_commons-compress: commons-compress 1.19
org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
org_objenesis_objenesis: objenesis 3.2
org_slf4j_slf4j-api: slf4j-api 1.7.29
org_tukaani_xz: xz 1.8
org_yaml_snakeyaml: snakeyaml 1.27
outvoted: Outvoted 1.5.0-beta.3
owo: oωo 0.3.0
oxidized: Oxidized 1.4.0
oxidizelib: OxidizeLib 1.1.0
packet_tweaker: Packet Tweaker 0.2.0+1.17.1
paintings: Paintings ++ 1.17.1-1.0.0.3
patchouli: Patchouli 1.17.1-56-FABRIC
paxi: Paxi 1.17-1.2.2
pipe: Pipe 1.6.0
pipe_vacuum_pump: PipePump ${version}
pipeplus: PipePlus 0.3.2
placeholder-api: Placeholder API 1.1.1+1.17.1
plantinajar: Plant In A Jar 2.2.2
playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
plushies: Plushie Mod 1.0
polymer: Polymer 0.1.8+1.17.1
polymorph: Polymorph 0.0.14-1.17.1
prefab: Prefab 2.1.6
primordial-shores-add-on-for-wwoo: Primordial Shores add-on for William Wythers Overhauled Overworld 1.0
promenade: Promenade 2.1.2
puzzleslib: Puzzles Lib 2.0.1
quarrymod: Industial Quarry Mod 0.5.1
quarryplus: QuarryPlus 17.0.432
quartzelv: Quartz Elevator 1.2.5
ratsmischief: Rat's Mischief 1.3.1
reach-entity-attributes: Reach Entity Attributes 2.1.1
reborncore: Reborn Core 5.0.11-beta
repurposed_structures: Repurposed Structures 2.5.6+1.17.1
reroll: Reroll 1.3.0-1.17.1
rhino: Rhino 1701.1.5-build.71
rightclickharvest: Right Click Harvest 1.5.0
roughlyenoughitems: Roughly Enough Items 6.1.329
roughlyenoughresources: Roughly Enough Resources 2.2.0
rpg-hud: RPG-Hud 3.9.1
rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
runelic: Runelic 3.0.1
satin: Satin 1.6.4
scorch: Scorch 1.2.0
seasons: Fabric Seasons 1.3.1-BETA+1.17
server_translations_api: Server Translations API 1.4.6+1.17
sgui: SGui 1.0.0-rc4+1.17.1
simple_backpack: SimpleBackpack 1.1.19
simple_pipes: SimplePipeTest 0.6.1
simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.6.1
simplelife: SimpleLife 0.0.11
sit: Sit 1.17.1-13
skinlayers: 3d Skin Layers 1.2.1
smootherbedrock: Smoother Bedrock 1.0.2
smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
snowundertrees: Snow Under Trees 1.0.0
sodium: Sodium 0.3.2+IRIS2-build.9
someforgepatchesported: Some Forge Patches Ported 1.0.1
somnus: Somnus API 0.0.13-1.17.1
spark: spark 1.6.2
spirit: Spirit 1.1.0
spruceui: SpruceUI 3.2.0+1.17
static-content: Static Content 1.0.1-1.16.2
staticdata: Static Data 1.1.2
stonecutter_recipe_tags: Stonecutter Recipe Tags 1.1.0
stoneholm: Stoneholm 1.3
stonevaults: Stonevaults 1.1.0
team_reborn_energy: Energy 2.0.0-beta1
techreborn: Tech Reborn 5.0.11-beta
terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 2.0.0
terraform-config-api-v1: Terraform Config API (v1) 2.0.0
terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 2.0.0
terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
terraform-surfaces-api-v1: Terraform Surfaces API (v1) 2.0.0
terraform-tree-api-v1: Terraform Tree API (v1) 2.0.0
terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
textile_backup: Textile Backup 2.2.0-1.17
the_bumblezone: The Bumblezone - Fabric 3.3.2+1.17.1
thonkutil: ThonkUtil 1.2
toms_storage: Tom's Simple Storage Mod 1.1.18
toolstats: Tool Stats 2.0.1
tooltipfix: ToolTip Fix 1.0.4-1.17.1
tradingpost: Trading Post 2.0.0
traverse: Traverse 4.0.0
trinketofundying: Trinket of Undying 2.0.0-1.17
trinkets: Trinkets 3.0.4
trinketshulkerboxes: Trinket Shulker Boxes 2.0.0-1.17
ttc: Tiny Trash Can 1.3.0
tweed: Tweed 3.0.0-beta.26
twigs: Twigs 1.0.2
unitool: Mattock 1.0.2
universal-graves: Universal Graves 1.1.3+1.17.1
universal_ores: Universal Ores 1.0
untitledduckmod: Untitled Duck Mod 0.3.0
urns: Urns 1.0.1
valley: ValleyCraft 1.3.2
vanilla_degus: Vanilla Degus 1.2.3
vanillaplusbiomes: Vanilla Plus Biomes 0.3.2
veinmining: Vein Mining 0.0.11-1.17.1
villager-hats: Villager Hats Mod 1.2.1
villagernames: Villager Names 2.0.1
visuality: Visuality 0.3.0
voidtotem: Void Totem (Fabric) 1.17.0-1.0.0
voidz: VoidZ 1.0.5
wandering_collector: Wandering Collector 1.0.2+mc1.17
wands: Building Wands 2.2.8_mc1.17.1
waystones: Waystones 2.2.1
wild_update: Wild Update 1.17.1-0.0.6
william-wythers-overhauled-overworld: William Wythers Overhauled Overworld 1.7
wolveswitharmor: Wolves With Armor 1.6.1-1.17.1
wthit: wthit 3.11.2
xaerominimap: Xaero's Minimap 21.14.0
xaeroworldmap: Xaero's World Map 1.15.0.1
xp_storage: XP Storage 1.4.2+1.17.1
xp_storage_trinkets: XP Storage - Trinkets 0.1+1.17.1
yosbr: YOSBR 0.1.1
yungsapi: YUNG's API 1.17-Fabric-19
Launched Version: fabric-loader-0.11.7-1.17.1
Backend library: LWJGL version 3.2.2 build 10
Backend API: NO CONTEXT
Window size:
GL Caps: Using framebuffer using OpenGL 3.2
GL debug messages:
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fabric'
Type: Client (map_client.txt)
CPU:

hope it help and i know i got toomany mods ^^
Greetz OnkelDrako

**Comment by OnkelDrako** [comment]
Turns out its some Other mod that couses the problem but Log tell other sorry . closing
