### ISSUE TITLE
Backport: RebornCore incompatible with current Fabric API version in 1.18.2

### ISSUE THREAD

**Issue by enderger** [TechReborn/TechReborn#2980]
**Describe the bug**
On recent Fabric API versions, the 5.2.0 update fails to load due to changes made in commit 3cb62b02911b72bbabb8163dedb03235b7c810d7 not being included. Since 1.18.2 is still the dominant version in the ecosystem, it would probably be best to also apply the patches to `WorldGen.java` in a 1.18 release, or build a 5.3.0 release using the 1.18 version

**Steps to Reproduce**
1. Try to load RebornCore in 1.18 with Fabric API >5.51.1
2. See error

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.2
 - Mod Loader: fabric (quilt v0.17.0, though this appears to affect Fabric API universally)

**Logs**
Here's the crash report, the caused by section should be strong evidence of this being an API compatibility issue.

```log
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 6/10/22, 3:07 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'techreborn'!
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:63)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:61)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:46)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:452)
	at net.minecraft.client.main.Main.main(Main:197)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)
Caused by: java.lang.ClassCastException: class techreborn.world.WorldGenerator$$Lambda$6515/0x0000000801cef1e8 cannot be cast to class java.util.function.Consumer (techreborn.world.WorldGenerator$$Lambda$6515/0x0000000801cef1e8 is in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @7de62196; java.util.function.Consumer is in module java.base of loader 'bootstrap')
	at net.fabricmc.fabric.api.biome.v1.BiomeModification.add(BiomeModification.java:64)
	at techreborn.world.WorldGenerator.initWorldGen(WorldGenerator.java:74)
	at techreborn.TechReborn.onInitialize(TechReborn.java:87)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:52)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59)
	... 21 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:63)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:61)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:46)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 5.15.40-xanmod1
	Java Version: 17.0.3, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1426426968 bytes (1360 MiB) / 4454350848 bytes (4248 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 4.65
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: GP108 [GeForce GT 1030]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1d01
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 12069.78
	Virtual memory used (MB): 10709.25
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 666.23
	JVM Flags: 2 total; -Xms512m -Xmx8192m
	Quilted Fabric API: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
	Quilt Mods: 
		additionaladditions: Additional Additions 4.0.4
		additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
		adorn: Adorn 3.5.0+1.18.2
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.7
		ae2: Applied Energistics 2 11.1.2
		ae2wtlib: AE2WTLib 11.1.0
		alloy_forgery: Alloy Forgery 2.0.13+1.18
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architects_palette: Architect's Palette Fabric 2.1
		architectury: Architectury 4.4.70
		authme: Auth Me 3.1.0
		badpackets: Bad Packets 0.1.2
		badwithernocookiereloaded: Bad Wither No Cookie! Reloaded 3.10.18 (Fabric 1.18.2)
		bannerpp: Banner++ 2.0.6-teb.1+mc.1.18.2
		betterf3: BetterF3 1.2.5
		bitsandchisels: BitsAndChisels 2.6.9
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.4.1
		botania: Botania 1.18.2-433-FABRIC
		campanion: Campanion 3.0.4
		canvas: Canvas Renderer 1.0.2360
		cardinal-components-base: Cardinal Components API (base) 4.1.4
		cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		cardinal-components-world: Cardinal Components API (worlds) 4.1.4
		charm: Charm 4.1.1
		charmonium: Charmonium 4.0.0
		chisel: Chisel Refabricated 1.4.5
		cloth-basic-math: cloth-basic-math 0.6.1
		cloth-config: Cloth Config v6 6.2.62
		cloth-utils-v1: Cloth Utils v1 2.0.54
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.13.1
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.13.1
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.13.1
		com_github_llamalad7_mixinextras: MixinExtras 0.0.10
		com_github_luben_zstd-jni: zstd-jni 1.5.2-2
		com_google_code_findbugs_jsr305: jsr305 3.0.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		computercraft: CC: Restitched 1.100.6
		consistency_plus: Consistency Plus 0.5.0+1.18.2
		continuity: Continuity 2.0.0+1.18.2
		create: Create mc1.18.2_v0.4.1+601
		createplus: CreatePlus 1.0
		crowdin-translate: CrowdinTranslate 1.4+1.18.2
		cull-less-leaves: Cull Less Leaves 1.0.1
		customportalapi: Custom Portal Api 0.0.1-beta50-1.18
		customsplashscreen: Custom Splash Screen 1.2.0
		dashloader: DashLoader 4.0.0
		dev_quantumfusion_hyphen: Hyphen 0.2.2
		dev_quantumfusion_taski: Taski 1.1.0
		dml-refabricated: Deep Mob Learning: Refabricated 1.18.2
		dml-refabricated-base: DML: Refabricated - Base 1.18.2
		dml-refabricated-events: DML: Refabricated - Vanilla Events 1.18.2
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 1.18.2
		dml-refabricated-rei: DML: Refabricated - REI Integration 1.18.2
		dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
		durabilityviewer: Giselbaers Durability Viewer 1.18.2-fabric0.47.10-1.10.3
		dynamic_asset_generator: DynamicAssetGenerator 0.6.2
		excavated_variants: Excavated Variants 0.6.2
		extraalchemy: Extra Alchemy 1.8.1
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 2.0.9+e19de87d60
		fabric-language-kotlin: Fabric Language Kotlin 1.8.0+kotlin.1.7.0
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fake-player-api: Fake Player API 0.3.0
		fallingleaves: Falling Leaves 1.11.1+1.18.2
		fastdecay: FastDecay 1.1.0
		ferritecore: FerriteCore 4.2.1
		fiber: fiber 0.23.0-2
		flywheel: Flywheel 1.18-0.7.0.26
		forge_tags: Forge Tags 2.1
		forgeconfigapiport: Forge Config API Port 3.2.0
		frex: FREX 6.0.258
		gbfabrictools: GBfabrictools 1.3.4+1.18.2
		gud_recipe_confidence: Recipe Confidence 1.0.2
		haema: Haema 1.9.9+1.18.2
		here-be-no-dragons: Here be no Dragons! 1.0.0
		iknowwhatimdoing: I Know What I'm Doing 4.0.0
		incorporeal: Incorporeal 3 1.18.2-2-SNAPSHOT-894c974c
		incubus_core: Incubus Core 1.7-rc.4
		interference: Interference API 1.3.9
		io_vram_bitkit: bitkit 1.0.4
		io_vram_bitraster: bitraster 1.5.53
		io_vram_dtklib: dtklib 1.0.6
		io_vram_special-circumstances: special-circumstances 1.10.7
		ironchests: Iron Chests 1.6.1
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		json-model-extensions: JSON Model Extensions 1.22.250
		kanos_config: Kanos Config 0.2.0+1.14.4-1.19
		kiln: Kiln 1.0.0
		krypton: Krypton 0.1.9
		ktdatataglib: KtDataTagLib 1.6.5+1.18.2
		kubejs: KubeJS 1802.5.4-build.480
		lambdabettergrass: LambdaBetterGrass 1.2.3+1.18
		lambdamap: LambdaMap 1.0.0-alpha.1+1.18
		lambdynlights: LambDynamicLights 2.1.0+1.17
		libblockattributes: LibBlockAttributes 0.10.2
		libblockattributes_core: LibBlockAttributes (Core) 0.10.2
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.2
		libblockattributes_items: LibBlockAttributes (Items) 0.10.2
		libgui: LibGui 5.4.1+1.18.2
		libmultipart: LibMultiPart 0.7.2
		libnetworkstack: Lib Network Stack 0.6.0
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.10
		lovely_snails: Lovely Snails 1.0.4+1.18
		magna: Magna 1.7.0-1.18-pre1
		malum: Malum (Quilt) b1.0.6
		mcwifipnp: LAN World Plug-n-Play 1.5.6
		memoryleakfix: memory Leak Fix 1.18.2-0.3.5
		midnightlib: MidnightLib 0.3.1
		milk: Milk Lib 0.3.2
		minecraft: Minecraft 1.18.2
		mm: Manningham Mills 2.3
		modern_industrialization: Modern Industrialization 1.2.0
		modmenu: Mod Menu 3.2.2
		moretags: More Tags 3.0.3
		mythicmetals: Mythic Metals 0.13.1
		no-telemetry: No Telemetry 1.3.0
		noindium: No Indium? 1.0.2+1.18.2
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		omega-config: OmegaConfig 1.2.3-1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.17.3
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.2
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.3.3
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		owo: oωo 0.7.2+1.18
		packages: Packages 1.4
		patchouli: Patchouli 1.18.2-69-FABRIC
		pehkui: Pehkui 3.2.2+1.14.4-1.19
		playerabilitylib: Pal 1.5.0
		porting_lib: Porting Lib 1.1.310-beta+1.18.2-dev.ba26474
		pride: Pride Lib 1.1.0+1.17
		quickcarpet: QuickCarpet 3.5.0
		quickcarpet-api: QuickCarpet API 2.0.0
		quilt_base: Quilt Base API 1.1.0-beta.18+1.18.2
		quilt_biome: Quilt Biome API 1.1.0-beta.18+1.18.2
		quilt_block_extensions: Quilt Block Extensions API 1.1.0-beta.18+1.18.2
		quilt_client_command: Quilt Client Command API 1.1.0-beta.18+1.18.2
		quilt_command: Quilt Command API 1.1.0-beta.18+1.18.2
		quilt_crash_info: Quilt Crash Info 1.1.0-beta.18+1.18.2
		quilt_dimension: Quilt Dimension API 1.1.0-beta.18+1.18.2
		quilt_item_group: Quilt Item Group API 1.1.0-beta.18+1.18.2
		quilt_item_setting: Quilt Item Setting API 1.1.0-beta.18+1.18.2
		quilt_lifecycle_events: Quilt Lifecycle Events 1.1.0-beta.18+1.18.2
		quilt_loader: Quilt Loader 0.17.0
		quilt_networking: Quilt Networking 1.1.0-beta.18+1.18.2
		quilt_recipe: Quilt Recipe API 1.1.0-beta.18+1.18.2
		quilt_registry: Quilt Registry API 1.1.0-beta.18+1.18.2
		quilt_registry_entry_attachments: Quilt Registry Entry Attachments 1.1.0-beta.18+1.18.2
		quilt_resource_loader: Quilt Resource Loader 1.1.0-beta.18+1.18.2
		quilt_screen: Quilt Screen API 1.1.0-beta.18+1.18.2
		quilt_tags: Quilt Tags API 1.1.0-beta.18+1.18.2
		quilt_tooltip: Quilt Tooltip API 1.1.0-beta.18+1.18.2
		quilted_fabric_api: Quilted Fabric API 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_api_base: Quilted Fabric API Base 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_api_lookup_api_v1: Quilted Fabric API Lookup API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_biome_api_v1: Quilted Fabric Biome API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_blockrenderlayer_v1: Quilted Fabric BlockRenderLayer Registration (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_command_api_v1: Quilted Fabric Command API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_commands_v0: Quilted Fabric Commands (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_containers_v0: Quilted Fabric Containers (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_content_registries_v0: Quilted Fabric Content Registries (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_convention_tags_api_v1: Quilted Fabric Convention Tags API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_crash_report_info_v1: Quilted Fabric Crash Report Info (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_dimensions_v1: Quilted Fabric Dimensions API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_entity_events_v1: Quilted Fabric Entity Events (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_events_interaction_v0: Quilted Fabric Events Interaction (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_events_lifecycle_v0: Quilted Fabric Events Lifecycle (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_game_rule_api_v1: Quilted Fabric Game Rule API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_item_api_v1: Quilted Fabric Item API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_item_groups_v0: Quilted Fabric Item Groups (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_key_binding_api_v1: Quilted Fabric Key Binding API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_keybindings_v0: Quilted Fabric Key Bindings (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_lifecycle_events_v1: Quilted Fabric Lifecycle Events (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_loot_api_v2: Quilted Fabric Loot API (v2) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_loot_tables_v1: Quilted Fabric Loot Tables (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_mining_level_api_v1: Quilted Fabric Mining Level API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_models_v0: Quilted Fabric Models (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_networking_api_v1: Quilted Fabric Networking API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_networking_v0: Quilted Fabric Networking (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_object_builder_api_v1: Quilted Fabric Object Builder API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_particles_v1: Quilted Fabric Particles (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_registry_sync_v0: Quilted Fabric Registry Sync (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_renderer_api_v1: Quilted Fabric Renderer API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_renderer_indigo: Quilted Fabric Renderer - Indigo 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_renderer_registries_v1: Quilted Fabric Renderer Registries (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_rendering_data_attachment_v1: Quilted Fabric Rendering Data Attachment (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_rendering_fluids_v1: Quilted Fabric Rendering Fluids (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_rendering_v0: Quilted Fabric Rendering (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_rendering_v1: Quilted Fabric Rendering (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_resource_conditions_api_v1: Quilted Fabric Resource Conditions API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_resource_loader_v0: Quilted Fabric Resource Loader (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_screen_api_v1: Quilted Fabric Screen API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_screen_handler_api_v1: Quilted Fabric Screen Handler API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_textures_v0: Quilted Fabric Textures (v0) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_transfer_api_v1: Quilted Fabric Transfer API (v1) 1.0.0-beta.19+0.55.1-1.18.2
		quilted_fabric_transitive_access_wideners_v1: Quilted Fabric Transitive Access Wideners (v1) 1.0.0-beta.19+0.55.1-1.18.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.2.0
		redbits: Red Bits 1.13.2
		registrate-fabric: Registrate for Fabric MC1.18.2-1.0.3
		rhino: Rhino 1802.1.13-build.175
		roughlyenoughitems: Roughly Enough Items 8.2.473
		satin: Satin 1.7.2
		secretrooms: Secret Rooms 1.3.1+1.18.2
		serialization_hooks: Serialization Hooks 0.2.0+1.18.cb29164
		simple_pipes: SimplePipeTest 0.7.2
		simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.7.2
		spectrum: Spectrum 1.4.1-1.18.2-chaos_and_exploration
		spoornpacks: SpoornPacks 1.2
		spruceui: SpruceUI 3.3.3+1.18
		stacc: Stacc 1.2.3
		starlight: Starlight 1.0.2+fabric.89b8d9f
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter_recipe_tags: Stonecutter Recipe Tags 3.0.1+1.18.bc850d5.fabric
		team_reborn_energy: Energy 2.2.0
		techreborn: Tech Reborn 5.2.0
		terraform-config-api-v1: Terraform Config API (v1) 3.0.0
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 3.0.0
		terraform-tree-api-v1: Terraform Tree API (v1) 3.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 3.0.0
		the_aether: Paradise Lost 1.6.8+1.18.2
		thorium: thorium 1.2.1
		tiefix: TieFix 1.10.0
		toms_storage: Tom's Simple Storage Mod 1.3.2
		traverse: Traverse 5.0.0-alpha.2
		trinkets: Trinkets 3.3.1
		twigs: Twigs 1.1.3+legacy.1.18.2
		waystones: Waystones 2.5.4
		wthit: wthit 4.10.3
		wthit-plugins: Wthit Plugins 1.0.5
	Flywheel Backend: Uninitialized
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'
	Type: Client (map_client.txt)
	CPU: <unknown>
	Suspected Mods: Quilt Loader (quilt_loader), Tech Reborn (techreborn), Minecraft (minecraft), Quilted Fabric Biome API (v1) (quilted_fabric_biome_api_v1)
```

**Additional context**

**Comment by modmuss50** [comment]
Please provide a log without quilt, just TR and API would do fine.

**Comment by enderger** [comment]
Alright, it appears as though I was mistaken. The issue appears to be with Quilt's implementation of Fabric API, so I apologise for wasting time.
