### ISSUE TITLE
REI Compat | Recycler Registry "Unknown"

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#3007]
**Describe the bug**
I notice in the game log:
```
[12:24:41] [REI-ReloadPlugins/ERROR]: Throwing
java.lang.IllegalStateException: Displays registered for unknown registry: techreborn:recycler
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.endReload(DisplayRegistryImpl.java:266) ~[RoughlyEnoughItems-8.3.510.jar:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.endReload(Reloadable.java:47) ~[RoughlyEnoughItems-8.3.510.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:366) ~[RoughlyEnoughItems-8.3.510.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:142) ~[RoughlyEnoughItems-8.3.510.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$25(RoughlyEnoughItemsCoreClient.java:482) ~[RoughlyEnoughItems-8.3.510.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Steps to Reproduce**
Steps to reproduce the behaviour:
- Install REI and Tech Reborn
- Enter a world

**Screenshots**
`N/A`

**Environment (please complete the following information with the version):**
 - Minecraft: `1.18.2`
 - Mod Loader: `Fabric`

**Logs**
[latest.log](https://pastebin.com/R7bt4w2t)

**Additional context**
`N/A`

**Comment by drcrazy** [comment]
Sorry, 1.18 is not getting a lot of love anymore since 1.19 is already in a wild for some time. You can try with REI 8.1.457. This last REI version tested together with TR.

**Comment by ghost** [comment]
Aw, understood. Thanks for giving me a solid REI version to use. Would you guys still accept PRs if I eventually tried to fix the issue myself? At this point I don't think I can update game versions.

**Comment by drcrazy** [comment]
Sure

**Comment by shedaniel** [comment]
The issue here is that the following line registers a filler for every recipe type in TR, while there are no corresponding `techreborn:recycler` REI category. A fix for this would be to not register that filler.

https://github.com/TechReborn/TechReborn/blob/29ade9092f51b1715b14e84b7340726c6bae0f3f/src/main/java/techreborn/compat/rei/ReiPlugin.java#L184

The cherry on top is that this issue should only be logging and doesn't affect the actual reload.

**Comment by kil0byt3** [comment]
@Brittank88 out of curiosity was this issue reported on a Mac or Windows computer

**Comment by ghost** [comment]
> @Brittank88 out of curiosity was this issue reported on a Mac or Windows computer

Windows 10
