### ISSUE TITLE
Some zombie villagers are missing their textures

### ISSUE THREAD

**Issue by CoreanXka** [TechReborn/TechReborn#3037]
**Describe the bug**
Some zombie villagers are missing their textures.
When summoning a sufficient number of zombie villagers, there are some without stickers.

Version：
Minecraft 1.18.2
RebornCore 5.2.0
TechReborn 5.2.0

**Comment by xanthian** [comment]
![image](https://user-images.githubusercontent.com/7688001/193449097-e5ff4cb8-94ec-4de2-9b0c-f0c9d724c97b.png)
confirmed in 1.18.2

```[Failed to load texture: techreborn:textures/entity/zombie_villager/profession/metallurgist.png]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.io.FileNotFoundException: techreborn:textures/entity/zombie_villager/profession/metallurgist.png
	at net.minecraft.class_3294.method_14486(class_3294.java:67)
	at net.minecraft.class_6861.method_14486(class_6861.java:47)
	at net.minecraft.class_3304.method_14486(class_3304.java:52)
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:81)
	at net.minecraft.class_1049.method_18153(class_1049.java:57)
	at net.minecraft.class_1049.method_4625(class_1049.java:28)
	at net.minecraft.class_1060.method_24303(class_1060.java:96)
	at net.minecraft.class_1060.method_4616(class_1060.java:68)
	at net.minecraft.class_1060.method_4619(class_1060.java:118)
	at net.minecraft.class_4668$class_4683.method_23563(class_4668.java:238)
	at net.minecraft.class_4668.method_23516(class_4668.java:36)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_1921$class_4687.method_23595(class_1921.java:929)
	at net.minecraft.class_4668.method_23516(class_4668.java:36)
	at net.minecraft.class_1921.method_23012(class_1921.java:727)
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:96)
	at net.minecraft.class_4597$class_4598.getBuffer(class_4597.java:45)
	at net.minecraft.class_3887.method_23199(class_3887.java:31)
	at net.minecraft.class_3885.method_17151(class_3885.java:74)
	at net.minecraft.class_3885.method_4199(class_3885.java:28)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1563)
	at net.minecraft.class_761.method_22710(class_761.java:1311)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)```

**Comment by xanthian** [comment]
Looks to be ok in 1.19.2
![image](https://user-images.githubusercontent.com/7688001/193449280-be419e4d-2c2e-4f03-b8e3-b40d073c005b.png)
![image](https://user-images.githubusercontent.com/7688001/193449438-95b34ec0-6464-4c31-9d0d-26073561d8a7.png)

**Comment by xanthian** [comment]
This would need backporting to fix.
https://github.com/TechReborn/TechReborn/commit/db499e60b2fe4ead588b5afadcd7ef3fa8e4910e

Not sure you are supporting 1.18.2 any more though :)

**Comment by Ayutac** [comment]
We are not.
