### ISSUE TITLE
Server crashes due to solar panel and is not able to boot any more.

### ISSUE THREAD

**Issue by Kasax007** [TechReborn/TechReborn#3085]
**Describe the bug**
Placed a solar panel for energy. Logged out and back it. Now always crashes the server when loading that chunk. 

**Steps to Reproduce**
I guess place a solar panel and then log out and back in. 

**Screenshots**
![image](https://user-images.githubusercontent.com/92468253/205652118-78612ec0-2e2e-4df3-b47a-b67cc9b5a2e7.png)

**Environment (please complete the following information with the version):**
 - Minecraft: [1.19.2]
 - Mod Loader: [fabric]

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**
A spatial harvester was attached to it

**Comment by Ayutac** [comment]
Always with the negative energy... Are you playing on newest TechReborn?

**Comment by Kasax007** [comment]
It gave me about 6 hours of work to fix the chunk that crashed the whole server :D The version is 
TechReborn-5.4.0.jar. Also maybe it was related to the spatial harvester attached to it. But unsure.

**Comment by Ayutac** [comment]
> spatial harvester
can you link the mod?

**Comment by Kasax007** [comment]
https://www.curseforge.com/minecraft/mc-mods/spatial-harvesters-fabric

**Comment by Avakining** [comment]
> It gave me about 6 hours of work to fix the chunk that crashed the whole server :D The version is TechReborn-5.4.0.jar. 

How did you fix it? Trying to fix my server's world after #3075 broke it

Edit: I fixed it by editing the chunk's NBT with [MCA Selector](https://github.com/Querz/mcaselector) to make the negative values positive (or you can just delete the TR cables)

**Comment by Twisted6** [comment]
Same issue. Essentially bricked the server without manually editing the chunk data.


Description: Ticking block entity

java.lang.IllegalArgumentException: Amount may not be negative, but it is: -64
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notNegative(StoragePreconditions.java:50)
	at team.reborn.energy.api.base.SimpleSidedEnergyContainer$SideStorage.insert(SimpleSidedEnergyContainer.java:72)
	at techreborn.blockentity.cable.CableTickManager.dispatchTransfer(CableTickManager.java:151)
	at techreborn.blockentity.cable.CableTickManager.handleCableTick(CableTickManager.java:78)
	at techreborn.blockentity.cable.CableBlockEntity.tick(CableBlockEntity.java:261)
	at techreborn.blocks.cable.CableBlock.lambda$getTicker$1(CableBlock.java:120)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:1623)

-- Head --
Thread: Server thread
Stacktrace:
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notNegative(StoragePreconditions.java:50)
	at team.reborn.energy.api.base.SimpleSidedEnergyContainer$SideStorage.insert(SimpleSidedEnergyContainer.java:72)
	at techreborn.blockentity.cable.CableTickManager.dispatchTransfer(CableTickManager.java:151)
	at techreborn.blockentity.cable.CableTickManager.handleCableTick(CableTickManager.java:78)
	at techreborn.blockentity.cable.CableBlockEntity.tick(CableBlockEntity.java:261)
	at techreborn.blocks.cable.CableBlock.lambda$getTicker$1(CableBlock.java:120)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)

-- Block entity being ticked --
Details:
	Name: techreborn:cable // techreborn.blockentity.cable.CableBlockEntity
	Block: Block{techreborn:insulated_hv_cable}[covered=false,down=false,east=false,north=false,south=true,up=false,waterlogged=false,west=true]
	Block location: World: (-3232,68,1737), Section: (at 0,4,9 in -202,4,108; chunk contains blocks -3232,-64,1728 to -3217,319,1743), Region: (-7,3; contains chunks -224,96 to -193,127, blocks -3584,-64,1536 to -3073,319,2047)
	Block: Block{techreborn:insulated_hv_cable}[covered=false,down=false,east=false,north=false,south=true,up=false,waterlogged=false,west=true]
	Block location: World: (-3232,68,1737), Section: (at 0,4,9 in -202,4,108; chunk contains blocks -3232,-64,1728 to -3217,319,1743), Region: (-7,3; contains chunks -224,96 to -193,127, blocks -3584,-64,1536 to -3073,319,2047)

**Comment by drcrazy** [comment]
Duplicate for https://github.com/TechReborn/TechReborn/issues/2697
