### ISSUE TITLE
Config wrench can crash the server by copying config from induction furnace to compressor 

### ISSUE THREAD

**Issue by Bluedot55** [TechReborn/TechReborn#3122]
Had a configuration setup for i/o on the two inputs and outputs of the induction furnace. Tried to copy config using the wrench to the compressor. Server crashed with below message logged 

`
[04:13:34] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking block entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$cka000$modifiedRunLoop(MinecraftServer.java:7885) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at java.util.Arrays$ArrayList.get(Arrays.java:4164) ~[?:?]
	at net.minecraft.class_2371.get(class_2371.java:47) ~[server-intermediary.jar:?]
	at reborncore.api.items.InventoryBase.method_5438(InventoryBase.java:68) ~[RebornCore-5.4.0.jar:?]
	at reborncore.common.blockentity.SlotConfiguration$SlotConfig.handleItemOutput(SlotConfiguration.java:304) ~[RebornCore-5.4.0.jar:?]
	at reborncore.common.blockentity.SlotConfiguration$SlotConfigHolder.lambda$handleItemIO$3(SlotConfiguration.java:187) ~[RebornCore-5.4.0.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at reborncore.common.blockentity.SlotConfiguration$SlotConfigHolder.handleItemIO(SlotConfiguration.java:182) ~[RebornCore-5.4.0.jar:?]
	at reborncore.common.blockentity.SlotConfiguration.lambda$update$0(SlotConfiguration.java:76) ~[RebornCore-5.4.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at reborncore.common.blockentity.SlotConfiguration.update(SlotConfiguration.java:76) ~[RebornCore-5.4.0.jar:?]
	at reborncore.common.blockentity.MachineBaseBlockEntity.tick(MachineBaseBlockEntity.java:185) ~[RebornCore-5.4.0.jar:?]
	at reborncore.common.powerSystem.PowerAcceptorBlockEntity.tick(PowerAcceptorBlockEntity.java:328) ~[RebornCore-5.4.0.jar:?]
	at techreborn.blockentity.machine.GenericMachineBlockEntity.tick(GenericMachineBlockEntity.java:93) ~[TechReborn-5.4.0.jar:?]
	at techreborn.blockentity.machine.GenericMachineBlockEntity.tick(GenericMachineBlockEntity.java:49) ~[TechReborn-5.4.0.jar:?]
	at reborncore.common.BaseBlockEntityProvider.lambda$getTicker$0(BaseBlockEntityProvider.java:77) ~[RebornCore-5.4.0.jar:?]
	at net.minecraft.class_2818$class_5563.redirect$ckd000$checkProcessBEs(carpet/mixins/BoundTickingBlockEntity_tickMixin.java [carpet.mixins.json]:37) ~[server-intermediary.jar:?]
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660) ~[server-intermediary.jar:?]
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:456) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:376) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$cka000$modifiedRunLoop(carpet/mixins/MinecraftServer_tickspeedMixin.java [carpet.mixins.json]:137) ~[server-intermediary.jar:?]
	... 3 more
`

**Comment by Bluedot55** [comment]
Note, this not only crashes the server, but will crash it on restart as well, since the config stays.

**Comment by drcrazy** [comment]
What is Config Wrench?

**Comment by Ayutac** [comment]
what is an induction furnace?

**Comment by modmuss50** [comment]
Closing this, TR doesnt have an induction furnace or config wrench.
