### ISSUE TITLE
Game crashes when loading a save

### ISSUE THREAD

**Issue by olive-spore-734** [TechReborn/TechReborn#3166]
**Describe the bug**
Game crashes when loading a save / a world (at 100%)
Removing Tech Reborn fixes the problem.

**Steps to Reproduce**
- Start minecraft
- load save

**Environment**
 - Minecraft: 1.19.2
 - Mod Loader: Fabric 0.14.21
 - Tech Reborn 5.3.3
 - Tech Reborn 5.3.4
 - Tech Reborn 5.4.0

**Logs**
Detailed Log: 
https://pastebin.com/jBspVf7m

---- Minecraft Crash Report ----
Description: Exception in server tick loop

java.lang.StackOverflowError: Exception in server tick loop
	at java.base/java.util.Collection.removeIf(Collection.java:574)
	at net.minecraft.class_167.method_727(class_167.java:37)
	at net.minecraft.class_2985.method_12884(class_2985.java:321)
	at net.minecraft.class_2985.method_12882(class_2985.java:315)
	at net.minecraft.class_2985.method_12877(class_2985.java:376)
	at net.minecraft.class_2985.method_12879(class_2985.java:353)
	at net.minecraft.class_2985.method_12885(class_2985.java:326)
	at net.minecraft.class_2985.method_12885(class_2985.java:346)
	at net.minecraft.class_2985.method_12885(class_2985.java:342)

 ... it then repeats the last two for a while.

**Comment by drcrazy** [comment]
No support for 1.19. Please, reopen if it is still reproducible in 1.20
