### ISSUE TITLE
[Crash] incorrect operation of energy storage units

### ISSUE THREAD

**Issue by Sepera-okeq** [TechReborn/TechReborn#3177]
**Describe the bug**

I found a strange bug that allows you to work from the side, where there are no obvious holes where you can put a wire and power it up. Concerns as well as medium_voltage_su/high_voltage_su and other...

P.S  The chance to catch a crash is higher with high-voltage ones.
Crash server to:
```
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2023-08-24 08:14:40
Description: Ticking block entity

java.lang.IllegalArgumentException: Amount may not be negative, but it is: -598740
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notNegative(StoragePreconditions.java:50)
	at team.reborn.energy.api.base.SimpleSidedEnergyContainer$SideStorage.extract(SimpleSidedEnergyContainer.java:92)
	at team.reborn.energy.api.EnergyStorageUtil.move(EnergyStorageUtil.java:42)
	at reborncore.common.powerSystem.PowerAcceptorBlockEntity.discharge(PowerAcceptorBlockEntity.java:189)
	at techreborn.blockentity.storage.energy.EnergyStorageBlockEntity.tick(EnergyStorageBlockEntity.java:77)
	at techreborn.blockentity.storage.energy.EnergyStorageBlockEntity.tick(EnergyStorageBlockEntity.java:47)
	at reborncore.common.BaseBlockEntityProvider.lambda$getTicker$0(BaseBlockEntityProvider.java:77)
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.redirect$bgd000$carpet$checkProcessBEs(LevelChunk.java:784)
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:660)
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:714)
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:456)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:376)
	at net.minecraft.server.MinecraftServer.redirect$cdg000$carpet-fixes$catchExceptions(MinecraftServer.java:7782)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:875)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:289)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.handler$bga000$carpet$modifiedRunLoop(MinecraftServer.java:5885)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:257)
	at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notNegative(StoragePreconditions.java:50)
	at team.reborn.energy.api.base.SimpleSidedEnergyContainer$SideStorage.extract(SimpleSidedEnergyContainer.java:92)
	at team.reborn.energy.api.EnergyStorageUtil.move(EnergyStorageUtil.java:42)
	at reborncore.common.powerSystem.PowerAcceptorBlockEntity.discharge(PowerAcceptorBlockEntity.java:189)
	at techreborn.blockentity.storage.energy.EnergyStorageBlockEntity.tick(EnergyStorageBlockEntity.java:77)
	at techreborn.blockentity.storage.energy.EnergyStorageBlockEntity.tick(EnergyStorageBlockEntity.java:47)
	at reborncore.common.BaseBlockEntityProvider.lambda$getTicker$0(BaseBlockEntityProvider.java:77)
	at net.minecraft.class_2818$class_5563.redirect$bgd000$carpet$checkProcessBEs(class_2818.java:784)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.redirect$cdg000$carpet-fixes$catchExceptions(MinecraftServer.java:7782)
Mixins in Stacktrace:
	net.minecraft.class_2818$class_5563:
		carpet.mixins.BoundTickingBlockEntity_tickMixin (carpet.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.block_entity_ticking.world_border.DirectBlockEntityTickInvokerMixin (lithium.mixins.json)
	net.minecraft.class_2818$class_5564:
		me.jellysquid.mods.lithium.mixin.world.block_entity_ticking.sleeping.WrappedBlockEntityTickInvokerAccessor (lithium.mixins.json)
	net.minecraft.class_1937:
		me.jellysquid.mods.lithium.mixin.world.inline_height.WorldMixin (lithium.mixins.json)
		dev.architectury.mixin.fabric.ExplosionPreInvoker (architectury.mixins.json)
		me.jellysquid.mods.lithium.mixin.alloc.chunk_random.WorldMixin (lithium.mixins.json)
		carpet.mixins.Level_fillUpdatesMixin (carpet.mixins.json)
		carpet.mixins.Level_getOtherEntitiesLimited (carpet.mixins.json)
		me.jellysquid.mods.lithium.mixin.block.hopper.WorldMixin (lithium.mixins.json)
		carpet.mixins.Level_scarpetPlopMixin (carpet.mixins.json)
		carpetfixes.mixins.coreSystemFixes.World_seaLevelMixin (carpet-fixes.mixins.json)
		net.kyori.adventure.platform.fabric.impl.accessor.LevelAccess (adventure-platform-fabric.accessor.mixins.json)
		me.drex.antixray.mixin.LevelMixin (antixray.mixins.json)
		carpet.mixins.Level_tickMixin (carpet.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.inline_block_access.WorldMixin (lithium.mixins.json)
		io.github.fabricators_of_create.porting_lib.transfer.mixin.common.LevelMixin (porting_lib_transfer.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.mid_tick_chunk_tasks.MixinWorld (c2me-opts-scheduling.mixins.json)
		me.jellysquid.mods.lithium.mixin.entity.collisions.intersection.WorldMixin (lithium.mixins.json)
		io.github.fabricators_of_create.porting_lib.mixin.common.entity.LevelMixin (porting_lib_entity.mixins.json)
		dev.latvian.mods.kubejs.core.mixin.common.LevelMixin (kubejs-common.mixins.json)
		com.ishland.c2me.notickvd.mixin.MixinWorld (c2me-notickvd.mixins.json)
		carpet.mixins.Level_movableBEMixin (carpet.mixins.json)
		appeng.mixins.OnNeighborUpdateMixin (ae2.mixins.json)
		me.jellysquid.mods.lithium.mixin.util.block_entity_retrieval.WorldMixin (lithium.mixins.json)
		io.github.fabricators_of_create.porting_lib.mixin.common.LevelMixin (porting_lib_base.mixins.json)
		com.teampotato.doespotatotick.mixin.EntityTickInWorldMixin (doespotatotick.mixins.json)
		carpetfixes.mixins.accessors.WorldAccessor (carpet-fixes.mixins.json)
		me.wesley1808.servercore.mixin.features.activation_range.LevelMixin (servercore.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.WorldMixin (fabric-lifecycle-events-v1.mixins.json)
		ca.spottedleaf.starlight.mixin.common.world.LevelMixin (starlight.mixins.json)
		net.blay09.mods.balm.mixin.LevelMixin (balm.mixins.json)
		carpetfixes.mixins.redstoneFixes.World_ComparatorNotUpdatingMixin (carpet-fixes.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.block_entity_ticking.sleeping.WorldMixin (lithium.mixins.json)
		com.ishland.c2me.fixes.worldgen.threading_issues.mixin.threading_detections.random_instances.MixinWorld (c2me-fixes-worldgen-threading-issues.mixins.json)
		xaero.pac.common.mixin.MixinLevel (openpartiesandclaims.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.chunk_access.WorldMixin (lithium.mixins.json)
		draylar.magna.mixin.WorldMixin (magna.mixins.json)
	net.minecraft.class_3218:
		me.wesley1808.servercore.mixin.features.spawn_chunks.ServerLevelMixin (servercore.mixins.json)
		dev.architectury.mixin.fabric.MixinServerLevel (architectury.mixins.json)
		com.ishland.vmp.mixins.general.cache_ops.biome.MixinServerWorld (vmp.mixins.json)
		net.fabricmc.fabric.mixin.lookup.ServerWorldMixin (fabric-api-lookup-api-v1.mixins.json)
		me.jellysquid.mods.lithium.mixin.entity.inactive_navigations.ServerWorldMixin (lithium.mixins.json)
		alternate.current.mixin.ServerLevelMixin (alternate-current.mixins.json)
		dev.architectury.mixin.fabric.ExplosionPreInvoker (architectury.mixins.json)
		me.jellysquid.mods.lithium.mixin.util.entity_movement_tracking.ServerWorldAccessor (lithium.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.block_entity_ticking.sleeping.ServerWorldMixin (lithium.mixins.json)
		carpetfixes.mixins.coreSystemFixes.ServerWorld_rainTimerMixin (carpet-fixes.mixins.json)
		me.jellysquid.mods.lithium.mixin.alloc.chunk_random.ServerWorldMixin (lithium.mixins.json)
		elocindev.ysns.fabric_quilt.mixin.ServerWorldMixin (ysns.fabricmixins.json)
		carpetfixes.mixins.reIntroduced.ServerWorld_zeroTickMixin (carpet-fixes.mixins.json)
		xaero.pac.common.mixin.MixinServerLevel (openpartiesandclaims.mixins.json)
		carpet.mixins.ServerLevel_spawnChunksMixin (carpet.mixins.json)
		com.ishland.c2me.threading.worldgen.mixin.MixinServerWorld (c2me-threading-worldgen.mixins.json)
		com.simibubi.create.foundation.mixin.accessor.ServerLevelAccessor (create.mixins.json)
		com.blamejared.crafttweaker.mixin.common.transform.world.level.MixinServerLevel (crafttweaker.mixins.json)
		me.wesley1808.servercore.mixin.optimizations.tickets.ServerLevelMixin (servercore.mixins.json)
		earth.terrarium.ad_astra.mixin.ServerLevelMixin (ad_astra-common.mixins.json)
		carpet.mixins.ServerLevel_scarpetMixin (carpet.mixins.json)
		me.wesley1808.servercore.mixin.features.activation_range.ServerLevelMixin (servercore.mixins.json)
		me.wesley1808.servercore.mixin.optimizations.ticking.chunk.random.ServerLevelMixin (servercore.mixins.json)
		me.drex.antixray.mixin.ServerLevelMixin (antixray.mixins.json)
		ml.pkom.mcpitanlibarch.mixin.ServerWorldTimer (mcpitanlibarch-common.mixins.json)
		me.lucko.spark.fabric.mixin.ServerWorldAccessor (spark.mixins.json)
		io.github.fabricators_of_create.porting_lib.mixin.common.ServerLevelMixin (porting_lib_base.mixins.json)
		me.steinborn.krypton.mixin.server.fastchunkentityaccess.ServerWorldMixin (krypton.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.ServerWorldMixin (fabric-lifecycle-events-v1.mixins.json)
		carpetfixes.mixins.coreSystemFixes.ServerWorld_spawnPlatformMixin (carpet-fixes.mixins.json)
		io.github.fabricators_of_create.porting_lib.transfer.mixin.common.ServerLevelMixin (porting_lib_transfer.mixins.json)
		carpetfixes.mixins.coreSystemFixes.ServerWorld_spawnChunksMixin (carpet-fixes.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.cache_strongholds.ServerLevelMixin (modernfix-common.mixins.json)
		dev.latvian.mods.kubejs.core.mixin.common.ServerLevelMixin (kubejs-common.mixins.json)
		com.ishland.vmp.mixins.playerwatching.optimize_nearby_player_lookups.MixinServerWorld (vmp.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.mid_tick_chunk_tasks.MixinServerWorld (c2me-opts-scheduling.mixins.json)
		me.jellysquid.mods.lithium.mixin.chunk.entity_class_groups.ServerWorldAccessor (lithium.mixins.json)
		carpetfixes.mixins.other.ServerWorld_tickWorldEventsMixin (carpet-fixes.mixins.json)
		ca.spottedleaf.starlight.mixin.common.world.ServerWorldMixin (starlight.mixins.json)
		com.ishland.vmp.mixins.chunk.ticking.MixinServerWorld (vmp.mixins.json)
		dev.onyxstudios.cca.mixin.entity.common.MixinServerWorld (mixins.cardinal_components_entity.json)
		carpet.mixins.ServerLevel_tickMixin (carpet.mixins.json)
		me.jellysquid.mods.lithium.mixin.profiler.ServerWorldMixin (lithium.mixins.json)
	net.minecraft.server.MinecraftServer:
		me.wesley1808.servercore.mixin.features.misc.MinecraftServerMixin (servercore.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.MinecraftServerMixin (fabric-registry-sync-v0.mixins.json)
		appeng.mixins.spatial.MinecraftServerMixin (ae2.mixins.json)
		net.fabricmc.fabric.mixin.message.MinecraftServerMixin (fabric-message-api-v1.mixins.json)
		carpet.mixins.MinecraftServer_pingPlayerSampleLimit (carpet.mixins.json)
		me.wesley1808.servercore.mixin.MinecraftServerMixin (servercore.mixins.json)
		dev.latvian.mods.kubejs.core.mixin.common.inject_resources.MinecraftServerMixin (kubejs-common.mixins.json)
		xaero.map.mixin.MixinMinecraftServer (xaeroworldmap.mixins.json)
		net.blay09.mods.balm.mixin.MinecraftServerMixin (balm.mixins.json)
		net.fabricmc.fabric.mixin.resource.loader.MinecraftServerMixin (fabric-resource-loader-v0.mixins.json)
		xaero.pac.common.mixin.MixinMinecraftServer (openpartiesandclaims.mixins.json)
		carpet.mixins.MinecraftServer_scarpetMixin (carpet.mixins.json)
		com.blamejared.crafttweaker.mixin.common.access.server.AccessMinecraftServer (crafttweaker.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.shutdown.MixinMinecraftServer (c2me-opts-scheduling.mixins.json)
		carpet.mixins.MinecraftServer_coreMixin (carpet.mixins.json)
		ml.pkom.mcpitanlibarch.mixin.MinecraftServerTimer (mcpitanlibarch-common.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.mid_tick_chunk_tasks.MixinMinecraftServer (c2me-opts-scheduling.mixins.json)
		carpetfixes.mixins.advanced.MinecraftServer_autosaveDelayMixin (carpet-fixes.mixins.json)
		io.github.fabricators_of_create.porting_lib.mixin.common.accessor.MinecraftServerAccessor (porting_lib_accessors.mixins.json)
		carpetfixes.mixins.other.MinecraftServer_eventsMixin (carpet-fixes.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.MinecraftServerMixin (fabric-lifecycle-events-v1.mixins.json)
		lol.bai.megane.runtime.mixin.MixinMinecraftServer (megane-runtime.mixins.json)
		dev.latvian.mods.kubejs.core.mixin.common.MinecraftServerMixin (kubejs-common.mixins.json)
		net.kyori.adventure.platform.fabric.impl.mixin.MinecraftServerMixin (adventure-platform-fabric.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.idle_tasks.autosave.enhanced_autosave.MixinMinecraftServer (c2me-opts-scheduling.mixins.json)
		carpet.mixins.MinecraftServer_tickspeedMixin (carpet.mixins.json)
		net.fabricmc.fabric.mixin.biome.modification.MinecraftServerMixin (fabric-biome-api-v1.mixins.json)
		org.embeddedt.modernfix.fabric.mixin.core.MinecraftServerMixin (modernfix-fabric.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.dedicated_reload_executor.MinecraftServerMixin (modernfix-common.mixins.json)
		carpetfixes.mixins.coreSystemFixes.updateSuppression.MinecraftServer_crashFixMixin (carpet-fixes.mixins.json)
		carpetfixes.mixins.accessors.MinecraftServerAccessor (carpet-fixes.mixins.json)
		net.fabricmc.fabric.mixin.biome.MinecraftServerMixin (fabric-biome-api-v1.mixins.json)
		io.github.bumblesoftware.fastload.mixin.mixins.mc1182.server.MinecraftServerMixin (fastload.mixins.json)
		aztech.modern_industrialization.mixin.runtime_resources.MinecraftServerMixin (modern_industrialization.mixins.json)
		eu.pb4.styledchat.mixin.MinecraftServerMixin (styledchat.mixins.json)
		xaero.common.mixin.MixinMinecraftServer (xaerominimap.mixins.json)

-- Block entity being ticked --
Details:
	Name: techreborn:high_voltage_su // techreborn.blockentity.storage.energy.HighVoltageSUBlockEntity
	Block: Block{techreborn:high_voltage_su}[facing=north]
	Block location: World: (-7734,66,-3908), Section: (at 10,2,12 in -484,4,-245; chunk contains blocks -7744,-64,-3920 to -7729,319,-3905), Region: (-16,-8; contains chunks -512,-256 to -481,-225, blocks -8192,-64,-4096 to -7681,319,-3585)
	Block: Block{techreborn:high_voltage_su}[facing=north]
	Block location: World: (-7734,66,-3908), Section: (at 10,2,12 in -484,4,-245; chunk contains blocks -7744,-64,-3920 to -7729,319,-3905), Region: (-16,-8; contains chunks -512,-256 to -481,-225, blocks -8192,-64,-4096 to -7681,319,-3585)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.redirect$cdg000$carpet-fixes$catchExceptions(MinecraftServer.java:7782)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.handler$bga000$carpet$modifiedRunLoop(MinecraftServer.java:5885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
Mixins in Stacktrace:
	net.minecraft.class_2818$class_5563:
		carpet.mixins.BoundTickingBlockEntity_tickMixin (carpet.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.block_entity_ticking.world_border.DirectBlockEntityTickInvokerMixin (lithium.mixins.json)
	net.minecraft.class_2818$class_5564:
		me.jellysquid.mods.lithium.mixin.world.block_entity_ticking.sleeping.WrappedBlockEntityTickInvokerAccessor (lithium.mixins.json)
	net.minecraft.class_1937:
		me.jellysquid.mods.lithium.mixin.world.inline_height.WorldMixin (lithium.mixins.json)
		dev.architectury.mixin.fabric.ExplosionPreInvoker (architectury.mixins.json)
		me.jellysquid.mods.lithium.mixin.alloc.chunk_random.WorldMixin (lithium.mixins.json)
		carpet.mixins.Level_fillUpdatesMixin (carpet.mixins.json)
		carpet.mixins.Level_getOtherEntitiesLimited (carpet.mixins.json)
		me.jellysquid.mods.lithium.mixin.block.hopper.WorldMixin (lithium.mixins.json)
		carpet.mixins.Level_scarpetPlopMixin (carpet.mixins.json)
		carpetfixes.mixins.coreSystemFixes.World_seaLevelMixin (carpet-fixes.mixins.json)
		net.kyori.adventure.platform.fabric.impl.accessor.LevelAccess (adventure-platform-fabric.accessor.mixins.json)
		me.drex.antixray.mixin.LevelMixin (antixray.mixins.json)
		carpet.mixins.Level_tickMixin (carpet.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.inline_block_access.WorldMixin (lithium.mixins.json)
		io.github.fabricators_of_create.porting_lib.transfer.mixin.common.LevelMixin (porting_lib_transfer.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.mid_tick_chunk_tasks.MixinWorld (c2me-opts-scheduling.mixins.json)
		me.jellysquid.mods.lithium.mixin.entity.collisions.intersection.WorldMixin (lithium.mixins.json)
		io.github.fabricators_of_create.porting_lib.mixin.common.entity.LevelMixin (porting_lib_entity.mixins.json)
		dev.latvian.mods.kubejs.core.mixin.common.LevelMixin (kubejs-common.mixins.json)
		com.ishland.c2me.notickvd.mixin.MixinWorld (c2me-notickvd.mixins.json)
		carpet.mixins.Level_movableBEMixin (carpet.mixins.json)
		appeng.mixins.OnNeighborUpdateMixin (ae2.mixins.json)
		me.jellysquid.mods.lithium.mixin.util.block_entity_retrieval.WorldMixin (lithium.mixins.json)
		io.github.fabricators_of_create.porting_lib.mixin.common.LevelMixin (porting_lib_base.mixins.json)
		com.teampotato.doespotatotick.mixin.EntityTickInWorldMixin (doespotatotick.mixins.json)
		carpetfixes.mixins.accessors.WorldAccessor (carpet-fixes.mixins.json)
		me.wesley1808.servercore.mixin.features.activation_range.LevelMixin (servercore.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.WorldMixin (fabric-lifecycle-events-v1.mixins.json)
		ca.spottedleaf.starlight.mixin.common.world.LevelMixin (starlight.mixins.json)
		net.blay09.mods.balm.mixin.LevelMixin (balm.mixins.json)
		carpetfixes.mixins.redstoneFixes.World_ComparatorNotUpdatingMixin (carpet-fixes.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.block_entity_ticking.sleeping.WorldMixin (lithium.mixins.json)
		com.ishland.c2me.fixes.worldgen.threading_issues.mixin.threading_detections.random_instances.MixinWorld (c2me-fixes-worldgen-threading-issues.mixins.json)
		xaero.pac.common.mixin.MixinLevel (openpartiesandclaims.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.chunk_access.WorldMixin (lithium.mixins.json)
		draylar.magna.mixin.WorldMixin (magna.mixins.json)
	net.minecraft.class_3218:
		me.wesley1808.servercore.mixin.features.spawn_chunks.ServerLevelMixin (servercore.mixins.json)
		dev.architectury.mixin.fabric.MixinServerLevel (architectury.mixins.json)
		com.ishland.vmp.mixins.general.cache_ops.biome.MixinServerWorld (vmp.mixins.json)
		net.fabricmc.fabric.mixin.lookup.ServerWorldMixin (fabric-api-lookup-api-v1.mixins.json)
		me.jellysquid.mods.lithium.mixin.entity.inactive_navigations.ServerWorldMixin (lithium.mixins.json)
		alternate.current.mixin.ServerLevelMixin (alternate-current.mixins.json)
		dev.architectury.mixin.fabric.ExplosionPreInvoker (architectury.mixins.json)
		me.jellysquid.mods.lithium.mixin.util.entity_movement_tracking.ServerWorldAccessor (lithium.mixins.json)
		me.jellysquid.mods.lithium.mixin.world.block_entity_ticking.sleeping.ServerWorldMixin (lithium.mixins.json)
		carpetfixes.mixins.coreSystemFixes.ServerWorld_rainTimerMixin (carpet-fixes.mixins.json)
		me.jellysquid.mods.lithium.mixin.alloc.chunk_random.ServerWorldMixin (lithium.mixins.json)
		elocindev.ysns.fabric_quilt.mixin.ServerWorldMixin (ysns.fabricmixins.json)
		carpetfixes.mixins.reIntroduced.ServerWorld_zeroTickMixin (carpet-fixes.mixins.json)
		xaero.pac.common.mixin.MixinServerLevel (openpartiesandclaims.mixins.json)
		carpet.mixins.ServerLevel_spawnChunksMixin (carpet.mixins.json)
		com.ishland.c2me.threading.worldgen.mixin.MixinServerWorld (c2me-threading-worldgen.mixins.json)
		com.simibubi.create.foundation.mixin.accessor.ServerLevelAccessor (create.mixins.json)
		com.blamejared.crafttweaker.mixin.common.transform.world.level.MixinServerLevel (crafttweaker.mixins.json)
		me.wesley1808.servercore.mixin.optimizations.tickets.ServerLevelMixin (servercore.mixins.json)
		earth.terrarium.ad_astra.mixin.ServerLevelMixin (ad_astra-common.mixins.json)
		carpet.mixins.ServerLevel_scarpetMixin (carpet.mixins.json)
		me.wesley1808.servercore.mixin.features.activation_range.ServerLevelMixin (servercore.mixins.json)
		me.wesley1808.servercore.mixin.optimizations.ticking.chunk.random.ServerLevelMixin (servercore.mixins.json)
		me.drex.antixray.mixin.ServerLevelMixin (antixray.mixins.json)
		ml.pkom.mcpitanlibarch.mixin.ServerWorldTimer (mcpitanlibarch-common.mixins.json)
		me.lucko.spark.fabric.mixin.ServerWorldAccessor (spark.mixins.json)
		io.github.fabricators_of_create.porting_lib.mixin.common.ServerLevelMixin (porting_lib_base.mixins.json)
		me.steinborn.krypton.mixin.server.fastchunkentityaccess.ServerWorldMixin (krypton.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.ServerWorldMixin (fabric-lifecycle-events-v1.mixins.json)
		carpetfixes.mixins.coreSystemFixes.ServerWorld_spawnPlatformMixin (carpet-fixes.mixins.json)
		io.github.fabricators_of_create.porting_lib.transfer.mixin.common.ServerLevelMixin (porting_lib_transfer.mixins.json)
		carpetfixes.mixins.coreSystemFixes.ServerWorld_spawnChunksMixin (carpet-fixes.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.cache_strongholds.ServerLevelMixin (modernfix-common.mixins.json)
		dev.latvian.mods.kubejs.core.mixin.common.ServerLevelMixin (kubejs-common.mixins.json)
		com.ishland.vmp.mixins.playerwatching.optimize_nearby_player_lookups.MixinServerWorld (vmp.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.mid_tick_chunk_tasks.MixinServerWorld (c2me-opts-scheduling.mixins.json)
		me.jellysquid.mods.lithium.mixin.chunk.entity_class_groups.ServerWorldAccessor (lithium.mixins.json)
		carpetfixes.mixins.other.ServerWorld_tickWorldEventsMixin (carpet-fixes.mixins.json)
		ca.spottedleaf.starlight.mixin.common.world.ServerWorldMixin (starlight.mixins.json)
		com.ishland.vmp.mixins.chunk.ticking.MixinServerWorld (vmp.mixins.json)
		dev.onyxstudios.cca.mixin.entity.common.MixinServerWorld (mixins.cardinal_components_entity.json)
		carpet.mixins.ServerLevel_tickMixin (carpet.mixins.json)
		me.jellysquid.mods.lithium.mixin.profiler.ServerWorldMixin (lithium.mixins.json)
	net.minecraft.server.MinecraftServer:
		me.wesley1808.servercore.mixin.features.misc.MinecraftServerMixin (servercore.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.MinecraftServerMixin (fabric-registry-sync-v0.mixins.json)
		appeng.mixins.spatial.MinecraftServerMixin (ae2.mixins.json)
		net.fabricmc.fabric.mixin.message.MinecraftServerMixin (fabric-message-api-v1.mixins.json)
		carpet.mixins.MinecraftServer_pingPlayerSampleLimit (carpet.mixins.json)
		me.wesley1808.servercore.mixin.MinecraftServerMixin (servercore.mixins.json)
		dev.latvian.mods.kubejs.core.mixin.common.inject_resources.MinecraftServerMixin (kubejs-common.mixins.json)
		xaero.map.mixin.MixinMinecraftServer (xaeroworldmap.mixins.json)
		net.blay09.mods.balm.mixin.MinecraftServerMixin (balm.mixins.json)
		net.fabricmc.fabric.mixin.resource.loader.MinecraftServerMixin (fabric-resource-loader-v0.mixins.json)
		xaero.pac.common.mixin.MixinMinecraftServer (openpartiesandclaims.mixins.json)
		carpet.mixins.MinecraftServer_scarpetMixin (carpet.mixins.json)
		com.blamejared.crafttweaker.mixin.common.access.server.AccessMinecraftServer (crafttweaker.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.shutdown.MixinMinecraftServer (c2me-opts-scheduling.mixins.json)
		carpet.mixins.MinecraftServer_coreMixin (carpet.mixins.json)
		ml.pkom.mcpitanlibarch.mixin.MinecraftServerTimer (mcpitanlibarch-common.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.mid_tick_chunk_tasks.MixinMinecraftServer (c2me-opts-scheduling.mixins.json)
		carpetfixes.mixins.advanced.MinecraftServer_autosaveDelayMixin (carpet-fixes.mixins.json)
		io.github.fabricators_of_create.porting_lib.mixin.common.accessor.MinecraftServerAccessor (porting_lib_accessors.mixins.json)
		carpetfixes.mixins.other.MinecraftServer_eventsMixin (carpet-fixes.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.MinecraftServerMixin (fabric-lifecycle-events-v1.mixins.json)
		lol.bai.megane.runtime.mixin.MixinMinecraftServer (megane-runtime.mixins.json)
		dev.latvian.mods.kubejs.core.mixin.common.MinecraftServerMixin (kubejs-common.mixins.json)
		net.kyori.adventure.platform.fabric.impl.mixin.MinecraftServerMixin (adventure-platform-fabric.mixins.json)
		com.ishland.c2me.opts.scheduling.mixin.idle_tasks.autosave.enhanced_autosave.MixinMinecraftServer (c2me-opts-scheduling.mixins.json)
		carpet.mixins.MinecraftServer_tickspeedMixin (carpet.mixins.json)
		net.fabricmc.fabric.mixin.biome.modification.MinecraftServerMixin (fabric-biome-api-v1.mixins.json)
		org.embeddedt.modernfix.fabric.mixin.core.MinecraftServerMixin (modernfix-fabric.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.dedicated_reload_executor.MinecraftServerMixin (modernfix-common.mixins.json)
		carpetfixes.mixins.coreSystemFixes.updateSuppression.MinecraftServer_crashFixMixin (carpet-fixes.mixins.json)
		carpetfixes.mixins.accessors.MinecraftServerAccessor (carpet-fixes.mixins.json)
		net.fabricmc.fabric.mixin.biome.MinecraftServerMixin (fabric-biome-api-v1.mixins.json)
		io.github.bumblesoftware.fastload.mixin.mixins.mc1182.server.MinecraftServerMixin (fastload.mixins.json)
		aztech.modern_industrialization.mixin.runtime_resources.MinecraftServerMixin (modern_industrialization.mixins.json)
		eu.pb4.styledchat.mixin.MinecraftServerMixin (styledchat.mixins.json)
		xaero.common.mixin.MixinMinecraftServer (xaerominimap.mixins.json)
	net.minecraft.class_3176:
		com.ishland.c2me.base.mixin.util.log4j2shutdownhookisnomore.MixinMinecraftDedicatedServer (c2me-base.mixins.json)
		me.drex.vanillapermissions.mixin.bypass.spawn_protection.DedicatedServerMixin (vanilla-permissions.mixins.json)
		xyz.jpenilla.betterfabricconsole.mixin.DedicatedServerMixin (better-fabric-console.mixins.json)
		dev.architectury.mixin.fabric.MixinDedicatedServer (architectury.mixins.json)
```

**Steps to Reproduce**

For this you will need hv cable and voltage su.

- put everything as done in the photo:
![image](https://github.com/TechReborn/TechReborn/assets/54331959/dea9358f-9418-41d3-a9cc-4ad08f047a81)

- put the wire here so that it starts to absorb and record energy:
![image](https://github.com/TechReborn/TechReborn/assets/54331959/ae238c48-d926-43a5-ba0c-b2176fcfe41b)

- crash! 

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19.2
 - Mod Loader: fabric, 0.14.21, latest version fabric mod

**Logs**
Fill logs: https://gist.github.com/Sepera-okeq/6d7d9c777fc88f0abcc80b5934138574

**Comment by Sepera-okeq** [comment]
P.S The bug also works when you put a thing from Ad Astra (for example, a backpack from there)
![image](https://github.com/TechReborn/TechReborn/assets/54331959/1f22625c-1142-4460-a9c7-52d0f47de635)

**Comment by Technici4n** [comment]
Hi, can you provide a minimal testing setup in creative that can be used to reproduce the issue?

**Comment by Sepera-okeq** [comment]
> Hi, can you provide a minimal testing setup in creative that can be used to reproduce the issue?

Yes! Carry any energy storage (I took a high_voltage_su one). Power it with hv wires from a creative solar panel. 

Is your vault filling up now? Now put the jet_suit from the Ad Astra mod inside the storage, and if you are alone(singleplayer), then look at the state of the world, that mobs do not react in any way, do not fight, and so on.

If you have a server, then you will have a server crash. Example: https://gist.github.com/Sepera-okeq/6d7d9c777fc88f0abcc80b5934138574

**Comment by Technici4n** [comment]
Does this happen with other powered items than the Ad Astra armor?

**Comment by drcrazy** [comment]
Can't reproduce on MC 1.20.2

![image](https://github.com/TechReborn/TechReborn/assets/1382352/705303a8-1d14-442c-b750-54f6c3f17034)
