### ISSUE TITLE
Crash all time.

### ISSUE THREAD

**Issue by Fiishbone7** [TechReborn/TechReborn#3199]
The game crashed whilst encountered exception while building chunk meshes
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.block.BlockState.isOpaque()" because "adjState" is null

**Comment by Fiishbone7** [comment]
![minecraft_qd3Pv2Zp68](https://github.com/TechReborn/TechReborn/assets/151882847/9011edd8-d225-484a-8e9a-3b101844141b)

**Comment by Fiishbone7** [comment]
[crash-2023-11-24_02.20.22-client.txt](https://github.com/TechReborn/TechReborn/files/13454281/crash-2023-11-24_02.20.22-client.txt)

**Comment by xanthian** [comment]
Why is this here?
Its not a Tech Reborn related crash.
Look at the error log. 

Its either Sodium or Mythic Upgrades.
```
-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.BlockOcclusionCache.shouldDrawSide(BlockOcclusionCache.java:40)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.isFaceVisible(BlockRenderer.java:94)
Mixins in Stacktrace:
	me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer:
		net.coderbot.iris.compat.sodium.mixin.separate_ao.MixinBlockRenderer (mixins.iris.compat.sodium.json)
		link.infra.indium.mixin.sodium.AccessBlockRenderer (indium.mixins.json)

-- Block being rendered --
Details:
	Block: Block{mythicupgrades:aquamarine_ore}
	Block location: World: (-3392,12,-3008), Section: (at 0,12,0 in -212,0,-188; chunk contains blocks -3392,-64,-3008 to -3377,319,-2993), Region: (-7,-6; contains chunks -224,-192 to -193,-161, blocks -3584,-64,-3072 to -3073,319,-2561)
	Chunk section: RenderSection at chunk (-212, 0, -188) from (-3392, 0, -3008) to (-3377, 15, -2993)
	Render context volume: class_3341{minX=-3394, minY=-2, minZ=-3010, maxX=-3375, maxY=17, maxZ=-2991}
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
Mixins in Stacktrace:
	me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask:
		com.jozufozu.flywheel.mixin.sodium.ChunkBuilderMeshingTaskMixin (flywheel.sodium.mixins.json)
		link.infra.indium.mixin.sodium.MixinChunkBuilderMeshingTask (indium.mixins.json)
		net.coderbot.iris.compat.sodium.mixin.block_id.MixinChunkRenderRebuildTask (mixins.iris.compat.sodium.json)
