### ISSUE TITLE
1.20.1 Server quantum chestplate log spam

### ISSUE THREAD

**Issue by mike1000195** [TechReborn/TechReborn#3211]
**Describe the bug**
When running 1.20.1 server, and a player equips a quantum chestplate, it repeatedly spams the console with the same message over and over again

**Steps to Reproduce**
- run 1.20.1 server with tech reborn
- equip quantum chestplate and check server console

**Console Output**

Server thread/WARN

Player ability minecraft:mayfly was updated externally (expected disabled, was enabled).
Console

java.lang.RuntimeException: stacktrace
at io.github.ladysnake.pal.impl.PalInternals.logTamperWarning(PalInternals.java:63) ~[playerabilitylib-1.8.0-4683a0cc11f08713.jar:?]
at io.github.ladysnake.pal.impl.VanillaAbilityTracker.checkConflict(VanillaAbilityTracker.java:71) ~[playerabilitylib-1.8.0-4683a0cc11f08713.jar:?]
at net.minecraft.class_3222.handler$dac000$playerabilitylib$checkAbilityConsistency(class_3222.java:12424) ~[server-intermediary.jar:?]
at net.minecraft.class_3222.method_7355(class_3222.java:1323) ~[server-intermediary.jar:?]
at techreborn.items.armor.QuantumSuitItem.tickArmor(QuantumSuitItem.java:94) ~[TechReborn-5.8.7.jar:?]
at net.minecraft.class_1657.handler$ddi011$reborncore$tick(class_1657.java:14916) ~[server-intermediary.jar:?]
at net.minecraft.class_1657.method_5773(class_1657.java) ~[server-intermediary.jar:?]
at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
at net.minecraft.class_3244.method_18784(class_3244.java:269) ~[server-intermediary.jar:?]
at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by ppyLEK** [comment]
This issue is caused by [PAL](https://github.com/Ladysnake/PlayerAbilityLib), I had the same problem and ended up removing all mods that use PAL.

**Comment by drcrazy** [comment]
It's PAL who spam. Not TR

**Comment by mike1000195** [comment]
i dont even have PAL installed into my mods folder. any ideas what else it could be?
