### ISSUE TITLE
Nano Armor causing intense server lag and crashes

### ISSUE THREAD

**Issue by tangoskett** [TechReborn/TechReborn#3250]
I have discovered that wearing nano armour is the cause of extreme lag and server crashes on my server.

In order to reproduce this behaviour all I have to do is equip (powered) nano armour

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.1
 - Fabric 0.15.11-1.20.1

[17.05 09:34:33] [Server] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2828$class_2829@57612bf0, suppressing error
[17.05 09:34:33] [Server] org.spongepowered.asm.mixin.injection.callback.CancellationExceptionThe call method_5747 is not cancellable.
[17.05 09:34:33] [Server] 	at org.spongepowered.asm.mixin.injection.callback.CallbackInfo.cancel(CallbackInfo.java:101) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
[17.05 09:34:33] [Server] 	at net.minecraft.class_1309.handler$zdp000$advanced_reborn$injectFallDamage(class_1309.java:5158) ~[server-intermediary.jar:?]
[17.05 09:34:33] [Server] 	at net.minecraft.class_1309.method_5747(class_1309.java) ~[server-intermediary.jar:?]
[17.05 09:34:33] [Server] 	at net.minecraft.class_1657.method_5747(class_1657.java:1722) ~[server-intermediary.jar:?]
[17.05 09:34:33] [Server] 	at net.minecraft.class_2248.method_9554(class_2248.java:457) ~[server-intermediary.jar:?]
[17.05 09:34:33] [Server] 	at net.minecraft.class_1297.method_5623(class_1297.java:1287) ~[server-intermediary.jar:?]
[17.05 09:34:33] [Server] 	at net.minecraft.class_1309.method_5623(class_1309.java:339) ~[server-intermediary.jar:?]
[17.05 09:34:33] [Server] 	at net.minecraft.class_3222.method_14207(class_3222.java:1004) ~[server-intermediary.jar:?]
[17.05 09:34:33] [Server] 	at net.minecraft.class_3244.method_12063(class_3244.java:1000) ~[server-intermediary.jar:?]
[17.05 09:34:33] [Server] 	at net.minecraft.class_2828.method_12272(class_2828.java:114) ~[server-intermediary.jar:?]
[17.05 09:34:33] [Server] 	at net.minecraft.class_2828$class_2829.method_11054(class_2828.java:42) ~[server-intermediary.jar:?]
[17.05 09:34:33] [Server] 	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
[17.05 09:34:33] [Server] 	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
[17.05 09:34:33] [Server] 	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
[17.05 09:34:33] [Server] 	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
[17.05 09:34:33] [Server] 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
[17.05 09:34:33] [Server] 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]

Removing the nano armour stops the above errors from producing every second.

**Comment by modmuss50** [comment]
This appears to be an advanced_reborn issue not techreborn.
