### ISSUE TITLE
1.7.10:TechReborn-1.7.10-0.7.8.1081 crushed with the industrialcraft-2-2.2.811

### ISSUE THREAD

**Issue by Amamiya-Nagisa** [TechReborn/TechReborn#331]
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 16-1-27 下午9:35
Description: Initializing game

java.lang.RuntimeException: ambiguous recipe: [[1xgt.meta.ore.normal.bedrock@8339, 1xgt.meta.ore.normal.default@8339, 1xgt.meta.ore.broken.default@8339] -> [10xgt.meta.dust@8339]]
	at ic2.core.BasicMachineRecipeManager.displayError(BasicMachineRecipeManager.java:306)
	at ic2.core.BasicMachineRecipeManager.addRecipe(BasicMachineRecipeManager.java:40)
	at techreborn.compat.recipes.RecipesIC2.addTRMaceratorRecipes(RecipesIC2.java:1256)
	at techreborn.compat.recipes.RecipesIC2.init(RecipesIC2.java:52)
	at techreborn.Core.init(Core.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:114)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ic2.core.BasicMachineRecipeManager.displayError(BasicMachineRecipeManager.java:306)
	at ic2.core.BasicMachineRecipeManager.addRecipe(BasicMachineRecipeManager.java:40)
	at techreborn.compat.recipes.RecipesIC2.addTRMaceratorRecipes(RecipesIC2.java:1256)
	at techreborn.compat.recipes.RecipesIC2.init(RecipesIC2.java:52)
	at techreborn.Core.init(Core.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:114)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 372950784 bytes (355 MB) / 1000460288 bytes (954 MB) up to 3132358656 bytes (2987 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 2 loaded mod(s)
          - VoxelMap version 1.5.14
          - Mouse Tweaks version 2.4.4
	LaunchWrapper: 44 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: appeng.transformer.asm.ASMIntegration
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: fastcraft.asm.FastCraftTransformer
          - Transformer: lain.mods.inputfix.InputFixTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: me.exz.omniocular.asm.Transformer
          - Transformer: li.cil.oc.common.asm.ClassTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: appeng.transformer.asm.ASMTweaker
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: Reika.DragonAPI.ASM.InterfaceInjector
          - Transformer: Reika.DragonAPI.ASM.APIStripper
          - Transformer: Reika.DragonAPI.ASM.DragonAPIClassTransfomer
          - Transformer: Reika.DragonAPI.ASM.FMLItemBlockPatch
          - Transformer: Reika.DragonAPI.ASM.FluidNamePatch
          - Transformer: Reika.DragonAPI.ASM.DependentMethodStripper
          - Transformer: Reika.RotaryCraft.Auxiliary.RotaryASMHandler$ASMExecutor
          - Transformer: Reika.RotaryCraft.Auxiliary.RotaryASMHandler$InterfaceVerifier
          - Transformer: com.enderio.core.common.transform.EnderCoreTransformer
          - Transformer: com.enderio.core.common.transform.EnderCoreTransformerClient
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx3000m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 67 mods loaded, 67 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1566-1.7.10.jar) 
	UCHI	Forge{10.13.4.1566} [Minecraft Forge] (forge-1.7.10-10.13.4.1566-1.7.10.jar) 
	UCHI	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHI	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHI	InputFix{1.7.x-v2} [InputFix] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHI	OmniOcularCore{1.0} [Omni Ocular Core] (minecraft.jar) 
	UCHI	OpenComputers|Core{1.5.19.37} [OpenComputers (Core)] (minecraft.jar) 
	UCHI	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHI	VersionChecker{1.1.9} [Version Checker] ([版本检测器]VersionChecker-1.7.10-1.1.9.jar) 
	UCHI	gregapi{GT6-MC1710} [Greg-API] (gregtech_1.7.10-6.01.02.jar) 
	UCHI	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHI	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHI	BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14.jar) 
	UCHI	BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14.jar) 
	UCHI	IC2{2.2.811-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.811-experimental.jar) 
	UCHI	Forestry{4.2.5.53} [Forestry for Minecraft] (forestry_1.7.10-4.2.5.53.jar) 
	UCHI	BuildCraft|Compat{7.1.3} [BuildCraft Compat] (buildcraft-compat-7.1.3.jar) 
	UCHI	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter‘s Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHI	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHI	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UCHI	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCHI	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHI	CustomOreGen{1.2.24} [Custom Ore Generation] (CustomOreGen-1.7.10-1.2.24.jar) 
	UCHI	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHI	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V10d.jar) 
	UCHI	RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V10d.jar) 
	UCHI	ElectriCraft{1.0} [ElectriCraft] (ElectriCraft 1.7.10 V10b.jar) 
	UCHI	endercore{1.7.10-0.2.0.31_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.31_beta.jar) 
	UCHI	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHI	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHI	PFAAGeologica{0.2.27} [Geologica] (PFAA-1.7.10-0.2.27.jar) 
	UCHI	gregapi_post{GT6-MC1710} [Greg-API-Post] (gregtech_1.7.10-6.01.02.jar) 
	UCHI	gregtech{GT6-MC1710} [GregTech] (gregtech_1.7.10-6.01.02.jar) 
	UCHI	ImmersiveEngineering{0.7.1.2} [Immersive Engineering] (ImmersiveEngineering-0.7.1.2.jar) 
	UCHI	immersiveintegration{0.6.6} [Immersive Integration] (immersiveintegration-0.6.6.jar) 
	UCHI	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHI	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7.jar) 
	UCHI	LittleBlocks{2.2.4.4} [Little Blocks] (LittleBlocks-2.2.4.4.jar) 
	UCHI	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHI	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHI	NEIAddons{1.12.13.38} [NEI Addons] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHI	NEIAddons|Developer{1.12.13.38} [NEI Addons: Developer Tools] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHI	NEIAddons|AppEng{1.12.13.38} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHI	NEIAddons|Botany{1.12.13.38} [NEI Addons: Botany] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHI	NEIAddons|Forestry{1.12.13.38} [NEI Addons: Forestry] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHI	NEIAddons|CraftingTables{1.12.13.38} [NEI Addons: Crafting Tables] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHI	NEIAddons|ExNihilo{1.12.13.38} [NEI Addons: Ex Nihilo] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHI	neiintegration{1.1.1} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.1.jar) 
	UCHI	OmniOcular{1.7.10-1.0build60} [Omni Ocular] (OmniOcular-1.7.10-1.0build60.jar) 
	UCHI	OpenComputers{1.5.19.37} [OpenComputers] (OpenComputers-MC1.7.10-1.5.19.37-universal.jar) 
	UCHI	PFAAChemica{0.2.27} [Chemica] (PFAA-1.7.10-0.2.27.jar) 
	UCHI	reborncore{1.1.0.15} [RebornCore] (RebornCore-1.1.0.15-universal.jar) 
	UCHE	techreborn{0.7.8.1081} [TechReborn] (TechReborn-1.7.10-0.7.8.1081-universal.jar) 
	UCHI	twintails{1.0.3} [TwinTails] (twintails-1.0.3.jar) 
	UCHI	UnicodeFontFixer{1.1.3} [UnicodeFontFixer] (UnicodeFontFixer-1.1.3-mc1.7.10.jar) 
	UCHI	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHI	wailaplugins{MC1.7.10-0.1.2-21} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.1.2-21.jar) 
	UCHI	wawla{1.3.3} [What Are We Looking At] (Wawla-1.3.3-1.7.10.jar) 
	UCHI	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHI	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics 4000'
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	Launched Version: 1.7.10-Forge10.13.4.1566-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by modmuss50** [comment]
Try removing Greg tech
