### ISSUE TITLE
PAL spitting out error in console about TechReborn.

### ISSUE THREAD

**Issue by WickedDuck** [TechReborn/TechReborn#3329]
**Describe the bug**
I keep getting an error spat out in console anytime I am in survival mode and have equipped a Quantum Chestplate.

**Steps to Reproduce**
Be in survival mode, on a fabric server running 1.20.2
Equip a Quantum Chestplate and attempt to fly with it.

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.2
 - Mod Loader: Fabric 0.16.9
 - Tech Reborn is version 5.9.0
 - PAL is 1.9.0
 - Reborn Core is 5.9.0

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
I am not Pastebinning a 1 GB latest.log file, my internet connection will die. Here is the block of text it spits out when I even equip it:
```
[16:10:02] [Server thread/WARN]: Player ability minecraft:mayfly was updated externally (expected disabled, was enabled).
java.lang.RuntimeException: stacktrace
    at io.github.ladysnake.pal.impl.PalInternals.logTamperWarning(PalInternals.java:63) ~[playerabilitylib-1.9.0-5382c7a473e6f2d6.jar:?]
    at io.github.ladysnake.pal.impl.VanillaAbilityTracker.checkConflict(VanillaAbilityTracker.java:71) ~[playerabilitylib-1.9.0-5382c7a473e6f2d6.jar:?]
    at net.minecraft.class_3222.handler$blj000$playerabilitylib$checkAbilityConsistency(class_3222.java:9448) ~[server-intermediary.jar:?]
    at net.minecraft.class_3222.method_7355(class_3222.java:1325) ~[server-intermediary.jar:?]
    at techreborn.items.armor.QuantumSuitItem.tickArmor(QuantumSuitItem.java:94) ~[TechReborn-5.9.1.jar:?]
    at net.minecraft.class_1657.handler$bmn007$reborncore$tick(class_1657.java:12419) ~[server-intermediary.jar:?]
    at net.minecraft.class_1657.method_5773(class_1657.java) ~[server-intermediary.jar:?]
    at net.minecraft.class_3222.method_14226(class_3222.java:511) ~[server-intermediary.jar:?]
    at net.minecraft.class_3244.method_18784(class_3244.java:258) ~[server-intermediary.jar:?]
    at net.minecraft.class_2535.method_10754(class_2535.java:379) ~[server-intermediary.jar:?]
    at net.minecraft.class_3242.method_14357(class_3242.java:176) ~[server-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
    at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:820) ~[server-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667) ~[server-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263) ~[server-intermediary.jar:?]
    at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Additional context**
Interestingly, being in Creative Mode does not cause PAL to display any errors. unsure as to why. In addition, this may also be the cause of why when I equip a Quantum Chestplate, the creative flight it should provide just lets me infinitely jump.

**Comment by WickedDuck** [comment]
Nevermind, this issue has already been posted here, and closed.
