### ISSUE TITLE
[1.9.4] Crash when trying to charge items with Ender IO (RF)

### ISSUE THREAD

**Issue by Kazzamkablam** [TechReborn/TechReborn#640]
Techreborn: TechReborn-1.9.4-1.3.2.120-universal.jar
Reborncore: RebornCore-1.9.4-2.5.3.44-universal.jar
Forge: 1954
Crash log: http://www.filedropper.com/fml-client-latest_4

How to reproduce:
1. craft something with charge
2. put it on Ender Io capacitor bank / or have it wirelessly charged by wireless charger

java.lang.IncompatibleClassChangeError: Found class techreborn.items.battery.ItemReBattery$$BasePowerTrait$$RFItemPowerTrait, but interface was expected
    at techreborn.items.battery.ItemReBattery$$BasePowerTrait$$RFItemPowerTrait.receiveEnergy(RFItemPowerTrait.java:28)
    at crazypants.enderio.machine.wireless.TileWirelessCharger.chargeItems(TileWirelessCharger.java:80)
    at crazypants.enderio.machine.wireless.WirelessChargerController.chargeFromCapBank(WirelessChargerController.java:107)
    at crazypants.enderio.machine.wireless.WirelessChargerController.chargePlayersItems(WirelessChargerController.java:84)
    at crazypants.enderio.machine.wireless.WirelessChargerController.onPlayerTick(WirelessChargerController.java:60)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_632_WirelessChargerController_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:357)
    at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:370)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:286)
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
    at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:163)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:193)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:730)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
    at java.lang.Thread.run(Unknown Source)

**Comment by modmuss50** [comment]
Ok this could be a hard one to fix, I will look into it

**Comment by modmuss50** [comment]
IncompatibleClassChangeError not sure what that is, I will look into it

**Comment by modmuss50** [comment]
@amadornes Any idea? Seams like Jtraits is having an issue.

**Comment by amadornes** [comment]
I have no clue what could be causing that, no... but it seems like you're supplying the modified class instead of the interface somewhere in your code

**Comment by modmuss50** [comment]
Ok thanks for the help, I will have a closer look

**Comment by 0Navis0** [comment]
TechReborn is compatible with RF ? I thought that it used a totaly different energy system, the name than IndustrialCraft.

**Comment by modmuss50** [comment]
It needs to be enabled in the reborn core config, it also supports tesla. Both of off by default

**Comment by Dragon2488** [comment]
Fixed
