### ISSUE TITLE
World will not load after constructing Industrial Grinder Multiblock.

### ISSUE THREAD

**Issue by varukasalt** [TechReborn/TechReborn#719]
Using the same seed, 3 times in a row I have created a world, then using creative mode, built and powered and Industrial Grinder multiblock. Each time after exiting the world normally, it will fail to load and hang up on the Loading World Building Terrain screen. Grinder is being fed water from an EnderIO Reservoir, power from EnderIO Vibrant Capacitor Banks and receiving and exporting material with EnderIO Item Conduits. Also, conduits will not remove any products from the 3rd output slot.

**Comment by modmuss50** [comment]
I can have the logs please?

**Comment by varukasalt** [comment]
I don't have any crash logs. I just exit normally, then the next time I try to load the world it hangs. is there any other info I can give you?

**Comment by modmuss50** [comment]
No, when I get a chance I will look into it my self.

**Comment by varukasalt** [comment]
Thank you.

**Comment by 3TUSK** [comment]
@modmuss50 I am getting similar issue while I am making an ic2 addon in my dev environment (1.10.2) today. And after several test, I suspect this in `TilePowerAcceptor`, because I used to have similar code in my mod as well:

``` java
    @Override
    @Optional.Method(modid = "IC2")
    public void onLoad() {
        if(FMLCommonHandler.instance().getEffectiveSide().isServer())
            MinecraftForge.EVENT_BUS.post(new EnergyTileLoadEvent(this));
        super.onLoad();
    }
```

For whatever reason this will cause infinite loop when you load your world again:

```
    at reborncore.common.tile.TilePowerAcceptor.onLoad(TilePowerAcceptor.java:72) ~[TilePowerAcceptor.class:?]
    at net.minecraft.world.chunk.Chunk.addTileEntity(Chunk.java:875) ~[Chunk.class:?]
    at net.minecraft.world.chunk.Chunk.addTileEntity(Chunk.java:852) ~[Chunk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:519) ~[AnvilChunkLoader.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) ~[ChunkIOProvider.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) ~[ChunkIOExecutor.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:121) ~[ChunkProviderServer.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:92) ~[ChunkProviderServer.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:138) ~[ChunkProviderServer.class:?]
    at net.minecraft.world.World.getChunkFromChunkCoords(World.java:349) ~[World.class:?]
    at net.minecraft.world.World.getChunkFromBlockCoords(World.java:341) ~[World.class:?]
    at net.minecraft.world.World.getBlockState(World.java:911) ~[World.class:?]
    at ic2.core.energy.leg.EnergyNetLocalLeg.addTileEntity(EnergyNetLocalLeg.java:187) ~[EnergyNetLocalLeg.class:?]
    at ic2.core.energy.leg.EventHandler.onEnergyTileLoad(EventHandler.java:27) ~[EventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) ~[EventBus.class:?]
    at reborncore.common.tile.TilePowerAcceptor.onLoad(TilePowerAcceptor.java:72) ~[TilePowerAcceptor.class:?]
```

And the easiest solution I know so far is post `EnergyTileLoadEvent` in `update()` which is provided by `ITickable`, and cache the status of whether the event has been posted or not, as it only need to be posted _one time_.

However, it seems possible (while i am not sure how to implement so) to post EvenrTileEvent during `onLoad()` and `onChucnkUnload()`, as it is mentioned in the `usage.txt` bundled in ic2 api jar:

> You can detect the loading by either using the 1st iteration of update() or by waiting for
> the next world tick after TileEntity.validate(). The 2nd approach is obviously more sophisticated
> and requires to use some tick queuing mechanism.

Just a quick reply~~, so if there is any technical mistake please ignore~~.

**Comment by varukasalt** [comment]
I have ic2 and many other mods running as well. I can provide a complete list if that is of any assistance.

**Comment by varukasalt** [comment]
This now also seems to be happening with Single Block machines such as the Grinder.

**Comment by varukasalt** [comment]
Seems to be resolved in latest release.
