### ISSUE TITLE
Bug: connecting Techreborn cable to other Machines [1.10.2/1.9.4]

### ISSUE THREAD

**Issue by 9t3ndo** [TechReborn/TechReborn#731]
https://youtu.be/pPWtsj6zSmg

![launcher](https://cloud.githubusercontent.com/assets/21056984/17696198/2a49b0c4-63ad-11e6-9a57-c5ecc47b70ad.jpg)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.47-beta.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 16.08.16 12:23
Description: Ticking block entity

java.lang.NoClassDefFoundError: net/darkhax/tesla/capability/TeslaCapabilities
    at techreborn.parts.powerCables.CableMultipart.shouldConnectTo(CableMultipart.java:237)
    at techreborn.parts.powerCables.CableMultipart.checkConnectedSides(CableMultipart.java:277)
    at techreborn.parts.powerCables.CableMultipart.func_73660_a(CableMultipart.java:295)
    at reborncore.mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:311)
    at net.minecraft.world.World.func_72939_s(World.java:1804)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Server thread
Stacktrace:
    at techreborn.parts.powerCables.CableMultipart.shouldConnectTo(CableMultipart.java:237)
    at techreborn.parts.powerCables.CableMultipart.checkConnectedSides(CableMultipart.java:277)
    at techreborn.parts.powerCables.CableMultipart.func_73660_a(CableMultipart.java:295)
    at reborncore.mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:311)

-- Block entity being ticked --
Details:
    Name: reborncore.mcmultipart:multipart.ticking // reborncore.mcmultipart.block.TileMultipartContainer.Ticking
    Block type: ID #420 (tile.null // reborncore.mcmultipart.block.BlockMultipartContainer)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (349,4,-38), Chunk: (at 13,0,10 in 21,-3; contains blocks 336,0,-48 to 351,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Actual block type: ID #420 (tile.null // reborncore.mcmultipart.block.BlockMultipartContainer)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1804)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
    Level name: New World
    All players: 1 total; [EntityPlayerMP['9t3ndo'/14, l='New World', x=349,72, y=4,00, z=-40,58]]
    Chunk stats: ServerChunkCache: 625 Drop: 0
    Level seed: 4716743877724861930
    Level generator: ID 01 - flat, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (359,4,-34), Chunk: (at 7,0,14 in 22,-3; contains blocks 352,0,-48 to 367,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 800 game time, 800 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 93189 (now: false), thunder time: 23189 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 317058568 bytes (302 MB) / 2048917504 bytes (1954 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2065 14 mods loaded, 14 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2065.jar) 
    UCHIJAAAA   Forge{12.18.1.2065} [Minecraft Forge](forge-1.10.2-12.18.1.2065.jar) 
    UCHIJAAAA   actuallyadditions{1.10.2-r60} [Actually Additions](ActuallyAdditions-1.10.2-r60.jar) 
    UCHIJAAAA   endercore{1.10.2-0.4.1.47-beta} [EnderCore](EnderCore-1.10.2-0.4.1.47-beta.jar) 
    UCHIJAAAA   ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.10.2-alpha-1.0.1.jar) 
    UCHIJAAAA   JEI{3.9.0.244} [Just Enough Items](jei_1.10.2-3.9.0.244.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJAAAA   EnderIO{1.10.2-3.0.1.92_beta} [Ender IO](EnderIO-1.10.2-3.0.1.92_beta.jar) 
    UCHIJAAAA   reborncore{2.6.2.15} [RebornCore](RebornCore-1.10.2-2.6.2.15-universal.jar) 
    UCHIJAAAA   reborncore-mcmultipart{2.6.2.15} [reborncore-MCMultiPart](RebornCore-1.10.2-2.6.2.15-universal.jar) 
    UCHIJAAAA   rftools{5.15} [RFTools](rftools-1.10-5.15.jar) 
    UCHIJAAAA   techreborn{1.4.0.38} [TechReborn](TechReborn-1.10.2-1.4.0.38-universal.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.10-1.1.7.jar) 
    Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.47-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    EnderIO: No known problems detected.
    Detailed RF API diagnostics:
                  \* RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/tmxbo/Documents/Curse/Minecraft/Instances/Test/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/EnergyStorage.class
                  \* RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/tmxbo/Documents/Curse/Minecraft/Instances/Test/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyConnection.class
                  \* RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/tmxbo/Documents/Curse/Minecraft/Instances/Test/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyContainerItem.class
                  \* RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/tmxbo/Documents/Curse/Minecraft/Instances/Test/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyHandler.class
                  \* RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/tmxbo/Documents/Curse/Minecraft/Instances/Test/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyProvider.class
                  \* RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/tmxbo/Documents/Curse/Minecraft/Instances/Test/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyReceiver.class
                  \* RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/tmxbo/Documents/Curse/Minecraft/Instances/Test/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyStorage.class
                  \* RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/tmxbo/Documents/Curse/Minecraft/Instances/Test/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/ItemEnergyContainer.class
                  \* RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/tmxbo/Documents/Curse/Minecraft/Instances/Test/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/TileEnergyHandler.class
                  \* RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/tmxbo/Documents/Curse/Minecraft/Instances/Test/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/TileEnergyHandler.class

```
Profiler Position: N/A (disabled)
Player Count: 1 / 8; [EntityPlayerMP['9t3ndo'/14, l='New World', x=349,72, y=4,00, z=-40,58]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by 9t3ndo** [comment]
Ok got it by my one

Change the Java Version to 1.8.0.101 x64 and edit the config of recore, fixed it for me
