### ISSUE TITLE
Energy crystal charging bug.

### ISSUE THREAD

**Issue by merx3d** [TechReborn/TechReborn#755]
When I attempted to charge an energy crystal by placing the crystal in the charging slot of a rftools coal generator it resulted in crashing the server I was playing on. Thus I also attempted to repeat the problem in single-player which resulted in a client crash. You just place a coal generator and put the crystal in, it doesn't require the generator to be generating power at the time it is placed in. Then your client or the server will crash almost immediately after.
Here is the crash-log from the event http://pastebin.com/AsFw93b7
TechReborn version: 1.4.4.54
rftools version: 1.10-5.24
MC Version; 1.10.2

**Comment by quantumsheep** [comment]
Same for me! I'm come here to post the same issue 😛

**Comment by modmuss50** [comment]
Ok thanks, I will look into this, as its happened to a lot of people

**Comment by quantumsheep** [comment]
It crashed my client in singleplayer too:

`java.lang.IncompatibleClassChangeError: Found class techreborn.items.battery.ItemEnergyCrystal$$BasePowerTrait$$RFItemPowerTrait, but interface was expected
    at techreborn.items.battery.ItemEnergyCrystal$$BasePowerTrait$$RFItemPowerTrait.receiveEnergy(RFItemPowerTrait.java:28)
    at mcjty.rftools.blocks.generator.CoalGeneratorTileEntity.handleChargingItem(CoalGeneratorTileEntity.java:134)
    at mcjty.rftools.blocks.generator.CoalGeneratorTileEntity.func_73660_a(CoalGeneratorTileEntity.java:60)
    at net.minecraft.world.World.func_72939_s(World.java:1804)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by modmuss50** [comment]
Ok, I will have to fix asap then
