### ISSUE TITLE
assembling machine not showing inventory

### ISSUE THREAD

**Issue by wolfe02** [TechReborn/TechReborn#804]
https://images-eu.curseapp.net/0ac2060c-a890-487d-ac78-b8096f282d02/Image.png
issue with the assembling machine not showing inventory
also, when I pipe the items in, it doesn't process them
tried placing a new one, doesn't work

TechReborn 1.10.2-1.4.11.96-universal

**Comment by ken-noland** [comment]
using a hopper still allows me to use the machine, but I'm not sure what happened to the inventory.

**Comment by modmuss50** [comment]
Yeah it's an issue with the gui I think, I will look into it once I get a chance

**Comment by ken-noland** [comment]
shift+clicking out of it crashes the server

`Thread: Client thread
Stacktrace:
    at java.util.ArrayList.elementData(ArrayList.java:418)
    at java.util.ArrayList.get(ArrayList.java:431)
    at reborncore.common.container.RebornContainer.shiftItemStack(RebornContainer.java:136)
    at reborncore.common.container.RebornContainer.func_82846_b(RebornContainer.java:104)
    at net.minecraft.inventory.Container.func_184996_a(Container.java:258)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
    at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:630)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:389)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)`

**Comment by ken-noland** [comment]
Hmmm... darn.... I can't put upgrades into the assembler either.

**Comment by modmuss50** [comment]
Upgrades dont work in any machines, that still needs a lot of ground work to be possible.

**Comment by ken-noland** [comment]
Gotchya, didn't know that! Thanks!
