### ISSUE TITLE
Looping NPE in Centrifuge with newest release

### ISSUE THREAD

**Issue by utoc** [TechReborn/TechReborn#809]
Log here: https://gist.github.com/utoc/e4f06fa57e0c72b02cd64a7c61761d4c

Starts around 14:31:08

TechReborn-1.10.2-1.4.12.106  
RebornCore-1.10.2-2.8.1.64  
forge-1.10.2-12.18.2.2151

Restarted server, issue still exists.  We don't get a crash but the log gets large quickly.

```[14:31:32] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[14:31:32] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[14:31:32] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at techreborn.client.container.ContainerCentrifuge.addPlayerSlots(ContainerCentrifuge.java:59)
[14:31:32] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at techreborn.client.container.ContainerCentrifuge.<init>(ContainerCentrifuge.java:26)
[14:31:32] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	... 19 more```

**Comment by utoc** [comment]
Thank you @modmuss50 !

**Comment by modmuss50** [comment]
no worries.
