### ISSUE TITLE
Crash when extracting item from Electric Alloy Furnace

### ISSUE THREAD

**Issue by brad18** [TechReborn/TechReborn#816]
Attempting to remove an item from the two input slots (via the gui) of the Electric alloy furnace will crash the game.

Time: 29/11/16 21:36
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: -28
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at reborncore.common.container.RebornContainer.shiftItemStack(RebornContainer.java:136)
	at reborncore.common.container.RebornContainer.func_82846_b(RebornContainer.java:104)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:258)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:630)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:389)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at reborncore.common.container.RebornContainer.shiftItemStack(RebornContainer.java:136)
	at reborncore.common.container.RebornContainer.func_82846_b(RebornContainer.java:104)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:258)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:630)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:389)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)

-- Affected screen --
Details:
	Screen name: techreborn.client.gui.GuiAlloySmelter

**Comment by modmuss50** [comment]
huh, ok. Thanks

**Comment by brad18** [comment]
My bad, I didn't realise my reborncore wasn't updated. It's working fine.
