### ISSUE TITLE
versions 1.11-forge1.11-13.19.1.2189 TechReborn-1.11-2.0.4.47-universal

### ISSUE THREAD

**Issue by oldestilluminat** [TechReborn/TechReborn#830]
Time: 11.12.16 18:30
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from TechReborn (techreborn)
Caused by: java.lang.NoClassDefFoundError: reborncore/client/hud/StackInfoElement
	at techreborn.init.ModItems.init(ModItems.java:278)
	at techreborn.Core.preinit(Core.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:619)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:615)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:264)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:438)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:350)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: reborncore.client.hud.StackInfoElement
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 38 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 183006544 bytes (174 MB) / 388612096 bytes (370 MB) up to 737411072 bytes (703 MB)
	JVM Flags: 5 total; -Xmx716M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.35 Powered by Forge 13.19.1.2189 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11-13.19.1.2189.jar) 
	UCH	forge{13.19.1.2189} [Minecraft Forge] (forge-1.11-13.19.1.2189.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCH	actuallyadditions{1.11-r91} [Actually Additions] (ActuallyAdditions-1.11-r91.jar) 
	UCH	craftingtweaks{7.1.1} [Crafting Tweaks] (CraftingTweaks_1.11_7.1.1.jar) 
	UCH	cxlibrary{1.3.0} [CXLibrary] (cxlibrary-1.11-1.3.0.jar) 
	UCH	dooglamoocitiesmod{1.3.3b} [Dooglamoo Cities] (dooglamoocitiesmod_1.11_1.3.3b.jar) 
	UCH	durabilityshow{4.0.0} [Durability Show] (Durability_Show_1.11_4.0.0.jar) 
	UCH	endercrop{1.11-1.3.3} [Ender Crop] (endercrop_1.11_1.3.3.jar) 
	UCH	enderrift{2.0.1} [Ender-Rift] (EnderRift_1.11.0_2.0.1 (1).jar) 
	UCH	fakeores{1.8} [Fake Ores 2] (fakeores2v1.8_mc1.11.jar) 
	UCH	ironchest{1.11-7.0.17.799} [Iron Chest] (ironchest_1.11_7.0.17.799.jar) 
	UCH	jei{4.0.5.202} [Just Enough Items] (jei_1.11-4.0.5.202.jar) 
	UCH	levelup{${version}} [Level Up!] (LevelUp_0.13_1.11.jar) 
	UCH	morefurnaces{1.9.0} [More Furnaces] (MoreFurnaces-1.11-1.9.0.jar) 
	UCH	reborncore{2.10.0.34} [RebornCore] (RebornCore-1.11-2.10.0.34-universal.jar) 
	UCH	reborncore-mcmultipart{2.10.0.34} [reborncore-MCMultiPart] (RebornCore-1.11-2.10.0.34-universal.jar) 
	UCH	shadowmc{3.7.1} [ShadowMC] (ShadowMC-1.11-3.7.1.jar) 
	UCH	signpic{2.5.1} [SignPicture] (SignPicture-1.11-2.5.1-universal.jar) 
	UCE	techreborn{2.0.4.47} [TechReborn] (TechReborn-1.11-2.0.4.47-universal.jar) 
	UCH	thutcore{4.1.1} [ThutCore] (thutcore-4.1.1.jar) 
	UCH	thuttech{5.0.0} [Thut's Tech] (thuttech-1.11-5.0.0.b.jar) 
	UCH	torohealthmod{1.10.2-1} [ToroHealth Damage Indicators] (torohealth_1.11_2.jar) 
	UCH	treechopper{1.1.1a} [Tree Chopper] (TreeChopper_1.11_1.1.1a.jar) 
	Loaded coremods (and transformers): 
CXLibraryCore (cxlibrary-1.11-1.3.0.jar)
  cubex2.cxlibrary.CoreModTransformer

**Comment by modmuss50** [comment]
Update Reborn Core
