### ISSUE TITLE
[1.11] TechReborn 2.0.8.84 - Red Garnet still broke

### ISSUE THREAD

**Issue by shortybsd** [TechReborn/TechReborn#861]
When trying to break a red gem server spams this per block attempted to be broken yet yields nothing.

[17:58:23] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_111]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_111]
	at techreborn.events.BlockBreakHandler.onBlockHarvest(BlockBreakHandler.java:16) ~[BlockBreakHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_235_BlockBreakHandler_onBlockHarvest_HarvestDropsEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:260) ~[ForgeEventFactory.class:?]
	at net.minecraft.block.Block.func_180653_a(Block.java:558) ~[als.class:?]
	at net.minecraft.block.Block.func_176226_b(Block.java:550) ~[als.class:?]
	at net.minecraft.block.Block.func_180657_a(Block.java:720) ~[als.class:?]
	at de.ellpeck.actuallyadditions.mod.util.WorldUtil.playerHarvestBlock(WorldUtil.java:344) ~[WorldUtil.class:?]
	at de.ellpeck.actuallyadditions.mod.items.ItemDrill.tryHarvestBlock(ItemDrill.java:464) ~[ItemDrill.class:?]
	at de.ellpeck.actuallyadditions.mod.items.ItemDrill.breakBlocks(ItemDrill.java:412) ~[ItemDrill.class:?]
	at de.ellpeck.actuallyadditions.mod.items.ItemDrill.onBlockStartBreak(ItemDrill.java:240) ~[ItemDrill.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:305) ~[lz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:247) ~[lz.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:637) ~[mi.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[jd.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[jd.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[17:58:26] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_111]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_111]
	at techreborn.events.BlockBreakHandler.onBlockHarvest(BlockBreakHandler.java:16) ~[BlockBreakHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_235_BlockBreakHandler_onBlockHarvest_HarvestDropsEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:260) ~[ForgeEventFactory.class:?]
	at net.minecraft.block.Block.func_180653_a(Block.java:558) ~[als.class:?]
	at net.minecraft.block.Block.func_176226_b(Block.java:550) ~[als.class:?]
	at net.minecraft.block.Block.func_180657_a(Block.java:720) ~[als.class:?]
	at de.ellpeck.actuallyadditions.mod.util.WorldUtil.playerHarvestBlock(WorldUtil.java:344) ~[WorldUtil.class:?]
	at de.ellpeck.actuallyadditions.mod.items.ItemDrill.tryHarvestBlock(ItemDrill.java:464) ~[ItemDrill.class:?]
	at de.ellpeck.actuallyadditions.mod.items.ItemDrill.breakBlocks(ItemDrill.java:412) ~[ItemDrill.class:?]
	at de.ellpeck.actuallyadditions.mod.items.ItemDrill.onBlockStartBreak(ItemDrill.java:240) ~[ItemDrill.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:305) ~[lz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:247) ~[lz.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:637) ~[mi.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[jd.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[jd.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by OrdinatorStouff** [comment]
ATM2 official server is having a similar crash. ActAdd block breaker failing on a techreborn BlockBreakHandler: http://pastebin.com/cdXJseLf
