### ISSUE TITLE
World Crashes(can not open saved world) After 1.11.2-2.1.1.42 Update

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#916]
when save world, close game, then open the game and try to open your saved world, freeze at "loading world" after the latest release for 1.11.2.
using forge 2222
i tried these: deleting config files, deleting world, deleting minecraft. and installing everything.
also tried installing techreborn and reborn core **alone**
here is the crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.1.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.6.jar)
  RebornCoreASM (RebornCore-1.11.2-2.13.1.24-universal.jar)
  MMFMLCorePlugin (MultiMine-1.11.2.jar)
  ServerPropertiesLAN (ServerPropertiesLAN-2.3.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
  IvToolkit (IvToolkit-1.3.1.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 1/19/17 12:00 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: kq
	at net.minecraftforge.fml.common.event.FMLModIdMappingEvent.<init>(FMLModIdMappingEvent.java:73)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:1064)
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.injectSnapshot(PersistentRegistryManager.java:360)
	at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:329)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:421)
	at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:119)
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:122)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:76)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:197)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Unknown Source)

**Comment by modmuss50** [comment]
Ah I fixed in this in 1.10, I will get an update out soon.

**Comment by modmuss50** [comment]
Next Reborn core update should fix the issue. Let me know if it doesnt.

**Comment by ghost** [comment]
okay waiting

**Comment by modmuss50** [comment]
Ok new RebornCore on curse, I do hope this fixes it.

**Comment by ghost** [comment]
trying. when finish i will edit this post.
edit: okay it's solved.

**Comment by modmuss50** [comment]
nice 👍
