### ISSUE TITLE
Crashing every few minutes

### ISSUE THREAD

**Issue by VanDerGroot** [TechReborn/TechReborn#930]
Getting this in the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  RebornCoreASM (RebornCore-1.11.2-2.13.1.25-universal.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 1/23/17 10:01 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at techreborn.power.TRPowerNet.tick(TRPowerNet.java:68)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_56_TRPowerNet_tick_PowerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at techreborn.events.TRTickHandler.worldTick(TRTickHandler.java:43)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_42_TRTickHandler_worldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:272)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:729)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 271135032 bytes (258 MB) / 751648768 bytes (716 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2224 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2224.jar) 
	UCHIJAAAA	forge{13.20.0.2224} [Minecraft Forge] (forge-1.11.2-13.20.0.2224.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJAAAA	jei{4.2.3.222} [Just Enough Items] (jei_1.11.2-4.2.3.222.jar) 
	UCHIJAAAA	reborncore{2.13.1.25} [RebornCore] (RebornCore-1.11.2-2.13.1.25-universal.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.13.1.25} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.13.1.25-universal.jar) 
	UCHIJAAAA	techreborn{2.1.1.42} [TechReborn] (TechReborn-1.11.2-2.1.1.42-universal.jar) 
	Loaded coremods (and transformers): 
RebornCoreASM (RebornCore-1.11.2-2.13.1.25-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['GhostNULL'/541, l='Grootia', x=43.28, y=68.00, z=194.18]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

This started happening today, after no changes to minecraft files.

**Comment by modmuss50** [comment]
Ok, a temp fix for this is to remove any power cables that you have from techreborn. I need to figure out what has started to make this happen.

**Comment by VanDerGroot** [comment]
Crap. I need those. :P Oh well. Tell me if there is anything I can do to help pinpoint the issue.

**Comment by VanDerGroot** [comment]
Crashing seized when I removed a second MFE.
