### ISSUE TITLE
Breaking cables/using wrench

### ISSUE THREAD

**Issue by Towsty** [TechReborn/TechReborn#987]
I've encountered this error in the ATM Illumination pack. 
Using:
   TechReborn 1.10.2-2.1.6.180
   RebornCore 1.10.2-2.13.4.128
   McMultipart 1.10.2-1.4.0
   Forge 12.18.3.2234

This error happens when trying to break the cables - currently only tried on insulated copper and HV cables

```javascript
[11:29:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException
[11:29:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185904_a(BlockStateContainer.java:294)
[11:29:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.item.ItemPickaxe.func_150893_a(SourceFile:85)
[11:29:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.item.ItemStack.func_150997_a(ItemStack.java:157)
[11:29:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.entity.player.InventoryPlayer.func_184438_a(InventoryPlayer.java:522)
[11:29:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.entity.player.EntityPlayer.getDigSpeed(EntityPlayer.java:808)
[11:29:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at reborncore.mcmultipart.multipart.Multipart.getStrength(Multipart.java:205)
[11:29:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at reborncore.mcmultipart.multipart.MultipartContainer.getHardness(MultipartContainer.java:350)
[11:29:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at reborncore.mcmultipart.block.BlockMultipartContainer.func_180647_a(BlockMultipartContainer.java:174)
[11:29:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:399)
[11:29:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:240)
[11:29:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180512_c(PlayerControllerMP.java:325)
[11:29:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1421)
[11:29:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2198)
[11:29:15] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
```

Here's the full log - see issue @ line 29805:
https://gist.githubusercontent.com/Towsty/7b4b67d0fa69857d6513fdfa6f9a81c8/raw/37dc7d2133429a5c405c4f8da0a982b417246eac/tr-issue-log

[fml-client-latest.txt](https://github.com/TechReborn/TechReborn/files/800072/fml-client-latest.txt)

**Comment by modmuss50** [comment]
Remove Optifine

**Comment by Towsty** [comment]
Issue persists w/o optifine.

https://gist.githubusercontent.com/Towsty/9665b035ba6ab84586e7aa25cb4bee81/raw/19267dce8856f753332aa5f0be184cb6fc4ae5e2/tr-issue-log-2

[fml-client-latest.txt](https://github.com/TechReborn/TechReborn/files/800106/fml-client-latest.txt)
